/*
 * Generated by Bluespec Compiler, version 2014.07.A (build 34078, 2014-07-30)
 * 
 * On Tue May 19 15:33:31 PDT 2020
 * 
 */
#include "bluesim_primitives.h"
#include "mkBsvTop_bsim.h"
#include "imported_BDPI_functions.h"


/* String declarations */
static std::string const __str_literal_1("ERROR: %m: mkBRAMSeverAdapter overrun", 37u);
static std::string const __str_literal_2("uartIn %d\n", 10u);
static std::string const __str_literal_3("uartOut %d\n", 11u);


/* Constructor */
MOD_mkBsvTop_bsim::MOD_mkBsvTop_bsim(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_hwmain_mem_memory(simHdl, "hwmain_mem_memory", this, (tUInt8)0u, 10u, 32u, 1024u, 2u),
    INST_hwmain_mem_serverAdapterA_cnt(simHdl,
				       "hwmain_mem_serverAdapterA_cnt",
				       this,
				       3u,
				       (tUInt8)0u,
				       (tUInt8)0u),
    INST_hwmain_mem_serverAdapterA_cnt_1(simHdl,
					 "hwmain_mem_serverAdapterA_cnt_1",
					 this,
					 3u,
					 (tUInt8)0u),
    INST_hwmain_mem_serverAdapterA_cnt_2(simHdl,
					 "hwmain_mem_serverAdapterA_cnt_2",
					 this,
					 3u,
					 (tUInt8)0u),
    INST_hwmain_mem_serverAdapterA_cnt_3(simHdl,
					 "hwmain_mem_serverAdapterA_cnt_3",
					 this,
					 3u,
					 (tUInt8)0u),
    INST_hwmain_mem_serverAdapterA_outDataCore(simHdl,
					       "hwmain_mem_serverAdapterA_outDataCore",
					       this,
					       32u,
					       3u,
					       1u,
					       0u),
    INST_hwmain_mem_serverAdapterA_outData_deqCalled(simHdl,
						     "hwmain_mem_serverAdapterA_outData_deqCalled",
						     this,
						     0u),
    INST_hwmain_mem_serverAdapterA_outData_enqData(simHdl,
						   "hwmain_mem_serverAdapterA_outData_enqData",
						   this,
						   32u,
						   (tUInt8)0u),
    INST_hwmain_mem_serverAdapterA_outData_outData(simHdl,
						   "hwmain_mem_serverAdapterA_outData_outData",
						   this,
						   32u,
						   (tUInt8)0u),
    INST_hwmain_mem_serverAdapterA_s1(simHdl,
				      "hwmain_mem_serverAdapterA_s1",
				      this,
				      2u,
				      (tUInt8)0u,
				      (tUInt8)0u),
    INST_hwmain_mem_serverAdapterA_s1_1(simHdl, "hwmain_mem_serverAdapterA_s1_1", this, 2u, (tUInt8)0u),
    INST_hwmain_mem_serverAdapterA_writeWithResp(simHdl,
						 "hwmain_mem_serverAdapterA_writeWithResp",
						 this,
						 2u,
						 (tUInt8)0u),
    INST_hwmain_mem_serverAdapterB_cnt(simHdl,
				       "hwmain_mem_serverAdapterB_cnt",
				       this,
				       3u,
				       (tUInt8)0u,
				       (tUInt8)0u),
    INST_hwmain_mem_serverAdapterB_cnt_1(simHdl,
					 "hwmain_mem_serverAdapterB_cnt_1",
					 this,
					 3u,
					 (tUInt8)0u),
    INST_hwmain_mem_serverAdapterB_cnt_2(simHdl,
					 "hwmain_mem_serverAdapterB_cnt_2",
					 this,
					 3u,
					 (tUInt8)0u),
    INST_hwmain_mem_serverAdapterB_cnt_3(simHdl,
					 "hwmain_mem_serverAdapterB_cnt_3",
					 this,
					 3u,
					 (tUInt8)0u),
    INST_hwmain_mem_serverAdapterB_outDataCore(simHdl,
					       "hwmain_mem_serverAdapterB_outDataCore",
					       this,
					       32u,
					       3u,
					       1u,
					       0u),
    INST_hwmain_mem_serverAdapterB_outData_deqCalled(simHdl,
						     "hwmain_mem_serverAdapterB_outData_deqCalled",
						     this,
						     0u),
    INST_hwmain_mem_serverAdapterB_outData_enqData(simHdl,
						   "hwmain_mem_serverAdapterB_outData_enqData",
						   this,
						   32u,
						   (tUInt8)0u),
    INST_hwmain_mem_serverAdapterB_outData_outData(simHdl,
						   "hwmain_mem_serverAdapterB_outData_outData",
						   this,
						   32u,
						   (tUInt8)0u),
    INST_hwmain_mem_serverAdapterB_s1(simHdl,
				      "hwmain_mem_serverAdapterB_s1",
				      this,
				      2u,
				      (tUInt8)0u,
				      (tUInt8)0u),
    INST_hwmain_mem_serverAdapterB_s1_1(simHdl, "hwmain_mem_serverAdapterB_s1_1", this, 2u, (tUInt8)0u),
    INST_hwmain_mem_serverAdapterB_writeWithResp(simHdl,
						 "hwmain_mem_serverAdapterB_writeWithResp",
						 this,
						 2u,
						 (tUInt8)0u),
    INST_hwmain_proc(simHdl, "hwmain_proc", this),
    INST_hwmain_relayUart(simHdl, "hwmain_relayUart", this, 8u, 2u, 1u, 0u),
    INST_initialized(simHdl, "initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_uart_inQ(simHdl, "uart_inQ", this, 8u, 2u, 1u, 0u),
    INST_uart_inReqId(simHdl, "uart_inReqId", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_uart_outCnt(simHdl, "uart_outCnt", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_uart_outQ(simHdl, "uart_outQ", this, 8u, 2u, 1u, 0u),
    PORT_RST_N((tUInt8)1u),
    DEF_v__h320(2863311530u),
    DEF_hwmain_proc_memReq___d134(68u)
{
  symbol_count = 59u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkBsvTop_bsim::init_symbols_0()
{
  init_symbol(&symbols[0u], "b__h1484", SYM_DEF, &DEF_b__h1484, 3u);
  init_symbol(&symbols[1u], "b__h2891", SYM_DEF, &DEF_b__h2891, 3u);
  init_symbol(&symbols[2u], "hwmain_mem_memory", SYM_MODULE, &INST_hwmain_mem_memory);
  init_symbol(&symbols[3u],
	      "hwmain_mem_serverAdapterA_cnt",
	      SYM_MODULE,
	      &INST_hwmain_mem_serverAdapterA_cnt);
  init_symbol(&symbols[4u],
	      "hwmain_mem_serverAdapterA_cnt_1",
	      SYM_MODULE,
	      &INST_hwmain_mem_serverAdapterA_cnt_1);
  init_symbol(&symbols[5u],
	      "hwmain_mem_serverAdapterA_cnt_2",
	      SYM_MODULE,
	      &INST_hwmain_mem_serverAdapterA_cnt_2);
  init_symbol(&symbols[6u],
	      "hwmain_mem_serverAdapterA_cnt_3",
	      SYM_MODULE,
	      &INST_hwmain_mem_serverAdapterA_cnt_3);
  init_symbol(&symbols[7u],
	      "hwmain_mem_serverAdapterA_outData_deqCalled",
	      SYM_MODULE,
	      &INST_hwmain_mem_serverAdapterA_outData_deqCalled);
  init_symbol(&symbols[8u],
	      "hwmain_mem_serverAdapterA_outData_enqData",
	      SYM_MODULE,
	      &INST_hwmain_mem_serverAdapterA_outData_enqData);
  init_symbol(&symbols[9u],
	      "hwmain_mem_serverAdapterA_outData_outData",
	      SYM_MODULE,
	      &INST_hwmain_mem_serverAdapterA_outData_outData);
  init_symbol(&symbols[10u],
	      "hwmain_mem_serverAdapterA_outDataCore",
	      SYM_MODULE,
	      &INST_hwmain_mem_serverAdapterA_outDataCore);
  init_symbol(&symbols[11u],
	      "hwmain_mem_serverAdapterA_s1",
	      SYM_MODULE,
	      &INST_hwmain_mem_serverAdapterA_s1);
  init_symbol(&symbols[12u],
	      "hwmain_mem_serverAdapterA_s1_1",
	      SYM_MODULE,
	      &INST_hwmain_mem_serverAdapterA_s1_1);
  init_symbol(&symbols[13u],
	      "hwmain_mem_serverAdapterA_writeWithResp",
	      SYM_MODULE,
	      &INST_hwmain_mem_serverAdapterA_writeWithResp);
  init_symbol(&symbols[14u],
	      "hwmain_mem_serverAdapterB_cnt",
	      SYM_MODULE,
	      &INST_hwmain_mem_serverAdapterB_cnt);
  init_symbol(&symbols[15u],
	      "hwmain_mem_serverAdapterB_cnt_1",
	      SYM_MODULE,
	      &INST_hwmain_mem_serverAdapterB_cnt_1);
  init_symbol(&symbols[16u],
	      "hwmain_mem_serverAdapterB_cnt_2",
	      SYM_MODULE,
	      &INST_hwmain_mem_serverAdapterB_cnt_2);
  init_symbol(&symbols[17u],
	      "hwmain_mem_serverAdapterB_cnt_3",
	      SYM_MODULE,
	      &INST_hwmain_mem_serverAdapterB_cnt_3);
  init_symbol(&symbols[18u],
	      "hwmain_mem_serverAdapterB_outData_deqCalled",
	      SYM_MODULE,
	      &INST_hwmain_mem_serverAdapterB_outData_deqCalled);
  init_symbol(&symbols[19u],
	      "hwmain_mem_serverAdapterB_outData_enqData",
	      SYM_MODULE,
	      &INST_hwmain_mem_serverAdapterB_outData_enqData);
  init_symbol(&symbols[20u],
	      "hwmain_mem_serverAdapterB_outData_outData",
	      SYM_MODULE,
	      &INST_hwmain_mem_serverAdapterB_outData_outData);
  init_symbol(&symbols[21u],
	      "hwmain_mem_serverAdapterB_outDataCore",
	      SYM_MODULE,
	      &INST_hwmain_mem_serverAdapterB_outDataCore);
  init_symbol(&symbols[22u],
	      "hwmain_mem_serverAdapterB_s1",
	      SYM_MODULE,
	      &INST_hwmain_mem_serverAdapterB_s1);
  init_symbol(&symbols[23u],
	      "hwmain_mem_serverAdapterB_s1_1",
	      SYM_MODULE,
	      &INST_hwmain_mem_serverAdapterB_s1_1);
  init_symbol(&symbols[24u],
	      "hwmain_mem_serverAdapterB_writeWithResp",
	      SYM_MODULE,
	      &INST_hwmain_mem_serverAdapterB_writeWithResp);
  init_symbol(&symbols[25u], "hwmain_proc", SYM_MODULE, &INST_hwmain_proc);
  init_symbol(&symbols[26u], "hwmain_relayUart", SYM_MODULE, &INST_hwmain_relayUart);
  init_symbol(&symbols[27u], "initialized", SYM_MODULE, &INST_initialized);
  init_symbol(&symbols[28u], "RL_doinit", SYM_RULE);
  init_symbol(&symbols[29u], "RL_hwmain_mem_serverAdapterA_cnt_finalAdd", SYM_RULE);
  init_symbol(&symbols[30u], "RL_hwmain_mem_serverAdapterA_moveToOutFIFO", SYM_RULE);
  init_symbol(&symbols[31u], "RL_hwmain_mem_serverAdapterA_outData_deqOnly", SYM_RULE);
  init_symbol(&symbols[32u], "RL_hwmain_mem_serverAdapterA_outData_enqAndDeq", SYM_RULE);
  init_symbol(&symbols[33u], "RL_hwmain_mem_serverAdapterA_outData_enqOnly", SYM_RULE);
  init_symbol(&symbols[34u], "RL_hwmain_mem_serverAdapterA_outData_setFirstCore", SYM_RULE);
  init_symbol(&symbols[35u], "RL_hwmain_mem_serverAdapterA_outData_setFirstEnq", SYM_RULE);
  init_symbol(&symbols[36u], "RL_hwmain_mem_serverAdapterA_overRun", SYM_RULE);
  init_symbol(&symbols[37u], "RL_hwmain_mem_serverAdapterA_s1__dreg_update", SYM_RULE);
  init_symbol(&symbols[38u], "RL_hwmain_mem_serverAdapterA_stageReadResponseAlways", SYM_RULE);
  init_symbol(&symbols[39u], "RL_hwmain_mem_serverAdapterB_cnt_finalAdd", SYM_RULE);
  init_symbol(&symbols[40u], "RL_hwmain_mem_serverAdapterB_moveToOutFIFO", SYM_RULE);
  init_symbol(&symbols[41u], "RL_hwmain_mem_serverAdapterB_outData_deqOnly", SYM_RULE);
  init_symbol(&symbols[42u], "RL_hwmain_mem_serverAdapterB_outData_enqAndDeq", SYM_RULE);
  init_symbol(&symbols[43u], "RL_hwmain_mem_serverAdapterB_outData_enqOnly", SYM_RULE);
  init_symbol(&symbols[44u], "RL_hwmain_mem_serverAdapterB_outData_setFirstCore", SYM_RULE);
  init_symbol(&symbols[45u], "RL_hwmain_mem_serverAdapterB_outData_setFirstEnq", SYM_RULE);
  init_symbol(&symbols[46u], "RL_hwmain_mem_serverAdapterB_overRun", SYM_RULE);
  init_symbol(&symbols[47u], "RL_hwmain_mem_serverAdapterB_s1__dreg_update", SYM_RULE);
  init_symbol(&symbols[48u], "RL_hwmain_mem_serverAdapterB_stageReadResponseAlways", SYM_RULE);
  init_symbol(&symbols[49u], "RL_hwmain_rpReq", SYM_RULE);
  init_symbol(&symbols[50u], "RL_hwmain_rpResp", SYM_RULE);
  init_symbol(&symbols[51u], "RL_relayUartIn", SYM_RULE);
  init_symbol(&symbols[52u], "RL_relayUartOut", SYM_RULE);
  init_symbol(&symbols[53u], "RL_uart_relayIn", SYM_RULE);
  init_symbol(&symbols[54u], "RL_uart_relayOut", SYM_RULE);
  init_symbol(&symbols[55u], "uart_inQ", SYM_MODULE, &INST_uart_inQ);
  init_symbol(&symbols[56u], "uart_inReqId", SYM_MODULE, &INST_uart_inReqId);
  init_symbol(&symbols[57u], "uart_outCnt", SYM_MODULE, &INST_uart_outCnt);
  init_symbol(&symbols[58u], "uart_outQ", SYM_MODULE, &INST_uart_outQ);
}


/* Rule actions */

void MOD_mkBsvTop_bsim::RL_uart_relayOut()
{
  tUInt8 DEF_x__h370;
  tUInt8 DEF_TASK_bdpiUartGet_BITS_15_TO_8_EQ_0___d5;
  tUInt8 DEF_data__h337;
  tUInt8 DEF_flg__h338;
  tUInt8 DEF_x__h395;
  DEF_x__h395 = INST_uart_inReqId.METH_read();
  DEF_x__h370 = (tUInt8)255u & (DEF_x__h395 + (tUInt8)1u);
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h320 = bdpiUartGet(DEF_x__h395);
  DEF_flg__h338 = (tUInt8)((tUInt8)255u & (DEF_v__h320 >> 8u));
  DEF_data__h337 = (tUInt8)((tUInt8)255u & DEF_v__h320);
  DEF_TASK_bdpiUartGet_BITS_15_TO_8_EQ_0___d5 = DEF_flg__h338 == (tUInt8)0u;
  if (DEF_TASK_bdpiUartGet_BITS_15_TO_8_EQ_0___d5)
    INST_uart_inReqId.METH_write(DEF_x__h370);
  if (DEF_TASK_bdpiUartGet_BITS_15_TO_8_EQ_0___d5)
    INST_uart_outQ.METH_enq(DEF_data__h337);
}

void MOD_mkBsvTop_bsim::RL_uart_relayIn()
{
  tUInt32 DEF__0_CONCAT_uart_outCnt_CONCAT_uart_inQ_first__1___d12;
  tUInt8 DEF_x__h463;
  tUInt8 DEF_d__h450;
  tUInt8 DEF_x__h473;
  DEF_x__h473 = INST_uart_outCnt.METH_read();
  DEF_d__h450 = INST_uart_inQ.METH_first();
  DEF_x__h463 = (tUInt8)255u & (DEF_x__h473 + (tUInt8)1u);
  DEF__0_CONCAT_uart_outCnt_CONCAT_uart_inQ_first__1___d12 = (((tUInt32)(DEF_x__h473)) << 8u) | (tUInt32)(DEF_d__h450);
  INST_uart_inQ.METH_deq();
  INST_uart_outCnt.METH_write(DEF_x__h463);
  if (!(PORT_RST_N == (tUInt8)0u))
    bdpiUartPut(DEF__0_CONCAT_uart_outCnt_CONCAT_uart_inQ_first__1___d12);
}

void MOD_mkBsvTop_bsim::RL_hwmain_mem_serverAdapterA_outData_setFirstCore()
{
  tUInt32 DEF_x__h995;
  DEF_x__h995 = INST_hwmain_mem_serverAdapterA_outDataCore.METH_first();
  INST_hwmain_mem_serverAdapterA_outData_outData.METH_wset(DEF_x__h995);
}

void MOD_mkBsvTop_bsim::RL_hwmain_mem_serverAdapterA_outData_setFirstEnq()
{
  DEF_x__h1086 = INST_hwmain_mem_serverAdapterA_outData_enqData.METH_wget();
  INST_hwmain_mem_serverAdapterA_outData_outData.METH_wset(DEF_x__h1086);
}

void MOD_mkBsvTop_bsim::RL_hwmain_mem_serverAdapterA_outData_enqOnly()
{
  DEF_x__h1086 = INST_hwmain_mem_serverAdapterA_outData_enqData.METH_wget();
  INST_hwmain_mem_serverAdapterA_outDataCore.METH_enq(DEF_x__h1086);
}

void MOD_mkBsvTop_bsim::RL_hwmain_mem_serverAdapterA_outData_deqOnly()
{
  INST_hwmain_mem_serverAdapterA_outDataCore.METH_deq();
}

void MOD_mkBsvTop_bsim::RL_hwmain_mem_serverAdapterA_outData_enqAndDeq()
{
  DEF_x__h1086 = INST_hwmain_mem_serverAdapterA_outData_enqData.METH_wget();
  INST_hwmain_mem_serverAdapterA_outDataCore.METH_enq(DEF_x__h1086);
  INST_hwmain_mem_serverAdapterA_outDataCore.METH_deq();
}

void MOD_mkBsvTop_bsim::RL_hwmain_mem_serverAdapterA_cnt_finalAdd()
{
  tUInt8 DEF_IF_hwmain_mem_serverAdapterA_cnt_3_whas__5_THE_ETC___d45;
  tUInt8 DEF_b__h1464;
  DEF_b__h1464 = INST_hwmain_mem_serverAdapterA_cnt_3.METH_wget();
  DEF_b__h1484 = INST_hwmain_mem_serverAdapterA_cnt.METH_read();
  DEF_hwmain_mem_serverAdapterA_cnt_3_whas____d35 = INST_hwmain_mem_serverAdapterA_cnt_3.METH_whas();
  DEF_hwmain_mem_serverAdapterA_cnt_2_whas____d33 = INST_hwmain_mem_serverAdapterA_cnt_2.METH_whas();
  DEF_hwmain_mem_serverAdapterA_cnt_1_whas____d32 = INST_hwmain_mem_serverAdapterA_cnt_1.METH_whas();
  DEF_IF_hwmain_mem_serverAdapterA_cnt_3_whas__5_THE_ETC___d45 = DEF_hwmain_mem_serverAdapterA_cnt_3_whas____d35 ? DEF_b__h1464 : (tUInt8)7u & (((tUInt8)7u & (DEF_b__h1484 + (DEF_hwmain_mem_serverAdapterA_cnt_1_whas____d32 ? INST_hwmain_mem_serverAdapterA_cnt_1.METH_wget() : (tUInt8)0u))) + (DEF_hwmain_mem_serverAdapterA_cnt_2_whas____d33 ? INST_hwmain_mem_serverAdapterA_cnt_2.METH_wget() : (tUInt8)0u));
  INST_hwmain_mem_serverAdapterA_cnt.METH_write(DEF_IF_hwmain_mem_serverAdapterA_cnt_3_whas__5_THE_ETC___d45);
}

void MOD_mkBsvTop_bsim::RL_hwmain_mem_serverAdapterA_s1__dreg_update()
{
  tUInt8 DEF_hwmain_mem_serverAdapterA_s1_1_whas__6_AND_0_O_ETC___d54;
  tUInt8 DEF_IF_hwmain_mem_serverAdapterA_s1_1_wget__7_BIT__ETC___d52;
  tUInt8 DEF_hwmain_mem_serverAdapterA_s1_1_wget__7_BIT_0___d51;
  tUInt8 DEF_hwmain_mem_serverAdapterA_s1_1_wget__7_BIT_1___d48;
  tUInt8 DEF_hwmain_mem_serverAdapterA_s1_1_whas____d46;
  tUInt8 DEF_hwmain_mem_serverAdapterA_s1_1_wget____d47;
  DEF_hwmain_mem_serverAdapterA_s1_1_wget____d47 = INST_hwmain_mem_serverAdapterA_s1_1.METH_wget();
  DEF_hwmain_mem_serverAdapterA_s1_1_whas____d46 = INST_hwmain_mem_serverAdapterA_s1_1.METH_whas();
  DEF_hwmain_mem_serverAdapterA_s1_1_wget__7_BIT_1___d48 = (tUInt8)(DEF_hwmain_mem_serverAdapterA_s1_1_wget____d47 >> 1u);
  DEF_hwmain_mem_serverAdapterA_s1_1_wget__7_BIT_0___d51 = (tUInt8)((tUInt8)1u & DEF_hwmain_mem_serverAdapterA_s1_1_wget____d47);
  DEF_IF_hwmain_mem_serverAdapterA_s1_1_wget__7_BIT__ETC___d52 = DEF_hwmain_mem_serverAdapterA_s1_1_wget__7_BIT_1___d48 ? DEF_hwmain_mem_serverAdapterA_s1_1_wget__7_BIT_0___d51 : DEF_hwmain_mem_serverAdapterA_s1_1_wget__7_BIT_0___d51;
  DEF_hwmain_mem_serverAdapterA_s1_1_whas__6_AND_0_O_ETC___d54 = (tUInt8)3u & (((DEF_hwmain_mem_serverAdapterA_s1_1_whas____d46 && DEF_hwmain_mem_serverAdapterA_s1_1_wget__7_BIT_1___d48) << 1u) | (DEF_hwmain_mem_serverAdapterA_s1_1_whas____d46 ? DEF_IF_hwmain_mem_serverAdapterA_s1_1_wget__7_BIT__ETC___d52 : DEF_IF_hwmain_mem_serverAdapterA_s1_1_wget__7_BIT__ETC___d52));
  INST_hwmain_mem_serverAdapterA_s1.METH_write(DEF_hwmain_mem_serverAdapterA_s1_1_whas__6_AND_0_O_ETC___d54);
}

void MOD_mkBsvTop_bsim::RL_hwmain_mem_serverAdapterA_stageReadResponseAlways()
{
  tUInt8 DEF__1_CONCAT_NOT_hwmain_mem_serverAdapterA_writeWi_ETC___d61;
  tUInt8 DEF_NOT_hwmain_mem_serverAdapterA_writeWithResp_wg_ETC___d60;
  tUInt8 DEF_ab_BIT_0___h1987;
  tUInt8 DEF_ab_BIT_1___h1981;
  tUInt8 DEF_ab__h1973;
  DEF_ab__h1973 = INST_hwmain_mem_serverAdapterA_writeWithResp.METH_wget();
  DEF_ab_BIT_1___h1981 = (tUInt8)(DEF_ab__h1973 >> 1u);
  DEF_ab_BIT_0___h1987 = (tUInt8)((tUInt8)1u & DEF_ab__h1973);
  DEF_NOT_hwmain_mem_serverAdapterA_writeWithResp_wg_ETC___d60 = !DEF_ab_BIT_1___h1981 || DEF_ab_BIT_0___h1987;
  DEF__1_CONCAT_NOT_hwmain_mem_serverAdapterA_writeWi_ETC___d61 = (tUInt8)3u & (((tUInt8)1u << 1u) | DEF_NOT_hwmain_mem_serverAdapterA_writeWithResp_wg_ETC___d60);
  INST_hwmain_mem_serverAdapterA_s1_1.METH_wset(DEF__1_CONCAT_NOT_hwmain_mem_serverAdapterA_writeWi_ETC___d61);
  if (DEF_NOT_hwmain_mem_serverAdapterA_writeWithResp_wg_ETC___d60)
    INST_hwmain_mem_serverAdapterA_cnt_1.METH_wset((tUInt8)1u);
}

void MOD_mkBsvTop_bsim::RL_hwmain_mem_serverAdapterA_moveToOutFIFO()
{
  tUInt32 DEF_v__h2090;
  DEF_v__h2090 = INST_hwmain_mem_memory.METH_a_read();
  DEF_hwmain_mem_serverAdapterA_s1___d62 = INST_hwmain_mem_serverAdapterA_s1.METH_read();
  DEF_hwmain_mem_serverAdapterA_s1_2_BIT_0___d63 = (tUInt8)((tUInt8)1u & DEF_hwmain_mem_serverAdapterA_s1___d62);
  if (DEF_hwmain_mem_serverAdapterA_s1_2_BIT_0___d63)
    INST_hwmain_mem_serverAdapterA_outData_enqData.METH_wset(DEF_v__h2090);
}

void MOD_mkBsvTop_bsim::RL_hwmain_mem_serverAdapterA_overRun()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s", &__str_literal_1);
}

void MOD_mkBsvTop_bsim::RL_hwmain_mem_serverAdapterB_outData_setFirstCore()
{
  tUInt32 DEF_x__h2404;
  DEF_x__h2404 = INST_hwmain_mem_serverAdapterB_outDataCore.METH_first();
  INST_hwmain_mem_serverAdapterB_outData_outData.METH_wset(DEF_x__h2404);
}

void MOD_mkBsvTop_bsim::RL_hwmain_mem_serverAdapterB_outData_setFirstEnq()
{
  DEF_x__h2493 = INST_hwmain_mem_serverAdapterB_outData_enqData.METH_wget();
  INST_hwmain_mem_serverAdapterB_outData_outData.METH_wset(DEF_x__h2493);
}

void MOD_mkBsvTop_bsim::RL_hwmain_mem_serverAdapterB_outData_enqOnly()
{
  DEF_x__h2493 = INST_hwmain_mem_serverAdapterB_outData_enqData.METH_wget();
  INST_hwmain_mem_serverAdapterB_outDataCore.METH_enq(DEF_x__h2493);
}

void MOD_mkBsvTop_bsim::RL_hwmain_mem_serverAdapterB_outData_deqOnly()
{
  INST_hwmain_mem_serverAdapterB_outDataCore.METH_deq();
}

void MOD_mkBsvTop_bsim::RL_hwmain_mem_serverAdapterB_outData_enqAndDeq()
{
  DEF_x__h2493 = INST_hwmain_mem_serverAdapterB_outData_enqData.METH_wget();
  INST_hwmain_mem_serverAdapterB_outDataCore.METH_enq(DEF_x__h2493);
  INST_hwmain_mem_serverAdapterB_outDataCore.METH_deq();
}

void MOD_mkBsvTop_bsim::RL_hwmain_mem_serverAdapterB_cnt_finalAdd()
{
  tUInt8 DEF_IF_hwmain_mem_serverAdapterB_cnt_3_whas__4_THE_ETC___d104;
  tUInt8 DEF_b__h2871;
  DEF_b__h2871 = INST_hwmain_mem_serverAdapterB_cnt_3.METH_wget();
  DEF_b__h2891 = INST_hwmain_mem_serverAdapterB_cnt.METH_read();
  DEF_hwmain_mem_serverAdapterB_cnt_3_whas____d94 = INST_hwmain_mem_serverAdapterB_cnt_3.METH_whas();
  DEF_hwmain_mem_serverAdapterB_cnt_2_whas____d92 = INST_hwmain_mem_serverAdapterB_cnt_2.METH_whas();
  DEF_hwmain_mem_serverAdapterB_cnt_1_whas____d91 = INST_hwmain_mem_serverAdapterB_cnt_1.METH_whas();
  DEF_IF_hwmain_mem_serverAdapterB_cnt_3_whas__4_THE_ETC___d104 = DEF_hwmain_mem_serverAdapterB_cnt_3_whas____d94 ? DEF_b__h2871 : (tUInt8)7u & (((tUInt8)7u & (DEF_b__h2891 + (DEF_hwmain_mem_serverAdapterB_cnt_1_whas____d91 ? INST_hwmain_mem_serverAdapterB_cnt_1.METH_wget() : (tUInt8)0u))) + (DEF_hwmain_mem_serverAdapterB_cnt_2_whas____d92 ? INST_hwmain_mem_serverAdapterB_cnt_2.METH_wget() : (tUInt8)0u));
  INST_hwmain_mem_serverAdapterB_cnt.METH_write(DEF_IF_hwmain_mem_serverAdapterB_cnt_3_whas__4_THE_ETC___d104);
}

void MOD_mkBsvTop_bsim::RL_hwmain_mem_serverAdapterB_s1__dreg_update()
{
  tUInt8 DEF_hwmain_mem_serverAdapterB_s1_1_whas__05_AND_0__ETC___d113;
  tUInt8 DEF_IF_hwmain_mem_serverAdapterB_s1_1_wget__06_BIT_ETC___d111;
  tUInt8 DEF_hwmain_mem_serverAdapterB_s1_1_wget__06_BIT_0___d110;
  tUInt8 DEF_hwmain_mem_serverAdapterB_s1_1_wget__06_BIT_1___d107;
  tUInt8 DEF_hwmain_mem_serverAdapterB_s1_1_whas____d105;
  tUInt8 DEF_hwmain_mem_serverAdapterB_s1_1_wget____d106;
  DEF_hwmain_mem_serverAdapterB_s1_1_wget____d106 = INST_hwmain_mem_serverAdapterB_s1_1.METH_wget();
  DEF_hwmain_mem_serverAdapterB_s1_1_whas____d105 = INST_hwmain_mem_serverAdapterB_s1_1.METH_whas();
  DEF_hwmain_mem_serverAdapterB_s1_1_wget__06_BIT_1___d107 = (tUInt8)(DEF_hwmain_mem_serverAdapterB_s1_1_wget____d106 >> 1u);
  DEF_hwmain_mem_serverAdapterB_s1_1_wget__06_BIT_0___d110 = (tUInt8)((tUInt8)1u & DEF_hwmain_mem_serverAdapterB_s1_1_wget____d106);
  DEF_IF_hwmain_mem_serverAdapterB_s1_1_wget__06_BIT_ETC___d111 = DEF_hwmain_mem_serverAdapterB_s1_1_wget__06_BIT_1___d107 ? DEF_hwmain_mem_serverAdapterB_s1_1_wget__06_BIT_0___d110 : DEF_hwmain_mem_serverAdapterB_s1_1_wget__06_BIT_0___d110;
  DEF_hwmain_mem_serverAdapterB_s1_1_whas__05_AND_0__ETC___d113 = (tUInt8)3u & (((DEF_hwmain_mem_serverAdapterB_s1_1_whas____d105 && DEF_hwmain_mem_serverAdapterB_s1_1_wget__06_BIT_1___d107) << 1u) | (DEF_hwmain_mem_serverAdapterB_s1_1_whas____d105 ? DEF_IF_hwmain_mem_serverAdapterB_s1_1_wget__06_BIT_ETC___d111 : DEF_IF_hwmain_mem_serverAdapterB_s1_1_wget__06_BIT_ETC___d111));
  INST_hwmain_mem_serverAdapterB_s1.METH_write(DEF_hwmain_mem_serverAdapterB_s1_1_whas__05_AND_0__ETC___d113);
}

void MOD_mkBsvTop_bsim::RL_hwmain_mem_serverAdapterB_stageReadResponseAlways()
{
  tUInt8 DEF__1_CONCAT_NOT_hwmain_mem_serverAdapterB_writeWi_ETC___d120;
  tUInt8 DEF_NOT_hwmain_mem_serverAdapterB_writeWithResp_wg_ETC___d119;
  tUInt8 DEF_ab_BIT_0___h3394;
  tUInt8 DEF_ab_BIT_1___h3388;
  tUInt8 DEF_ab__h3380;
  DEF_ab__h3380 = INST_hwmain_mem_serverAdapterB_writeWithResp.METH_wget();
  DEF_ab_BIT_1___h3388 = (tUInt8)(DEF_ab__h3380 >> 1u);
  DEF_ab_BIT_0___h3394 = (tUInt8)((tUInt8)1u & DEF_ab__h3380);
  DEF_NOT_hwmain_mem_serverAdapterB_writeWithResp_wg_ETC___d119 = !DEF_ab_BIT_1___h3388 || DEF_ab_BIT_0___h3394;
  DEF__1_CONCAT_NOT_hwmain_mem_serverAdapterB_writeWi_ETC___d120 = (tUInt8)3u & (((tUInt8)1u << 1u) | DEF_NOT_hwmain_mem_serverAdapterB_writeWithResp_wg_ETC___d119);
  INST_hwmain_mem_serverAdapterB_s1_1.METH_wset(DEF__1_CONCAT_NOT_hwmain_mem_serverAdapterB_writeWi_ETC___d120);
  if (DEF_NOT_hwmain_mem_serverAdapterB_writeWithResp_wg_ETC___d119)
    INST_hwmain_mem_serverAdapterB_cnt_1.METH_wset((tUInt8)1u);
}

void MOD_mkBsvTop_bsim::RL_hwmain_mem_serverAdapterB_moveToOutFIFO()
{
  tUInt32 DEF_v__h3497;
  DEF_v__h3497 = INST_hwmain_mem_memory.METH_b_read();
  DEF_hwmain_mem_serverAdapterB_s1___d121 = INST_hwmain_mem_serverAdapterB_s1.METH_read();
  DEF_hwmain_mem_serverAdapterB_s1_21_BIT_0___d122 = (tUInt8)((tUInt8)1u & DEF_hwmain_mem_serverAdapterB_s1___d121);
  if (DEF_hwmain_mem_serverAdapterB_s1_21_BIT_0___d122)
    INST_hwmain_mem_serverAdapterB_outData_enqData.METH_wset(DEF_v__h3497);
}

void MOD_mkBsvTop_bsim::RL_hwmain_mem_serverAdapterB_overRun()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s", &__str_literal_1);
}

void MOD_mkBsvTop_bsim::RL_hwmain_rpReq()
{
  tUInt32 DEF_IF_hwmain_proc_memReq_34_BIT_67_35_THEN_hwmain_ETC___d138;
  tUInt8 DEF_hwmain_proc_memReq_34_BIT_67___d135;
  tUInt8 DEF_hwmain_proc_memReq_34_BITS_67_TO_66___d139;
  tUInt32 DEF_x2__h3643;
  tUInt32 DEF_x3__h3644;
  tUWide DEF_AVMeth_hwmain_proc_memReq(68u, false);
  DEF_AVMeth_hwmain_proc_memReq = INST_hwmain_proc.METH_memReq();
  DEF_hwmain_proc_memReq___d134 = DEF_AVMeth_hwmain_proc_memReq;
  DEF_x3__h3644 = primExtract32(32u, 68u, DEF_hwmain_proc_memReq___d134, 32u, 34u, 32u, 3u);
  DEF_x2__h3643 = DEF_hwmain_proc_memReq___d134.get_bits_in_word32(1u, 5u, 10u);
  DEF_hwmain_proc_memReq_34_BITS_67_TO_66___d139 = DEF_hwmain_proc_memReq___d134.get_bits_in_word8(2u,
												   2u,
												   2u);
  DEF_hwmain_proc_memReq_34_BIT_67___d135 = DEF_hwmain_proc_memReq___d134.get_bits_in_word8(2u,
											    3u,
											    1u);
  DEF_IF_hwmain_proc_memReq_34_BIT_67_35_THEN_hwmain_ETC___d138 = DEF_hwmain_proc_memReq_34_BIT_67___d135 ? DEF_x3__h3644 : DEF_x3__h3644;
  INST_hwmain_mem_memory.METH_a_put(DEF_hwmain_proc_memReq_34_BIT_67___d135,
				    DEF_x2__h3643,
				    DEF_IF_hwmain_proc_memReq_34_BIT_67_35_THEN_hwmain_ETC___d138);
  INST_hwmain_mem_serverAdapterA_writeWithResp.METH_wset(DEF_hwmain_proc_memReq_34_BITS_67_TO_66___d139);
}

void MOD_mkBsvTop_bsim::RL_hwmain_rpResp()
{
  tUInt32 DEF_v__h3778;
  DEF_v__h3778 = INST_hwmain_mem_serverAdapterA_outData_outData.METH_wget();
  INST_hwmain_mem_serverAdapterA_outData_deqCalled.METH_wset();
  INST_hwmain_mem_serverAdapterA_cnt_2.METH_wset((tUInt8)7u);
  INST_hwmain_proc.METH_memResp(DEF_v__h3778);
}

void MOD_mkBsvTop_bsim::RL_doinit()
{
  INST_initialized.METH_write((tUInt8)1u);
  if (!(PORT_RST_N == (tUInt8)0u))
    bdpiSwInit();
}

void MOD_mkBsvTop_bsim::RL_relayUartIn()
{
  tUInt32 DEF_x2__h4229;
  tUInt32 DEF_x3__h4230;
  tUInt8 DEF_v__h4111;
  DEF_v__h4111 = INST_uart_outQ.METH_first();
  DEF_x3__h4230 = (tUInt32)(DEF_v__h4111);
  DEF_x2__h4229 = 1023u & ((((tUInt32)((tUInt8)0u)) << 8u) | (tUInt32)(DEF_v__h4111));
  INST_uart_outQ.METH_deq();
  INST_hwmain_relayUart.METH_enq(DEF_v__h4111);
  INST_hwmain_mem_memory.METH_b_put((tUInt8)1u, DEF_x2__h4229, DEF_x3__h4230);
  INST_hwmain_mem_serverAdapterB_writeWithResp.METH_wset((tUInt8)2u);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_write(sim_hdl, this, "s,8", &__str_literal_2, DEF_v__h4111);
}

void MOD_mkBsvTop_bsim::RL_relayUartOut()
{
  tUInt8 DEF_d__h4327;
  DEF_d__h4327 = INST_hwmain_relayUart.METH_first();
  INST_hwmain_relayUart.METH_deq();
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_write(sim_hdl, this, "s,8", &__str_literal_3, DEF_d__h4327);
  INST_uart_inQ.METH_enq(DEF_d__h4327);
}


/* Methods */


/* Reset routines */

void MOD_mkBsvTop_bsim::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_uart_outQ.reset_RST(ARG_rst_in);
  INST_uart_outCnt.reset_RST(ARG_rst_in);
  INST_uart_inReqId.reset_RST(ARG_rst_in);
  INST_uart_inQ.reset_RST(ARG_rst_in);
  INST_initialized.reset_RST(ARG_rst_in);
  INST_hwmain_relayUart.reset_RST(ARG_rst_in);
  INST_hwmain_proc.reset_RST_N(ARG_rst_in);
  INST_hwmain_mem_serverAdapterB_s1.reset_RST(ARG_rst_in);
  INST_hwmain_mem_serverAdapterB_outDataCore.reset_RST(ARG_rst_in);
  INST_hwmain_mem_serverAdapterB_cnt.reset_RST(ARG_rst_in);
  INST_hwmain_mem_serverAdapterA_s1.reset_RST(ARG_rst_in);
  INST_hwmain_mem_serverAdapterA_outDataCore.reset_RST(ARG_rst_in);
  INST_hwmain_mem_serverAdapterA_cnt.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkBsvTop_bsim::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkBsvTop_bsim::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_hwmain_mem_memory.dump_state(indent + 2u);
  INST_hwmain_mem_serverAdapterA_cnt.dump_state(indent + 2u);
  INST_hwmain_mem_serverAdapterA_cnt_1.dump_state(indent + 2u);
  INST_hwmain_mem_serverAdapterA_cnt_2.dump_state(indent + 2u);
  INST_hwmain_mem_serverAdapterA_cnt_3.dump_state(indent + 2u);
  INST_hwmain_mem_serverAdapterA_outDataCore.dump_state(indent + 2u);
  INST_hwmain_mem_serverAdapterA_outData_deqCalled.dump_state(indent + 2u);
  INST_hwmain_mem_serverAdapterA_outData_enqData.dump_state(indent + 2u);
  INST_hwmain_mem_serverAdapterA_outData_outData.dump_state(indent + 2u);
  INST_hwmain_mem_serverAdapterA_s1.dump_state(indent + 2u);
  INST_hwmain_mem_serverAdapterA_s1_1.dump_state(indent + 2u);
  INST_hwmain_mem_serverAdapterA_writeWithResp.dump_state(indent + 2u);
  INST_hwmain_mem_serverAdapterB_cnt.dump_state(indent + 2u);
  INST_hwmain_mem_serverAdapterB_cnt_1.dump_state(indent + 2u);
  INST_hwmain_mem_serverAdapterB_cnt_2.dump_state(indent + 2u);
  INST_hwmain_mem_serverAdapterB_cnt_3.dump_state(indent + 2u);
  INST_hwmain_mem_serverAdapterB_outDataCore.dump_state(indent + 2u);
  INST_hwmain_mem_serverAdapterB_outData_deqCalled.dump_state(indent + 2u);
  INST_hwmain_mem_serverAdapterB_outData_enqData.dump_state(indent + 2u);
  INST_hwmain_mem_serverAdapterB_outData_outData.dump_state(indent + 2u);
  INST_hwmain_mem_serverAdapterB_s1.dump_state(indent + 2u);
  INST_hwmain_mem_serverAdapterB_s1_1.dump_state(indent + 2u);
  INST_hwmain_mem_serverAdapterB_writeWithResp.dump_state(indent + 2u);
  INST_hwmain_proc.dump_state(indent + 2u);
  INST_hwmain_relayUart.dump_state(indent + 2u);
  INST_initialized.dump_state(indent + 2u);
  INST_uart_inQ.dump_state(indent + 2u);
  INST_uart_inReqId.dump_state(indent + 2u);
  INST_uart_outCnt.dump_state(indent + 2u);
  INST_uart_outQ.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkBsvTop_bsim::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 46u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h1484", 3u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h2891", 3u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "hwmain_mem_serverAdapterA_cnt_1_whas____d32", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "hwmain_mem_serverAdapterA_cnt_2_whas____d33", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "hwmain_mem_serverAdapterA_cnt_3_whas____d35", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "hwmain_mem_serverAdapterA_s1_2_BIT_0___d63", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "hwmain_mem_serverAdapterA_s1___d62", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "hwmain_mem_serverAdapterB_cnt_1_whas____d91", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "hwmain_mem_serverAdapterB_cnt_2_whas____d92", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "hwmain_mem_serverAdapterB_cnt_3_whas____d94", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "hwmain_mem_serverAdapterB_s1_21_BIT_0___d122", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "hwmain_mem_serverAdapterB_s1___d121", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "hwmain_proc_memReq___d134", 68u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h320", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h1086", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h2493", 32u);
  num = INST_hwmain_mem_memory.dump_VCD_defs(num);
  num = INST_hwmain_mem_serverAdapterA_cnt.dump_VCD_defs(num);
  num = INST_hwmain_mem_serverAdapterA_cnt_1.dump_VCD_defs(num);
  num = INST_hwmain_mem_serverAdapterA_cnt_2.dump_VCD_defs(num);
  num = INST_hwmain_mem_serverAdapterA_cnt_3.dump_VCD_defs(num);
  num = INST_hwmain_mem_serverAdapterA_outDataCore.dump_VCD_defs(num);
  num = INST_hwmain_mem_serverAdapterA_outData_deqCalled.dump_VCD_defs(num);
  num = INST_hwmain_mem_serverAdapterA_outData_enqData.dump_VCD_defs(num);
  num = INST_hwmain_mem_serverAdapterA_outData_outData.dump_VCD_defs(num);
  num = INST_hwmain_mem_serverAdapterA_s1.dump_VCD_defs(num);
  num = INST_hwmain_mem_serverAdapterA_s1_1.dump_VCD_defs(num);
  num = INST_hwmain_mem_serverAdapterA_writeWithResp.dump_VCD_defs(num);
  num = INST_hwmain_mem_serverAdapterB_cnt.dump_VCD_defs(num);
  num = INST_hwmain_mem_serverAdapterB_cnt_1.dump_VCD_defs(num);
  num = INST_hwmain_mem_serverAdapterB_cnt_2.dump_VCD_defs(num);
  num = INST_hwmain_mem_serverAdapterB_cnt_3.dump_VCD_defs(num);
  num = INST_hwmain_mem_serverAdapterB_outDataCore.dump_VCD_defs(num);
  num = INST_hwmain_mem_serverAdapterB_outData_deqCalled.dump_VCD_defs(num);
  num = INST_hwmain_mem_serverAdapterB_outData_enqData.dump_VCD_defs(num);
  num = INST_hwmain_mem_serverAdapterB_outData_outData.dump_VCD_defs(num);
  num = INST_hwmain_mem_serverAdapterB_s1.dump_VCD_defs(num);
  num = INST_hwmain_mem_serverAdapterB_s1_1.dump_VCD_defs(num);
  num = INST_hwmain_mem_serverAdapterB_writeWithResp.dump_VCD_defs(num);
  num = INST_hwmain_relayUart.dump_VCD_defs(num);
  num = INST_initialized.dump_VCD_defs(num);
  num = INST_uart_inQ.dump_VCD_defs(num);
  num = INST_uart_inReqId.dump_VCD_defs(num);
  num = INST_uart_outCnt.dump_VCD_defs(num);
  num = INST_uart_outQ.dump_VCD_defs(num);
  if (levels != 1u)
  {
    unsigned int l = levels == 0u ? 0u : levels - 1u;
    num = INST_hwmain_proc.dump_VCD_defs(l);
  }
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkBsvTop_bsim::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkBsvTop_bsim &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
  if (levels != 1u)
    vcd_submodules(dt, levels - 1u, backing);
}

void MOD_mkBsvTop_bsim::vcd_defs(tVCDDumpType dt, MOD_mkBsvTop_bsim &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 3u);
    vcd_write_x(sim_hdl, num++, 3u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 68u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_b__h1484) != DEF_b__h1484)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h1484, 3u);
	backing.DEF_b__h1484 = DEF_b__h1484;
      }
      ++num;
      if ((backing.DEF_b__h2891) != DEF_b__h2891)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h2891, 3u);
	backing.DEF_b__h2891 = DEF_b__h2891;
      }
      ++num;
      if ((backing.DEF_hwmain_mem_serverAdapterA_cnt_1_whas____d32) != DEF_hwmain_mem_serverAdapterA_cnt_1_whas____d32)
      {
	vcd_write_val(sim_hdl, num, DEF_hwmain_mem_serverAdapterA_cnt_1_whas____d32, 1u);
	backing.DEF_hwmain_mem_serverAdapterA_cnt_1_whas____d32 = DEF_hwmain_mem_serverAdapterA_cnt_1_whas____d32;
      }
      ++num;
      if ((backing.DEF_hwmain_mem_serverAdapterA_cnt_2_whas____d33) != DEF_hwmain_mem_serverAdapterA_cnt_2_whas____d33)
      {
	vcd_write_val(sim_hdl, num, DEF_hwmain_mem_serverAdapterA_cnt_2_whas____d33, 1u);
	backing.DEF_hwmain_mem_serverAdapterA_cnt_2_whas____d33 = DEF_hwmain_mem_serverAdapterA_cnt_2_whas____d33;
      }
      ++num;
      if ((backing.DEF_hwmain_mem_serverAdapterA_cnt_3_whas____d35) != DEF_hwmain_mem_serverAdapterA_cnt_3_whas____d35)
      {
	vcd_write_val(sim_hdl, num, DEF_hwmain_mem_serverAdapterA_cnt_3_whas____d35, 1u);
	backing.DEF_hwmain_mem_serverAdapterA_cnt_3_whas____d35 = DEF_hwmain_mem_serverAdapterA_cnt_3_whas____d35;
      }
      ++num;
      if ((backing.DEF_hwmain_mem_serverAdapterA_s1_2_BIT_0___d63) != DEF_hwmain_mem_serverAdapterA_s1_2_BIT_0___d63)
      {
	vcd_write_val(sim_hdl, num, DEF_hwmain_mem_serverAdapterA_s1_2_BIT_0___d63, 1u);
	backing.DEF_hwmain_mem_serverAdapterA_s1_2_BIT_0___d63 = DEF_hwmain_mem_serverAdapterA_s1_2_BIT_0___d63;
      }
      ++num;
      if ((backing.DEF_hwmain_mem_serverAdapterA_s1___d62) != DEF_hwmain_mem_serverAdapterA_s1___d62)
      {
	vcd_write_val(sim_hdl, num, DEF_hwmain_mem_serverAdapterA_s1___d62, 2u);
	backing.DEF_hwmain_mem_serverAdapterA_s1___d62 = DEF_hwmain_mem_serverAdapterA_s1___d62;
      }
      ++num;
      if ((backing.DEF_hwmain_mem_serverAdapterB_cnt_1_whas____d91) != DEF_hwmain_mem_serverAdapterB_cnt_1_whas____d91)
      {
	vcd_write_val(sim_hdl, num, DEF_hwmain_mem_serverAdapterB_cnt_1_whas____d91, 1u);
	backing.DEF_hwmain_mem_serverAdapterB_cnt_1_whas____d91 = DEF_hwmain_mem_serverAdapterB_cnt_1_whas____d91;
      }
      ++num;
      if ((backing.DEF_hwmain_mem_serverAdapterB_cnt_2_whas____d92) != DEF_hwmain_mem_serverAdapterB_cnt_2_whas____d92)
      {
	vcd_write_val(sim_hdl, num, DEF_hwmain_mem_serverAdapterB_cnt_2_whas____d92, 1u);
	backing.DEF_hwmain_mem_serverAdapterB_cnt_2_whas____d92 = DEF_hwmain_mem_serverAdapterB_cnt_2_whas____d92;
      }
      ++num;
      if ((backing.DEF_hwmain_mem_serverAdapterB_cnt_3_whas____d94) != DEF_hwmain_mem_serverAdapterB_cnt_3_whas____d94)
      {
	vcd_write_val(sim_hdl, num, DEF_hwmain_mem_serverAdapterB_cnt_3_whas____d94, 1u);
	backing.DEF_hwmain_mem_serverAdapterB_cnt_3_whas____d94 = DEF_hwmain_mem_serverAdapterB_cnt_3_whas____d94;
      }
      ++num;
      if ((backing.DEF_hwmain_mem_serverAdapterB_s1_21_BIT_0___d122) != DEF_hwmain_mem_serverAdapterB_s1_21_BIT_0___d122)
      {
	vcd_write_val(sim_hdl, num, DEF_hwmain_mem_serverAdapterB_s1_21_BIT_0___d122, 1u);
	backing.DEF_hwmain_mem_serverAdapterB_s1_21_BIT_0___d122 = DEF_hwmain_mem_serverAdapterB_s1_21_BIT_0___d122;
      }
      ++num;
      if ((backing.DEF_hwmain_mem_serverAdapterB_s1___d121) != DEF_hwmain_mem_serverAdapterB_s1___d121)
      {
	vcd_write_val(sim_hdl, num, DEF_hwmain_mem_serverAdapterB_s1___d121, 2u);
	backing.DEF_hwmain_mem_serverAdapterB_s1___d121 = DEF_hwmain_mem_serverAdapterB_s1___d121;
      }
      ++num;
      if ((backing.DEF_hwmain_proc_memReq___d134) != DEF_hwmain_proc_memReq___d134)
      {
	vcd_write_val(sim_hdl, num, DEF_hwmain_proc_memReq___d134, 68u);
	backing.DEF_hwmain_proc_memReq___d134 = DEF_hwmain_proc_memReq___d134;
      }
      ++num;
      if ((backing.DEF_v__h320) != DEF_v__h320)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h320, 32u);
	backing.DEF_v__h320 = DEF_v__h320;
      }
      ++num;
      if ((backing.DEF_x__h1086) != DEF_x__h1086)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h1086, 32u);
	backing.DEF_x__h1086 = DEF_x__h1086;
      }
      ++num;
      if ((backing.DEF_x__h2493) != DEF_x__h2493)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h2493, 32u);
	backing.DEF_x__h2493 = DEF_x__h2493;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_b__h1484, 3u);
      backing.DEF_b__h1484 = DEF_b__h1484;
      vcd_write_val(sim_hdl, num++, DEF_b__h2891, 3u);
      backing.DEF_b__h2891 = DEF_b__h2891;
      vcd_write_val(sim_hdl, num++, DEF_hwmain_mem_serverAdapterA_cnt_1_whas____d32, 1u);
      backing.DEF_hwmain_mem_serverAdapterA_cnt_1_whas____d32 = DEF_hwmain_mem_serverAdapterA_cnt_1_whas____d32;
      vcd_write_val(sim_hdl, num++, DEF_hwmain_mem_serverAdapterA_cnt_2_whas____d33, 1u);
      backing.DEF_hwmain_mem_serverAdapterA_cnt_2_whas____d33 = DEF_hwmain_mem_serverAdapterA_cnt_2_whas____d33;
      vcd_write_val(sim_hdl, num++, DEF_hwmain_mem_serverAdapterA_cnt_3_whas____d35, 1u);
      backing.DEF_hwmain_mem_serverAdapterA_cnt_3_whas____d35 = DEF_hwmain_mem_serverAdapterA_cnt_3_whas____d35;
      vcd_write_val(sim_hdl, num++, DEF_hwmain_mem_serverAdapterA_s1_2_BIT_0___d63, 1u);
      backing.DEF_hwmain_mem_serverAdapterA_s1_2_BIT_0___d63 = DEF_hwmain_mem_serverAdapterA_s1_2_BIT_0___d63;
      vcd_write_val(sim_hdl, num++, DEF_hwmain_mem_serverAdapterA_s1___d62, 2u);
      backing.DEF_hwmain_mem_serverAdapterA_s1___d62 = DEF_hwmain_mem_serverAdapterA_s1___d62;
      vcd_write_val(sim_hdl, num++, DEF_hwmain_mem_serverAdapterB_cnt_1_whas____d91, 1u);
      backing.DEF_hwmain_mem_serverAdapterB_cnt_1_whas____d91 = DEF_hwmain_mem_serverAdapterB_cnt_1_whas____d91;
      vcd_write_val(sim_hdl, num++, DEF_hwmain_mem_serverAdapterB_cnt_2_whas____d92, 1u);
      backing.DEF_hwmain_mem_serverAdapterB_cnt_2_whas____d92 = DEF_hwmain_mem_serverAdapterB_cnt_2_whas____d92;
      vcd_write_val(sim_hdl, num++, DEF_hwmain_mem_serverAdapterB_cnt_3_whas____d94, 1u);
      backing.DEF_hwmain_mem_serverAdapterB_cnt_3_whas____d94 = DEF_hwmain_mem_serverAdapterB_cnt_3_whas____d94;
      vcd_write_val(sim_hdl, num++, DEF_hwmain_mem_serverAdapterB_s1_21_BIT_0___d122, 1u);
      backing.DEF_hwmain_mem_serverAdapterB_s1_21_BIT_0___d122 = DEF_hwmain_mem_serverAdapterB_s1_21_BIT_0___d122;
      vcd_write_val(sim_hdl, num++, DEF_hwmain_mem_serverAdapterB_s1___d121, 2u);
      backing.DEF_hwmain_mem_serverAdapterB_s1___d121 = DEF_hwmain_mem_serverAdapterB_s1___d121;
      vcd_write_val(sim_hdl, num++, DEF_hwmain_proc_memReq___d134, 68u);
      backing.DEF_hwmain_proc_memReq___d134 = DEF_hwmain_proc_memReq___d134;
      vcd_write_val(sim_hdl, num++, DEF_v__h320, 32u);
      backing.DEF_v__h320 = DEF_v__h320;
      vcd_write_val(sim_hdl, num++, DEF_x__h1086, 32u);
      backing.DEF_x__h1086 = DEF_x__h1086;
      vcd_write_val(sim_hdl, num++, DEF_x__h2493, 32u);
      backing.DEF_x__h2493 = DEF_x__h2493;
    }
}

void MOD_mkBsvTop_bsim::vcd_prims(tVCDDumpType dt, MOD_mkBsvTop_bsim &backing)
{
  INST_hwmain_mem_memory.dump_VCD(dt, backing.INST_hwmain_mem_memory);
  INST_hwmain_mem_serverAdapterA_cnt.dump_VCD(dt, backing.INST_hwmain_mem_serverAdapterA_cnt);
  INST_hwmain_mem_serverAdapterA_cnt_1.dump_VCD(dt, backing.INST_hwmain_mem_serverAdapterA_cnt_1);
  INST_hwmain_mem_serverAdapterA_cnt_2.dump_VCD(dt, backing.INST_hwmain_mem_serverAdapterA_cnt_2);
  INST_hwmain_mem_serverAdapterA_cnt_3.dump_VCD(dt, backing.INST_hwmain_mem_serverAdapterA_cnt_3);
  INST_hwmain_mem_serverAdapterA_outDataCore.dump_VCD(dt,
						      backing.INST_hwmain_mem_serverAdapterA_outDataCore);
  INST_hwmain_mem_serverAdapterA_outData_deqCalled.dump_VCD(dt,
							    backing.INST_hwmain_mem_serverAdapterA_outData_deqCalled);
  INST_hwmain_mem_serverAdapterA_outData_enqData.dump_VCD(dt,
							  backing.INST_hwmain_mem_serverAdapterA_outData_enqData);
  INST_hwmain_mem_serverAdapterA_outData_outData.dump_VCD(dt,
							  backing.INST_hwmain_mem_serverAdapterA_outData_outData);
  INST_hwmain_mem_serverAdapterA_s1.dump_VCD(dt, backing.INST_hwmain_mem_serverAdapterA_s1);
  INST_hwmain_mem_serverAdapterA_s1_1.dump_VCD(dt, backing.INST_hwmain_mem_serverAdapterA_s1_1);
  INST_hwmain_mem_serverAdapterA_writeWithResp.dump_VCD(dt,
							backing.INST_hwmain_mem_serverAdapterA_writeWithResp);
  INST_hwmain_mem_serverAdapterB_cnt.dump_VCD(dt, backing.INST_hwmain_mem_serverAdapterB_cnt);
  INST_hwmain_mem_serverAdapterB_cnt_1.dump_VCD(dt, backing.INST_hwmain_mem_serverAdapterB_cnt_1);
  INST_hwmain_mem_serverAdapterB_cnt_2.dump_VCD(dt, backing.INST_hwmain_mem_serverAdapterB_cnt_2);
  INST_hwmain_mem_serverAdapterB_cnt_3.dump_VCD(dt, backing.INST_hwmain_mem_serverAdapterB_cnt_3);
  INST_hwmain_mem_serverAdapterB_outDataCore.dump_VCD(dt,
						      backing.INST_hwmain_mem_serverAdapterB_outDataCore);
  INST_hwmain_mem_serverAdapterB_outData_deqCalled.dump_VCD(dt,
							    backing.INST_hwmain_mem_serverAdapterB_outData_deqCalled);
  INST_hwmain_mem_serverAdapterB_outData_enqData.dump_VCD(dt,
							  backing.INST_hwmain_mem_serverAdapterB_outData_enqData);
  INST_hwmain_mem_serverAdapterB_outData_outData.dump_VCD(dt,
							  backing.INST_hwmain_mem_serverAdapterB_outData_outData);
  INST_hwmain_mem_serverAdapterB_s1.dump_VCD(dt, backing.INST_hwmain_mem_serverAdapterB_s1);
  INST_hwmain_mem_serverAdapterB_s1_1.dump_VCD(dt, backing.INST_hwmain_mem_serverAdapterB_s1_1);
  INST_hwmain_mem_serverAdapterB_writeWithResp.dump_VCD(dt,
							backing.INST_hwmain_mem_serverAdapterB_writeWithResp);
  INST_hwmain_relayUart.dump_VCD(dt, backing.INST_hwmain_relayUart);
  INST_initialized.dump_VCD(dt, backing.INST_initialized);
  INST_uart_inQ.dump_VCD(dt, backing.INST_uart_inQ);
  INST_uart_inReqId.dump_VCD(dt, backing.INST_uart_inReqId);
  INST_uart_outCnt.dump_VCD(dt, backing.INST_uart_outCnt);
  INST_uart_outQ.dump_VCD(dt, backing.INST_uart_outQ);
}

void MOD_mkBsvTop_bsim::vcd_submodules(tVCDDumpType dt,
				       unsigned int levels,
				       MOD_mkBsvTop_bsim &backing)
{
  INST_hwmain_proc.dump_VCD(dt, levels, backing.INST_hwmain_proc);
}
