/*
 * Generated by Bluespec Compiler, version 2014.07.A (build 34078, 2014-07-30)
 * 
 * On Tue May 19 15:33:31 PDT 2020
 * 
 */

/* Generation options: */
#ifndef __mkProcessor_h__
#define __mkProcessor_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkProcessor module */
class MOD_mkProcessor : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_cycles;
  MOD_Fifo<tUWide> INST_d2e;
  MOD_Fifo<tUWide> INST_e2m;
  MOD_Reg<tUInt8> INST_epoch;
  MOD_Fifo<tUWide> INST_f2d;
  MOD_Wire<tUInt64> INST_forwardE;
  MOD_Reg<tUInt32> INST_instCnt;
  MOD_Fifo<tUWide> INST_mem_dm_reqQ;
  MOD_Fifo<tUInt32> INST_mem_dm_respQ;
  MOD_Fifo<tUWide> INST_mem_im_reqQ;
  MOD_Fifo<tUInt32> INST_mem_im_respQ;
  MOD_Fifo<tUWide> INST_mem_reqQ;
  MOD_Fifo<tUInt8> INST_mem_reqTargetIsIMemQ;
  MOD_Fifo<tUInt32> INST_mem_respQ;
  MOD_Fifo<tUInt32> INST_nextpcQ;
  MOD_Reg<tUInt32> INST_pc;
  MOD_Reg<tUInt32> INST_rf_rfile_0;
  MOD_Reg<tUInt32> INST_rf_rfile_1;
  MOD_Reg<tUInt32> INST_rf_rfile_10;
  MOD_Reg<tUInt32> INST_rf_rfile_11;
  MOD_Reg<tUInt32> INST_rf_rfile_12;
  MOD_Reg<tUInt32> INST_rf_rfile_13;
  MOD_Reg<tUInt32> INST_rf_rfile_14;
  MOD_Reg<tUInt32> INST_rf_rfile_15;
  MOD_Reg<tUInt32> INST_rf_rfile_16;
  MOD_Reg<tUInt32> INST_rf_rfile_17;
  MOD_Reg<tUInt32> INST_rf_rfile_18;
  MOD_Reg<tUInt32> INST_rf_rfile_19;
  MOD_Reg<tUInt32> INST_rf_rfile_2;
  MOD_Reg<tUInt32> INST_rf_rfile_20;
  MOD_Reg<tUInt32> INST_rf_rfile_21;
  MOD_Reg<tUInt32> INST_rf_rfile_22;
  MOD_Reg<tUInt32> INST_rf_rfile_23;
  MOD_Reg<tUInt32> INST_rf_rfile_24;
  MOD_Reg<tUInt32> INST_rf_rfile_25;
  MOD_Reg<tUInt32> INST_rf_rfile_26;
  MOD_Reg<tUInt32> INST_rf_rfile_27;
  MOD_Reg<tUInt32> INST_rf_rfile_28;
  MOD_Reg<tUInt32> INST_rf_rfile_29;
  MOD_Reg<tUInt32> INST_rf_rfile_3;
  MOD_Reg<tUInt32> INST_rf_rfile_30;
  MOD_Reg<tUInt32> INST_rf_rfile_31;
  MOD_Reg<tUInt32> INST_rf_rfile_4;
  MOD_Reg<tUInt32> INST_rf_rfile_5;
  MOD_Reg<tUInt32> INST_rf_rfile_6;
  MOD_Reg<tUInt32> INST_rf_rfile_7;
  MOD_Reg<tUInt32> INST_rf_rfile_8;
  MOD_Reg<tUInt32> INST_rf_rfile_9;
  MOD_Reg<tUInt8> INST_sb_datav_0;
  MOD_Reg<tUInt8> INST_sb_datav_1;
  MOD_Reg<tUInt8> INST_sb_datav_2;
  MOD_Reg<tUInt8> INST_sb_datav_3;
  MOD_Reg<tUInt8> INST_sb_deqoff;
  MOD_Wire<tUInt8> INST_sb_deqreq;
  MOD_Wire<tUInt8> INST_sb_enqdata;
  MOD_Reg<tUInt8> INST_sb_enqoff;
  MOD_Wire<tUInt8> INST_sb_enqreq;
 
 /* Constructor */
 public:
  MOD_mkProcessor(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_memReq;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_d2e_first__35_BIT_127_36_EQ_epoch_5___d537;
  tUInt8 DEF_d2e_first__35_BITS_126_TO_123___d540;
  tUInt8 DEF_d2e_first__35_BITS_159_TO_128_39_EQ_IF_d2e_fir_ETC___d583;
  tUInt8 DEF_NOT_sb_enqoff_5_ULE_sb_deqoff_72_73_AND_NOT_sb_ETC___d184;
  tUInt8 DEF_sb_enqoff_5_ULE_sb_deqoff___d172;
  tUInt8 DEF_NOT_sb_enqoff_5_ULE_sb_deqoff_72_73_AND_sb_enq_ETC___d177;
  tUInt8 DEF_sb_deqoff__h6881;
  tUInt8 DEF_IF_forwardE_whas__0_THEN_forwardE_wget__1_BITS_ETC___d213;
  tUInt8 DEF_IF_forwardE_whas__0_THEN_forwardE_wget__1_BITS_ETC___d255;
  tUInt8 DEF_dInst_src1__h6047;
  tUInt8 DEF_dInst_src2__h6048;
  tUInt8 DEF_mem_reqTargetIsIMemQ_first____d63;
  tUInt8 DEF_mem_dm_reqQ_notEmpty____d41;
  tUInt8 DEF_mem_im_reqQ_first__5_BIT_67___d36;
  tUInt8 DEF_idx__h9499;
  tUWide DEF_d2e_first____d535;
  tUWide DEF_e2m_first____d706;
  tUWide DEF_mem_dm_reqQ_first____d44;
  tUWide DEF_mem_im_reqQ_first____d35;
  tUInt64 DEF_forwardE_wget____d91;
  tUInt32 DEF_mem_im_respQ_first____d95;
  tUInt8 DEF__read__h829;
  tUInt8 DEF__read__h789;
  tUInt8 DEF__read__h749;
  tUInt8 DEF__read__h709;
  tUInt8 DEF_mem_im_reqQ_notEmpty____d32;
  tUInt8 DEF_forwardE_whas____d90;
  tUInt8 DEF_nextpcQ_notEmpty____d73;
  tUInt8 DEF_epoch__h5249;
  tUInt32 DEF_d2e_first__35_BITS_191_TO_160___d544;
  tUInt32 DEF_pc_predicted__h9696;
  tUInt32 DEF_imm__h9800;
  tUInt32 DEF_rVal1__h9698;
  tUInt32 DEF_rVal2__h9699;
  tUInt32 DEF_addr__h10041;
  tUInt8 DEF_funct7__h5430;
  tUInt8 DEF_opcode__h5428;
  tUInt8 DEF_x_wget_dst__h5399;
  tUInt8 DEF_src2__h5433;
  tUInt8 DEF_src1__h5432;
  tUInt8 DEF_d2e_first__35_BITS_118_TO_116___d547;
  tUInt8 DEF_funct3__h5429;
  tUInt8 DEF_x_BITS_1_TO_0___h9510;
  tUInt8 DEF_x__h9503;
  tUInt8 DEF_e2m_first__06_BIT_36___d707;
  tUInt8 DEF_mem_dm_reqQ_first__4_BIT_67___d45;
  tUInt8 DEF_d2e_first__35_BITS_126_TO_123_40_EQ_6___d586;
  tUInt8 DEF_d2e_first__35_BITS_126_TO_123_40_EQ_7___d588;
  tUInt8 DEF_IF_forwardE_whas__0_THEN_forwardE_wget__1_BITS_ETC___d94;
  tUInt32 DEF_nextPc__h9804;
  tUInt32 DEF_d2e_first__35_BITS_191_TO_160_44_PLUS_d2e_firs_ETC___d570;
  tUInt32 DEF_eInst_nextPC__h9819;
  tUInt32 DEF_nextPc__h9889;
  tUInt32 DEF_nextPc__h10025;
  tUInt8 DEF_IF_d2e_first__35_BITS_118_TO_116_47_EQ_0_48_TH_ETC___d568;
  tUInt8 DEF_d2e_first__35_BITS_63_TO_32_49_ULT_d2e_first___ETC___d557;
  tUInt8 DEF_d2e_first__35_BITS_63_TO_32_49_SLT_d2e_first___ETC___d555;
  tUInt8 DEF_mem_im_respQ_first__5_BITS_31_TO_25_8_EQ_0b0___d99;
  tUInt8 DEF_IF_mem_im_respQ_first__5_BITS_31_TO_25_8_EQ_0b_ETC___d223;
  tUInt8 DEF_IF_mem_im_respQ_first__5_BITS_31_TO_25_8_EQ_0b_ETC___d125;
  tUInt8 DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d137;
  tUInt8 DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d224;
  tUInt8 DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d143;
  tUInt8 DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d153;
  tUInt8 DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d228;
  tUInt8 DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d157;
  tUInt8 DEF_IF_mem_im_respQ_first__5_BITS_31_TO_25_8_EQ_0b_ETC___d134;
  tUInt8 DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d218;
  tUInt8 DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d117;
  tUInt8 DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d219;
  tUInt8 DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d120;
  tUInt8 DEF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0b0___d101;
  tUInt8 DEF_x__read_dst__h5403;
  tUInt8 DEF_p1__h9500;
  tUInt8 DEF_d2e_first__35_BITS_63_TO_32_49_EQ_d2e_first__3_ETC___d551;
  tUInt8 DEF_sb_datav_3_67_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d236;
  tUInt8 DEF_sb_datav_2_70_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d237;
  tUInt8 DEF_IF_sb_datav_1_78_EQ_IF_mem_im_respQ_first__5_B_ETC___d249;
  tUInt8 DEF_IF_sb_datav_1_78_EQ_IF_mem_im_respQ_first__5_B_ETC___d242;
  tUInt8 DEF_sb_datav_1_78_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d238;
  tUInt8 DEF_sb_datav_0_85_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d246;
  tUInt8 DEF_sb_datav_0_85_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d240;
  tUInt8 DEF_NOT_IF_mem_im_respQ_first__5_BITS_6_TO_0_6_EQ__ETC___d212;
  tUInt8 DEF_NOT_IF_forwardE_whas__0_THEN_forwardE_wget__1__ETC___d215;
  tUInt8 DEF_NOT_IF_mem_im_respQ_first__5_BITS_6_TO_0_6_EQ__ETC___d254;
  tUInt8 DEF_NOT_IF_forwardE_whas__0_THEN_forwardE_wget__1__ETC___d257;
  tUInt8 DEF_sb_datav_3_67_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d168;
  tUInt8 DEF_sb_datav_2_70_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d171;
  tUInt8 DEF_IF_sb_datav_1_78_EQ_IF_mem_im_respQ_first__5_B_ETC___d193;
  tUInt8 DEF_IF_sb_datav_1_78_EQ_IF_mem_im_respQ_first__5_B_ETC___d207;
  tUInt8 DEF_sb_datav_1_78_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d179;
  tUInt8 DEF_sb_datav_0_85_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d191;
  tUInt8 DEF_sb_datav_0_85_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d204;
  tUInt8 DEF_IF_mem_im_respQ_first__5_BITS_6_TO_0_6_EQ_0b11_ETC___d234;
  tUInt8 DEF_sb_datav_0_85_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d239;
  tUInt8 DEF_sb_datav_0_85_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d186;
  tUInt8 DEF_IF_mem_im_respQ_first__5_BITS_6_TO_0_6_EQ_0b11_ETC___d165;
  tUInt8 DEF_sb_deqoff_EQ_3___d175;
  tUInt8 DEF_sb_deqoff_EQ_0___d189;
  tUInt8 DEF_sb_enqoff_5_EQ_3___d30;
  tUInt8 DEF_sb_enqoff_5_EQ_0___d21;
  tUInt8 DEF_NOT_d2e_first__35_BIT_127_36_EQ_epoch_5_37___d538;
  tUInt8 DEF_NOT_d2e_first__35_BITS_126_TO_123_40_EQ_7_88___d589;
  tUInt8 DEF_sb_enqoff_5_ULT_sb_deqoff_69_AND_sb_enqoff_5_E_ETC___d198;
  tUInt8 DEF_sb_enqoff_5_ULT_sb_deqoff_69_AND_NOT_sb_enqoff_ETC___d200;
  tUInt8 DEF_sb_enqoff_5_ULT_sb_deqoff_69_AND_NOT_sb_enqoff_ETC___d203;
  tUInt8 DEF_NOT_sb_enqoff_5_ULE_sb_deqoff_72_73_AND_NOT_sb_ETC___d190;
  tUInt8 DEF_sb_enqoff_5_ULT_sb_deqoff___d169;
  tUInt8 DEF_NOT_sb_enqoff_5_EQ_0_1___d187;
  tUInt8 DEF_NOT_sb_enqoff_5_ULE_1_80___d181;
  tUInt8 DEF_sb_deqoff_ULE_1___d183;
  tUInt8 DEF_sb_enqoff_5_ULE_1___d180;
  tUInt8 DEF_NOT_sb_deqoff_EQ_3_75___d176;
  tUInt8 DEF_NOT_sb_enqoff_5_ULE_sb_deqoff_72___d173;
 
 /* Local definitions */
 private:
  tUWide DEF_f2d_first____d321;
  tUInt32 DEF_x__h9782;
  tUInt32 DEF_x__h170;
  tUWide DEF_IF_d2e_first__35_BIT_115_03_THEN_d2e_first__35_ETC___d674;
  tUWide DEF_d2e_first__35_BITS_191_TO_160_44_CONCAT_d2e_fi_ETC___d673;
  tUWide DEF_d2e_first__35_BITS_191_TO_160_44_CONCAT_0_CONC_ETC___d602;
  tUWide DEF_IF_d2e_first__35_BITS_126_TO_123_40_EQ_6_86_TH_ETC___d676;
  tUWide DEF_d2e_first__35_BITS_191_TO_160_44_CONCAT_d2e_fi_ETC___d601;
  tUWide DEF_IF_d2e_first__35_BIT_127_36_EQ_epoch_5_37_THEN_ETC___d677;
  tUWide DEF_IF_mem_im_reqQ_notEmpty__2_THEN_mem_im_reqQ_fi_ETC___d52;
  tUWide DEF_f2d_first__21_CONCAT_IF_mem_im_respQ_first__5__ETC___d528;
  tUWide DEF__0_CONCAT_IF_nextpcQ_notEmpty__3_THEN_nextpcQ_f_ETC___d84;
  tUWide DEF_NOT_d2e_first__35_BITS_126_TO_123_40_EQ_6_86_8_ETC___d696;
  tUWide DEF_IF_nextpcQ_notEmpty__3_THEN_nextpcQ_first__9_E_ETC___d86;
  tUWide DEF_memReq__avValue1;
 
 /* Rules */
 public:
  void RL_incCycle();
  void RL_sb_normalize();
  void RL_mem_relayReq();
  void RL_mem_relayResp();
  void RL_doFetch();
  void RL_doDecode();
  void RL_doExecute();
  void RL_doWriteback();
 
 /* Methods */
 public:
  tUWide METH_memReq();
  tUInt8 METH_RDY_memReq();
  void METH_memResp(tUInt32 ARG_memResp_data);
  tUInt8 METH_RDY_memResp();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkProcessor &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkProcessor &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkProcessor &backing);
};

#endif /* ifndef __mkProcessor_h__ */
