/*
 * Generated by Bluespec Compiler, version 2014.07.A (build 34078, 2014-07-30)
 * 
 * On Tue May 19 15:33:31 PDT 2020
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkBsvTop_bsim.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkBsvTop_bsim::MODEL_mkBsvTop_bsim()
{
  mkBsvTop_bsim_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkBsvTop_bsim()
{
  MODEL_mkBsvTop_bsim *model = new MODEL_mkBsvTop_bsim();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkBsvTop_bsim &INST_top = *((MOD_mkBsvTop_bsim *)(instance_ptr));
	 tUInt8 DEF_INST_top_INST_hwmain_proc_DEF_mem_dm_reqQ_i_notFull____d587;
	 tUInt8 DEF_INST_top_INST_hwmain_proc_DEF_mem_reqQ_i_notFull____d34;
	 tUInt8 DEF_INST_top_INST_hwmain_proc_DEF_mem_reqTargetIsIMemQ_i_notFull____d37;
	 tUInt8 DEF_INST_top_INST_hwmain_proc_DEF_CAN_FIRE_RL_incCycle;
	 tUInt8 DEF_INST_top_INST_hwmain_proc_DEF_WILL_FIRE_RL_incCycle;
	 tUInt8 DEF_INST_top_INST_hwmain_proc_DEF_CAN_FIRE_RL_sb_normalize;
	 tUInt8 DEF_INST_top_INST_hwmain_proc_DEF_WILL_FIRE_RL_sb_normalize;
	 tUInt8 DEF_INST_top_INST_hwmain_proc_DEF_CAN_FIRE_RL_mem_relayReq;
	 tUInt8 DEF_INST_top_INST_hwmain_proc_DEF_WILL_FIRE_RL_mem_relayReq;
	 tUInt8 DEF_INST_top_INST_hwmain_proc_DEF_CAN_FIRE_RL_mem_relayResp;
	 tUInt8 DEF_INST_top_INST_hwmain_proc_DEF_WILL_FIRE_RL_mem_relayResp;
	 tUInt8 DEF_INST_top_INST_hwmain_proc_DEF_CAN_FIRE_RL_doFetch;
	 tUInt8 DEF_INST_top_INST_hwmain_proc_DEF_WILL_FIRE_RL_doFetch;
	 tUInt8 DEF_INST_top_INST_hwmain_proc_DEF_CAN_FIRE_RL_doDecode;
	 tUInt8 DEF_INST_top_INST_hwmain_proc_DEF_WILL_FIRE_RL_doDecode;
	 tUInt8 DEF_INST_top_INST_hwmain_proc_DEF_CAN_FIRE_RL_doExecute;
	 tUInt8 DEF_INST_top_INST_hwmain_proc_DEF_WILL_FIRE_RL_doExecute;
	 tUInt8 DEF_INST_top_INST_hwmain_proc_DEF_CAN_FIRE_RL_doWriteback;
	 tUInt8 DEF_INST_top_INST_hwmain_proc_DEF_WILL_FIRE_RL_doWriteback;
	 tUInt8 DEF_INST_top_DEF_hwmain_mem_serverAdapterA_s1_2_BIT_1___d67;
	 tUInt8 DEF_INST_top_DEF_hwmain_mem_serverAdapterB_s1_21_BIT_1___d126;
	 tUInt8 DEF_INST_top_DEF_initialized__h4069;
	 tUInt8 DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outDataCore_notEmpty____d14;
	 tUInt8 DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outDataCore_notFull____d65;
	 tUInt8 DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outDataCore_i_notFull____d21;
	 tUInt8 DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outDataCore_i_notEmpty____d13;
	 tUInt8 DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outData_enqData_whas____d18;
	 tUInt8 DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outData_deqCalled_whas____d22;
	 tUInt8 DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outDataCore_notEmpty____d73;
	 tUInt8 DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outDataCore_notFull____d124;
	 tUInt8 DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outDataCore_i_notFull____d80;
	 tUInt8 DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outDataCore_i_notEmpty____d72;
	 tUInt8 DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outData_enqData_whas____d77;
	 tUInt8 DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outData_deqCalled_whas____d81;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_uart_relayOut;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_uart_relayOut;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_uart_relayIn;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_uart_relayIn;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_outData_setFirstCore;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_outData_setFirstCore;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_outData_setFirstEnq;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_outData_setFirstEnq;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_outData_enqOnly;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_outData_enqOnly;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_outData_deqOnly;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_outData_deqOnly;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_outData_enqAndDeq;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_outData_enqAndDeq;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_cnt_finalAdd;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_cnt_finalAdd;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_s1__dreg_update;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_s1__dreg_update;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_stageReadResponseAlways;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_stageReadResponseAlways;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_moveToOutFIFO;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_moveToOutFIFO;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_overRun;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_overRun;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_outData_setFirstCore;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_outData_setFirstCore;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_outData_setFirstEnq;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_outData_setFirstEnq;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_outData_enqOnly;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_outData_enqOnly;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_outData_deqOnly;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_outData_deqOnly;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_outData_enqAndDeq;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_outData_enqAndDeq;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_cnt_finalAdd;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_cnt_finalAdd;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_s1__dreg_update;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_s1__dreg_update;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_stageReadResponseAlways;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_stageReadResponseAlways;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_moveToOutFIFO;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_moveToOutFIFO;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_overRun;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_overRun;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_rpReq;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_rpReq;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_rpResp;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_rpResp;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_doinit;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_doinit;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_relayUartIn;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_relayUartIn;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_relayUartOut;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_relayUartOut;
	 DEF_INST_top_DEF_initialized__h4069 = INST_top.INST_initialized.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_doinit = !DEF_INST_top_DEF_initialized__h4069;
	 DEF_INST_top_DEF_WILL_FIRE_RL_doinit = DEF_INST_top_DEF_CAN_FIRE_RL_doinit;
	 INST_top.DEF_hwmain_mem_serverAdapterA_s1___d62 = INST_top.INST_hwmain_mem_serverAdapterA_s1.METH_read();
	 DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outDataCore_notFull____d65 = INST_top.INST_hwmain_mem_serverAdapterA_outDataCore.METH_notFull();
	 DEF_INST_top_DEF_hwmain_mem_serverAdapterA_s1_2_BIT_1___d67 = (tUInt8)((INST_top.DEF_hwmain_mem_serverAdapterA_s1___d62) >> 1u);
	 INST_top.DEF_hwmain_mem_serverAdapterA_s1_2_BIT_0___d63 = (tUInt8)((tUInt8)1u & (INST_top.DEF_hwmain_mem_serverAdapterA_s1___d62));
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_moveToOutFIFO = (!(INST_top.DEF_hwmain_mem_serverAdapterA_s1_2_BIT_0___d63) || DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outDataCore_notFull____d65) && DEF_INST_top_DEF_hwmain_mem_serverAdapterA_s1_2_BIT_1___d67;
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_moveToOutFIFO = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_moveToOutFIFO;
	 DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outDataCore_i_notEmpty____d13 = INST_top.INST_hwmain_mem_serverAdapterA_outDataCore.METH_i_notEmpty();
	 DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outDataCore_notEmpty____d14 = INST_top.INST_hwmain_mem_serverAdapterA_outDataCore.METH_notEmpty();
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_outData_setFirstCore = DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outDataCore_i_notEmpty____d13 && DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outDataCore_notEmpty____d14;
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_outData_setFirstCore = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_outData_setFirstCore;
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_overRun = DEF_INST_top_DEF_hwmain_mem_serverAdapterA_s1_2_BIT_1___d67 && !DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outDataCore_notFull____d65;
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_overRun = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_overRun;
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_s1__dreg_update = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_s1__dreg_update = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_s1__dreg_update;
	 INST_top.DEF_hwmain_mem_serverAdapterB_s1___d121 = INST_top.INST_hwmain_mem_serverAdapterB_s1.METH_read();
	 DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outDataCore_notFull____d124 = INST_top.INST_hwmain_mem_serverAdapterB_outDataCore.METH_notFull();
	 DEF_INST_top_DEF_hwmain_mem_serverAdapterB_s1_21_BIT_1___d126 = (tUInt8)((INST_top.DEF_hwmain_mem_serverAdapterB_s1___d121) >> 1u);
	 INST_top.DEF_hwmain_mem_serverAdapterB_s1_21_BIT_0___d122 = (tUInt8)((tUInt8)1u & (INST_top.DEF_hwmain_mem_serverAdapterB_s1___d121));
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_moveToOutFIFO = (!(INST_top.DEF_hwmain_mem_serverAdapterB_s1_21_BIT_0___d122) || DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outDataCore_notFull____d124) && DEF_INST_top_DEF_hwmain_mem_serverAdapterB_s1_21_BIT_1___d126;
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_moveToOutFIFO = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_moveToOutFIFO;
	 DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outDataCore_i_notEmpty____d72 = INST_top.INST_hwmain_mem_serverAdapterB_outDataCore.METH_i_notEmpty();
	 DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outDataCore_notEmpty____d73 = INST_top.INST_hwmain_mem_serverAdapterB_outDataCore.METH_notEmpty();
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_outData_setFirstCore = DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outDataCore_i_notEmpty____d72 && DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outDataCore_notEmpty____d73;
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_outData_setFirstCore = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_outData_setFirstCore;
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_overRun = DEF_INST_top_DEF_hwmain_mem_serverAdapterB_s1_21_BIT_1___d126 && !DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outDataCore_notFull____d124;
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_overRun = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_overRun;
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_s1__dreg_update = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_s1__dreg_update = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_s1__dreg_update;
	 INST_top.DEF_b__h1484 = INST_top.INST_hwmain_mem_serverAdapterA_cnt.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_rpReq = INST_top.INST_hwmain_proc.METH_RDY_memReq() && primSLT8(1u,
													     3u,
													     (tUInt8)(INST_top.DEF_b__h1484),
													     3u,
													     (tUInt8)3u);
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_rpReq = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_rpReq;
	 INST_top.DEF_b__h2891 = INST_top.INST_hwmain_mem_serverAdapterB_cnt.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_relayUartIn = INST_top.INST_uart_outQ.METH_i_notEmpty() && (INST_top.INST_hwmain_relayUart.METH_i_notFull() && primSLT8(1u,
																			      3u,
																			      (tUInt8)(INST_top.DEF_b__h2891),
																			      3u,
																			      (tUInt8)3u));
	 DEF_INST_top_DEF_WILL_FIRE_RL_relayUartIn = DEF_INST_top_DEF_CAN_FIRE_RL_relayUartIn;
	 DEF_INST_top_DEF_CAN_FIRE_RL_uart_relayIn = INST_top.INST_uart_inQ.METH_i_notEmpty();
	 DEF_INST_top_DEF_WILL_FIRE_RL_uart_relayIn = DEF_INST_top_DEF_CAN_FIRE_RL_uart_relayIn;
	 DEF_INST_top_DEF_CAN_FIRE_RL_relayUartOut = INST_top.INST_hwmain_relayUart.METH_i_notEmpty() && INST_top.INST_uart_inQ.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_relayUartOut = DEF_INST_top_DEF_CAN_FIRE_RL_relayUartOut;
	 DEF_INST_top_DEF_CAN_FIRE_RL_uart_relayOut = INST_top.INST_uart_outQ.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_uart_relayOut = DEF_INST_top_DEF_CAN_FIRE_RL_uart_relayOut;
	 INST_top.INST_hwmain_proc.DEF_d2e_first____d535 = INST_top.INST_hwmain_proc.INST_d2e.METH_first();
	 INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_126_TO_123___d540 = INST_top.INST_hwmain_proc.DEF_d2e_first____d535.get_bits_in_word8(3u,
																		27u,
																		4u);
	 DEF_INST_top_INST_hwmain_proc_DEF_mem_dm_reqQ_i_notFull____d587 = INST_top.INST_hwmain_proc.INST_mem_dm_reqQ.METH_i_notFull();
	 INST_top.INST_hwmain_proc.DEF_epoch__h5249 = INST_top.INST_hwmain_proc.INST_epoch.METH_read();
	 INST_top.INST_hwmain_proc.DEF_d2e_first__35_BIT_127_36_EQ_epoch_5___d537 = INST_top.INST_hwmain_proc.DEF_d2e_first____d535.get_bits_in_word8(3u,
																		      31u,
																		      1u) == (INST_top.INST_hwmain_proc.DEF_epoch__h5249);
	 INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_191_TO_160___d544 = INST_top.INST_hwmain_proc.DEF_d2e_first____d535.get_whole_word(5u);
	 INST_top.INST_hwmain_proc.DEF_rVal1__h9698 = INST_top.INST_hwmain_proc.DEF_d2e_first____d535.get_whole_word(1u);
	 INST_top.INST_hwmain_proc.DEF_pc_predicted__h9696 = INST_top.INST_hwmain_proc.DEF_d2e_first____d535.get_whole_word(4u);
	 INST_top.INST_hwmain_proc.DEF_imm__h9800 = primExtract32(32u,
								  192u,
								  INST_top.INST_hwmain_proc.DEF_d2e_first____d535,
								  32u,
								  99u,
								  32u,
								  68u);
	 INST_top.INST_hwmain_proc.DEF_rVal2__h9699 = INST_top.INST_hwmain_proc.DEF_d2e_first____d535.get_whole_word(0u);
	 INST_top.INST_hwmain_proc.DEF_addr__h10041 = (INST_top.INST_hwmain_proc.DEF_rVal1__h9698) + (INST_top.INST_hwmain_proc.DEF_imm__h9800);
	 INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_118_TO_116___d547 = INST_top.INST_hwmain_proc.DEF_d2e_first____d535.get_bits_in_word8(3u,
																		20u,
																		3u);
	 INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_126_TO_123_40_EQ_6___d586 = (INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_126_TO_123___d540) == (tUInt8)6u;
	 INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_126_TO_123_40_EQ_7___d588 = (INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_126_TO_123___d540) == (tUInt8)7u;
	 INST_top.INST_hwmain_proc.DEF_nextPc__h9804 = (INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_191_TO_160___d544) + 4u;
	 INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_191_TO_160_44_PLUS_d2e_firs_ETC___d570 = (INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_191_TO_160___d544) + (INST_top.INST_hwmain_proc.DEF_imm__h9800);
	 INST_top.INST_hwmain_proc.DEF_nextPc__h10025 = (((tUInt32)((INST_top.INST_hwmain_proc.DEF_addr__h10041) >> 1u)) << 1u) | (tUInt32)((tUInt8)0u);
	 INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_63_TO_32_49_ULT_d2e_first___ETC___d557 = (INST_top.INST_hwmain_proc.DEF_rVal1__h9698) < (INST_top.INST_hwmain_proc.DEF_rVal2__h9699);
	 INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_63_TO_32_49_SLT_d2e_first___ETC___d555 = primSLT8(1u,
													    32u,
													    (tUInt32)(INST_top.INST_hwmain_proc.DEF_rVal1__h9698),
													    32u,
													    (tUInt32)(INST_top.INST_hwmain_proc.DEF_rVal2__h9699));
	 INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_63_TO_32_49_EQ_d2e_first__3_ETC___d551 = (INST_top.INST_hwmain_proc.DEF_rVal1__h9698) == (INST_top.INST_hwmain_proc.DEF_rVal2__h9699);
	 switch (INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_118_TO_116___d547) {
	 case (tUInt8)0u:
	   INST_top.INST_hwmain_proc.DEF_IF_d2e_first__35_BITS_118_TO_116_47_EQ_0_48_TH_ETC___d568 = INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_63_TO_32_49_EQ_d2e_first__3_ETC___d551;
	   break;
	 case (tUInt8)1u:
	   INST_top.INST_hwmain_proc.DEF_IF_d2e_first__35_BITS_118_TO_116_47_EQ_0_48_TH_ETC___d568 = !(INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_63_TO_32_49_EQ_d2e_first__3_ETC___d551);
	   break;
	 case (tUInt8)2u:
	   INST_top.INST_hwmain_proc.DEF_IF_d2e_first__35_BITS_118_TO_116_47_EQ_0_48_TH_ETC___d568 = INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_63_TO_32_49_SLT_d2e_first___ETC___d555;
	   break;
	 case (tUInt8)3u:
	   INST_top.INST_hwmain_proc.DEF_IF_d2e_first__35_BITS_118_TO_116_47_EQ_0_48_TH_ETC___d568 = INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_63_TO_32_49_ULT_d2e_first___ETC___d557;
	   break;
	 case (tUInt8)4u:
	   INST_top.INST_hwmain_proc.DEF_IF_d2e_first__35_BITS_118_TO_116_47_EQ_0_48_TH_ETC___d568 = !(INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_63_TO_32_49_SLT_d2e_first___ETC___d555);
	   break;
	 case (tUInt8)5u:
	   INST_top.INST_hwmain_proc.DEF_IF_d2e_first__35_BITS_118_TO_116_47_EQ_0_48_TH_ETC___d568 = !(INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_63_TO_32_49_ULT_d2e_first___ETC___d557);
	   break;
	 default:
	   INST_top.INST_hwmain_proc.DEF_IF_d2e_first__35_BITS_118_TO_116_47_EQ_0_48_TH_ETC___d568 = (INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_118_TO_116___d547) == (tUInt8)6u;
	 }
	 INST_top.INST_hwmain_proc.DEF_nextPc__h9889 = INST_top.INST_hwmain_proc.DEF_IF_d2e_first__35_BITS_118_TO_116_47_EQ_0_48_TH_ETC___d568 ? INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_191_TO_160_44_PLUS_d2e_firs_ETC___d570 : INST_top.INST_hwmain_proc.DEF_nextPc__h9804;
	 switch (INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_126_TO_123___d540) {
	 case (tUInt8)2u:
	   INST_top.INST_hwmain_proc.DEF_eInst_nextPC__h9819 = INST_top.INST_hwmain_proc.DEF_nextPc__h9889;
	   break;
	 case (tUInt8)4u:
	   INST_top.INST_hwmain_proc.DEF_eInst_nextPC__h9819 = INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_191_TO_160_44_PLUS_d2e_firs_ETC___d570;
	   break;
	 case (tUInt8)5u:
	   INST_top.INST_hwmain_proc.DEF_eInst_nextPC__h9819 = INST_top.INST_hwmain_proc.DEF_nextPc__h10025;
	   break;
	 default:
	   INST_top.INST_hwmain_proc.DEF_eInst_nextPC__h9819 = INST_top.INST_hwmain_proc.DEF_nextPc__h9804;
	 }
	 INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_159_TO_128_39_EQ_IF_d2e_fir_ETC___d583 = (INST_top.INST_hwmain_proc.DEF_pc_predicted__h9696) == (INST_top.INST_hwmain_proc.DEF_eInst_nextPC__h9819);
	 INST_top.INST_hwmain_proc.DEF_NOT_d2e_first__35_BITS_126_TO_123_40_EQ_7_88___d589 = !(INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_126_TO_123_40_EQ_7___d588);
	 INST_top.INST_hwmain_proc.DEF_NOT_d2e_first__35_BIT_127_36_EQ_epoch_5_37___d538 = !(INST_top.INST_hwmain_proc.DEF_d2e_first__35_BIT_127_36_EQ_epoch_5___d537);
	 DEF_INST_top_INST_hwmain_proc_DEF_CAN_FIRE_RL_doExecute = INST_top.INST_hwmain_proc.INST_d2e.METH_i_notEmpty() && (INST_top.INST_hwmain_proc.INST_e2m.METH_i_notFull() && (INST_top.INST_hwmain_proc.DEF_NOT_d2e_first__35_BIT_127_36_EQ_epoch_5_37___d538 || ((INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_159_TO_128_39_EQ_IF_d2e_fir_ETC___d583 || INST_top.INST_hwmain_proc.INST_nextpcQ.METH_i_notFull()) && (INST_top.INST_hwmain_proc.DEF_d2e_first__35_BITS_126_TO_123_40_EQ_6___d586 ? DEF_INST_top_INST_hwmain_proc_DEF_mem_dm_reqQ_i_notFull____d587 : INST_top.INST_hwmain_proc.DEF_NOT_d2e_first__35_BITS_126_TO_123_40_EQ_7_88___d589 || DEF_INST_top_INST_hwmain_proc_DEF_mem_dm_reqQ_i_notFull____d587))));
	 DEF_INST_top_INST_hwmain_proc_DEF_WILL_FIRE_RL_doExecute = DEF_INST_top_INST_hwmain_proc_DEF_CAN_FIRE_RL_doExecute;
	 DEF_INST_top_INST_hwmain_proc_DEF_CAN_FIRE_RL_incCycle = (tUInt8)1u;
	 DEF_INST_top_INST_hwmain_proc_DEF_WILL_FIRE_RL_incCycle = DEF_INST_top_INST_hwmain_proc_DEF_CAN_FIRE_RL_incCycle;
	 INST_top.INST_hwmain_proc.DEF_nextpcQ_notEmpty____d73 = INST_top.INST_hwmain_proc.INST_nextpcQ.METH_notEmpty();
	 DEF_INST_top_INST_hwmain_proc_DEF_CAN_FIRE_RL_doFetch = INST_top.INST_hwmain_proc.INST_mem_im_reqQ.METH_i_notFull() && (INST_top.INST_hwmain_proc.INST_f2d.METH_i_notFull() && (!(INST_top.INST_hwmain_proc.DEF_nextpcQ_notEmpty____d73) || INST_top.INST_hwmain_proc.INST_nextpcQ.METH_i_notEmpty()));
	 DEF_INST_top_INST_hwmain_proc_DEF_WILL_FIRE_RL_doFetch = DEF_INST_top_INST_hwmain_proc_DEF_CAN_FIRE_RL_doFetch;
	 INST_top.INST_hwmain_proc.DEF_sb_deqoff__h6881 = INST_top.INST_hwmain_proc.INST_sb_deqoff.METH_read();
	 INST_top.INST_hwmain_proc.DEF_idx__h9499 = INST_top.INST_hwmain_proc.INST_sb_enqoff.METH_read();
	 INST_top.INST_hwmain_proc.DEF_e2m_first____d706 = INST_top.INST_hwmain_proc.INST_e2m.METH_first();
	 INST_top.INST_hwmain_proc.DEF_e2m_first__06_BIT_36___d707 = INST_top.INST_hwmain_proc.DEF_e2m_first____d706.get_bits_in_word8(1u,
																       4u,
																       1u);
	 DEF_INST_top_INST_hwmain_proc_DEF_CAN_FIRE_RL_doWriteback = !((INST_top.INST_hwmain_proc.DEF_sb_deqoff__h6881) == (INST_top.INST_hwmain_proc.DEF_idx__h9499)) && (INST_top.INST_hwmain_proc.INST_e2m.METH_i_notEmpty() && (!(INST_top.INST_hwmain_proc.DEF_e2m_first__06_BIT_36___d707) || INST_top.INST_hwmain_proc.INST_mem_dm_respQ.METH_i_notEmpty()));
	 DEF_INST_top_INST_hwmain_proc_DEF_WILL_FIRE_RL_doWriteback = DEF_INST_top_INST_hwmain_proc_DEF_CAN_FIRE_RL_doWriteback;
	 INST_top.INST_hwmain_proc.DEF_mem_dm_reqQ_notEmpty____d41 = INST_top.INST_hwmain_proc.INST_mem_dm_reqQ.METH_notEmpty();
	 INST_top.INST_hwmain_proc.DEF_mem_dm_reqQ_first____d44 = INST_top.INST_hwmain_proc.INST_mem_dm_reqQ.METH_first();
	 INST_top.INST_hwmain_proc.DEF_mem_im_reqQ_first____d35 = INST_top.INST_hwmain_proc.INST_mem_im_reqQ.METH_first();
	 INST_top.INST_hwmain_proc.DEF_mem_im_reqQ_first__5_BIT_67___d36 = INST_top.INST_hwmain_proc.DEF_mem_im_reqQ_first____d35.get_bits_in_word8(2u,
																		    3u,
																		    1u);
	 DEF_INST_top_INST_hwmain_proc_DEF_mem_reqTargetIsIMemQ_i_notFull____d37 = INST_top.INST_hwmain_proc.INST_mem_reqTargetIsIMemQ.METH_i_notFull();
	 INST_top.INST_hwmain_proc.DEF_mem_im_reqQ_notEmpty____d32 = INST_top.INST_hwmain_proc.INST_mem_im_reqQ.METH_notEmpty();
	 DEF_INST_top_INST_hwmain_proc_DEF_mem_reqQ_i_notFull____d34 = INST_top.INST_hwmain_proc.INST_mem_reqQ.METH_i_notFull();
	 INST_top.INST_hwmain_proc.DEF_mem_dm_reqQ_first__4_BIT_67___d45 = INST_top.INST_hwmain_proc.DEF_mem_dm_reqQ_first____d44.get_bits_in_word8(2u,
																		    3u,
																		    1u);
	 DEF_INST_top_INST_hwmain_proc_DEF_CAN_FIRE_RL_mem_relayReq = INST_top.INST_hwmain_proc.DEF_mem_im_reqQ_notEmpty____d32 ? INST_top.INST_hwmain_proc.INST_mem_im_reqQ.METH_i_notEmpty() && (DEF_INST_top_INST_hwmain_proc_DEF_mem_reqQ_i_notFull____d34 && (INST_top.INST_hwmain_proc.DEF_mem_im_reqQ_first__5_BIT_67___d36 || DEF_INST_top_INST_hwmain_proc_DEF_mem_reqTargetIsIMemQ_i_notFull____d37)) : !(INST_top.INST_hwmain_proc.DEF_mem_dm_reqQ_notEmpty____d41) || (INST_top.INST_hwmain_proc.INST_mem_dm_reqQ.METH_i_notEmpty() && (DEF_INST_top_INST_hwmain_proc_DEF_mem_reqQ_i_notFull____d34 && (INST_top.INST_hwmain_proc.DEF_mem_dm_reqQ_first__4_BIT_67___d45 || DEF_INST_top_INST_hwmain_proc_DEF_mem_reqTargetIsIMemQ_i_notFull____d37)));
	 DEF_INST_top_INST_hwmain_proc_DEF_WILL_FIRE_RL_mem_relayReq = DEF_INST_top_INST_hwmain_proc_DEF_CAN_FIRE_RL_mem_relayReq;
	 INST_top.INST_hwmain_proc.DEF_mem_reqTargetIsIMemQ_first____d63 = INST_top.INST_hwmain_proc.INST_mem_reqTargetIsIMemQ.METH_first();
	 DEF_INST_top_INST_hwmain_proc_DEF_CAN_FIRE_RL_mem_relayResp = INST_top.INST_hwmain_proc.INST_mem_reqTargetIsIMemQ.METH_i_notEmpty() && (INST_top.INST_hwmain_proc.INST_mem_respQ.METH_i_notEmpty() && (INST_top.INST_hwmain_proc.DEF_mem_reqTargetIsIMemQ_first____d63 ? INST_top.INST_hwmain_proc.INST_mem_im_respQ.METH_i_notFull() : INST_top.INST_hwmain_proc.INST_mem_dm_respQ.METH_i_notFull()));
	 DEF_INST_top_INST_hwmain_proc_DEF_WILL_FIRE_RL_mem_relayResp = DEF_INST_top_INST_hwmain_proc_DEF_CAN_FIRE_RL_mem_relayResp;
	 DEF_INST_top_INST_hwmain_proc_DEF_CAN_FIRE_RL_sb_normalize = (tUInt8)1u;
	 DEF_INST_top_INST_hwmain_proc_DEF_WILL_FIRE_RL_sb_normalize = DEF_INST_top_INST_hwmain_proc_DEF_CAN_FIRE_RL_sb_normalize;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_doinit)
	   INST_top.RL_doinit();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_moveToOutFIFO)
	   INST_top.RL_hwmain_mem_serverAdapterA_moveToOutFIFO();
	 DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outData_enqData_whas____d18 = INST_top.INST_hwmain_mem_serverAdapterA_outData_enqData.METH_whas();
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_outData_setFirstEnq = !DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outDataCore_notEmpty____d14 && DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outData_enqData_whas____d18;
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_outData_setFirstEnq = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_outData_setFirstEnq;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_outData_setFirstCore)
	   INST_top.RL_hwmain_mem_serverAdapterA_outData_setFirstCore();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_outData_setFirstEnq)
	   INST_top.RL_hwmain_mem_serverAdapterA_outData_setFirstEnq();
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_rpResp = INST_top.INST_hwmain_proc.METH_RDY_memResp() && ((DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outDataCore_notEmpty____d14 || DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outData_enqData_whas____d18) && INST_top.INST_hwmain_mem_serverAdapterA_outData_outData.METH_whas());
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_rpResp = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_rpResp;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_moveToOutFIFO)
	   INST_top.RL_hwmain_mem_serverAdapterB_moveToOutFIFO();
	 DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outData_deqCalled_whas____d81 = INST_top.INST_hwmain_mem_serverAdapterB_outData_deqCalled.METH_whas();
	 DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outData_enqData_whas____d77 = INST_top.INST_hwmain_mem_serverAdapterB_outData_enqData.METH_whas();
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_outData_deqOnly = DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outDataCore_i_notEmpty____d72 && (DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outData_deqCalled_whas____d81 && !DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outData_enqData_whas____d77);
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_outData_deqOnly = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_outData_deqOnly;
	 DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outDataCore_i_notFull____d80 = INST_top.INST_hwmain_mem_serverAdapterB_outDataCore.METH_i_notFull();
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_outData_enqAndDeq = (DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outDataCore_i_notEmpty____d72 && DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outDataCore_i_notFull____d80) && (DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outData_deqCalled_whas____d81 && DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outData_enqData_whas____d77);
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_outData_enqAndDeq = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_outData_enqAndDeq;
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_outData_enqOnly = DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outDataCore_i_notFull____d80 && (!DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outData_deqCalled_whas____d81 && DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outData_enqData_whas____d77);
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_outData_enqOnly = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_outData_enqOnly;
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_outData_setFirstEnq = !DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outDataCore_notEmpty____d73 && DEF_INST_top_DEF_hwmain_mem_serverAdapterB_outData_enqData_whas____d77;
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_outData_setFirstEnq = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_outData_setFirstEnq;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_outData_setFirstCore)
	   INST_top.RL_hwmain_mem_serverAdapterB_outData_setFirstCore();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_outData_enqAndDeq)
	   INST_top.RL_hwmain_mem_serverAdapterB_outData_enqAndDeq();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_outData_setFirstEnq)
	   INST_top.RL_hwmain_mem_serverAdapterB_outData_setFirstEnq();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_outData_enqOnly)
	   INST_top.RL_hwmain_mem_serverAdapterB_outData_enqOnly();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_rpReq)
	   INST_top.RL_hwmain_rpReq();
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_stageReadResponseAlways = INST_top.INST_hwmain_mem_serverAdapterA_writeWithResp.METH_whas();
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_stageReadResponseAlways = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_stageReadResponseAlways;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_stageReadResponseAlways)
	   INST_top.RL_hwmain_mem_serverAdapterA_stageReadResponseAlways();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_rpResp)
	   INST_top.RL_hwmain_rpResp();
	 INST_top.DEF_hwmain_mem_serverAdapterA_cnt_3_whas____d35 = INST_top.INST_hwmain_mem_serverAdapterA_cnt_3.METH_whas();
	 INST_top.DEF_hwmain_mem_serverAdapterA_cnt_2_whas____d33 = INST_top.INST_hwmain_mem_serverAdapterA_cnt_2.METH_whas();
	 INST_top.DEF_hwmain_mem_serverAdapterA_cnt_1_whas____d32 = INST_top.INST_hwmain_mem_serverAdapterA_cnt_1.METH_whas();
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_cnt_finalAdd = (INST_top.DEF_hwmain_mem_serverAdapterA_cnt_1_whas____d32 || INST_top.DEF_hwmain_mem_serverAdapterA_cnt_2_whas____d33) || INST_top.DEF_hwmain_mem_serverAdapterA_cnt_3_whas____d35;
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_cnt_finalAdd = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_cnt_finalAdd;
	 DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outData_deqCalled_whas____d22 = INST_top.INST_hwmain_mem_serverAdapterA_outData_deqCalled.METH_whas();
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_outData_deqOnly = (DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outDataCore_i_notEmpty____d13 && (DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outData_deqCalled_whas____d22 && !DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outData_enqData_whas____d18)) && !DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_outData_setFirstEnq;
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_outData_deqOnly = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_outData_deqOnly;
	 DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outDataCore_i_notFull____d21 = INST_top.INST_hwmain_mem_serverAdapterA_outDataCore.METH_i_notFull();
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_outData_enqAndDeq = ((DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outDataCore_i_notEmpty____d13 && DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outDataCore_i_notFull____d21) && (DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outData_deqCalled_whas____d22 && DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outData_enqData_whas____d18)) && !DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_outData_setFirstEnq;
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_outData_enqAndDeq = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_outData_enqAndDeq;
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_outData_enqOnly = DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outDataCore_i_notFull____d21 && (!DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outData_deqCalled_whas____d22 && DEF_INST_top_DEF_hwmain_mem_serverAdapterA_outData_enqData_whas____d18);
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_outData_enqOnly = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterA_outData_enqOnly;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_cnt_finalAdd)
	   INST_top.RL_hwmain_mem_serverAdapterA_cnt_finalAdd();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_outData_enqAndDeq)
	   INST_top.RL_hwmain_mem_serverAdapterA_outData_enqAndDeq();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_outData_enqOnly)
	   INST_top.RL_hwmain_mem_serverAdapterA_outData_enqOnly();
	 if (DEF_INST_top_INST_hwmain_proc_DEF_WILL_FIRE_RL_mem_relayReq)
	   INST_top.INST_hwmain_proc.RL_mem_relayReq();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_relayUartIn)
	   INST_top.RL_relayUartIn();
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_stageReadResponseAlways = INST_top.INST_hwmain_mem_serverAdapterB_writeWithResp.METH_whas();
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_stageReadResponseAlways = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_stageReadResponseAlways;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_stageReadResponseAlways)
	   INST_top.RL_hwmain_mem_serverAdapterB_stageReadResponseAlways();
	 INST_top.DEF_hwmain_mem_serverAdapterB_cnt_3_whas____d94 = INST_top.INST_hwmain_mem_serverAdapterB_cnt_3.METH_whas();
	 INST_top.DEF_hwmain_mem_serverAdapterB_cnt_2_whas____d92 = INST_top.INST_hwmain_mem_serverAdapterB_cnt_2.METH_whas();
	 INST_top.DEF_hwmain_mem_serverAdapterB_cnt_1_whas____d91 = INST_top.INST_hwmain_mem_serverAdapterB_cnt_1.METH_whas();
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_cnt_finalAdd = (INST_top.DEF_hwmain_mem_serverAdapterB_cnt_1_whas____d91 || INST_top.DEF_hwmain_mem_serverAdapterB_cnt_2_whas____d92) || INST_top.DEF_hwmain_mem_serverAdapterB_cnt_3_whas____d94;
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_cnt_finalAdd = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_mem_serverAdapterB_cnt_finalAdd;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_cnt_finalAdd)
	   INST_top.RL_hwmain_mem_serverAdapterB_cnt_finalAdd();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_relayUartOut)
	   INST_top.RL_relayUartOut();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_uart_relayOut)
	   INST_top.RL_uart_relayOut();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_uart_relayIn)
	   INST_top.RL_uart_relayIn();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_overRun)
	   INST_top.RL_hwmain_mem_serverAdapterA_overRun();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_outData_deqOnly)
	   INST_top.RL_hwmain_mem_serverAdapterA_outData_deqOnly();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterA_s1__dreg_update)
	   INST_top.RL_hwmain_mem_serverAdapterA_s1__dreg_update();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_overRun)
	   INST_top.RL_hwmain_mem_serverAdapterB_overRun();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_outData_deqOnly)
	   INST_top.RL_hwmain_mem_serverAdapterB_outData_deqOnly();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_mem_serverAdapterB_s1__dreg_update)
	   INST_top.RL_hwmain_mem_serverAdapterB_s1__dreg_update();
	 if (DEF_INST_top_INST_hwmain_proc_DEF_WILL_FIRE_RL_doFetch)
	   INST_top.INST_hwmain_proc.RL_doFetch();
	 if (DEF_INST_top_INST_hwmain_proc_DEF_WILL_FIRE_RL_doExecute)
	   INST_top.INST_hwmain_proc.RL_doExecute();
	 INST_top.INST_hwmain_proc.DEF_sb_enqoff_5_ULE_sb_deqoff___d172 = (INST_top.INST_hwmain_proc.DEF_idx__h9499) <= (INST_top.INST_hwmain_proc.DEF_sb_deqoff__h6881);
	 INST_top.INST_hwmain_proc.DEF_forwardE_wget____d91 = INST_top.INST_hwmain_proc.INST_forwardE.METH_wget();
	 INST_top.INST_hwmain_proc.DEF_mem_im_respQ_first____d95 = INST_top.INST_hwmain_proc.INST_mem_im_respQ.METH_first();
	 INST_top.INST_hwmain_proc.DEF__read__h829 = INST_top.INST_hwmain_proc.INST_sb_datav_3.METH_read();
	 INST_top.INST_hwmain_proc.DEF__read__h789 = INST_top.INST_hwmain_proc.INST_sb_datav_2.METH_read();
	 INST_top.INST_hwmain_proc.DEF__read__h749 = INST_top.INST_hwmain_proc.INST_sb_datav_1.METH_read();
	 INST_top.INST_hwmain_proc.DEF__read__h709 = INST_top.INST_hwmain_proc.INST_sb_datav_0.METH_read();
	 INST_top.INST_hwmain_proc.DEF_forwardE_whas____d90 = INST_top.INST_hwmain_proc.INST_forwardE.METH_whas();
	 INST_top.INST_hwmain_proc.DEF_funct7__h5430 = (tUInt8)((INST_top.INST_hwmain_proc.DEF_mem_im_respQ_first____d95) >> 25u);
	 INST_top.INST_hwmain_proc.DEF_opcode__h5428 = (tUInt8)((tUInt8)127u & (INST_top.INST_hwmain_proc.DEF_mem_im_respQ_first____d95));
	 INST_top.INST_hwmain_proc.DEF_x_wget_dst__h5399 = (tUInt8)((INST_top.INST_hwmain_proc.DEF_forwardE_wget____d91) >> 32u);
	 INST_top.INST_hwmain_proc.DEF_src2__h5433 = (tUInt8)((tUInt8)31u & ((INST_top.INST_hwmain_proc.DEF_mem_im_respQ_first____d95) >> 20u));
	 INST_top.INST_hwmain_proc.DEF_src1__h5432 = (tUInt8)((tUInt8)31u & ((INST_top.INST_hwmain_proc.DEF_mem_im_respQ_first____d95) >> 15u));
	 INST_top.INST_hwmain_proc.DEF_funct3__h5429 = (tUInt8)((tUInt8)7u & ((INST_top.INST_hwmain_proc.DEF_mem_im_respQ_first____d95) >> 12u));
	 INST_top.INST_hwmain_proc.DEF_mem_im_respQ_first__5_BITS_31_TO_25_8_EQ_0b0___d99 = (INST_top.INST_hwmain_proc.DEF_funct7__h5430) == (tUInt8)0u;
	 switch (INST_top.INST_hwmain_proc.DEF_funct3__h5429) {
	 case (tUInt8)0u:
	 case (tUInt8)1u:
	 case (tUInt8)4u:
	 case (tUInt8)5u:
	 case (tUInt8)6u:
	 case (tUInt8)7u:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d224 = INST_top.INST_hwmain_proc.DEF_src2__h5433;
	   break;
	 default:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d224 = (tUInt8)0u;
	 }
	 switch (INST_top.INST_hwmain_proc.DEF_funct3__h5429) {
	 case (tUInt8)0u:
	 case (tUInt8)1u:
	 case (tUInt8)4u:
	 case (tUInt8)5u:
	 case (tUInt8)6u:
	 case (tUInt8)7u:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d143 = INST_top.INST_hwmain_proc.DEF_src1__h5432;
	   break;
	 default:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d143 = (tUInt8)0u;
	 }
	 switch (INST_top.INST_hwmain_proc.DEF_funct3__h5429) {
	 case (tUInt8)0u:
	 case (tUInt8)1u:
	 case (tUInt8)2u:
	 case (tUInt8)4u:
	 case (tUInt8)5u:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d153 = INST_top.INST_hwmain_proc.DEF_src1__h5432;
	   break;
	 default:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d153 = (tUInt8)0u;
	 }
	 switch (INST_top.INST_hwmain_proc.DEF_funct3__h5429) {
	 case (tUInt8)0u:
	 case (tUInt8)1u:
	 case (tUInt8)2u:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d228 = INST_top.INST_hwmain_proc.DEF_src2__h5433;
	   break;
	 default:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d228 = (tUInt8)0u;
	 }
	 switch (INST_top.INST_hwmain_proc.DEF_funct3__h5429) {
	 case (tUInt8)0u:
	 case (tUInt8)1u:
	 case (tUInt8)2u:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d157 = INST_top.INST_hwmain_proc.DEF_src1__h5432;
	   break;
	 default:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d157 = (tUInt8)0u;
	 }
	 switch (INST_top.INST_hwmain_proc.DEF_funct7__h5430) {
	 case (tUInt8)0u:
	 case (tUInt8)32u:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_31_TO_25_8_EQ_0b_ETC___d134 = INST_top.INST_hwmain_proc.DEF_src1__h5432;
	   break;
	 default:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_31_TO_25_8_EQ_0b_ETC___d134 = (tUInt8)0u;
	 }
	 switch (INST_top.INST_hwmain_proc.DEF_funct3__h5429) {
	 case (tUInt8)0u:
	 case (tUInt8)2u:
	 case (tUInt8)3u:
	 case (tUInt8)4u:
	 case (tUInt8)6u:
	 case (tUInt8)7u:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d137 = INST_top.INST_hwmain_proc.DEF_src1__h5432;
	   break;
	 case (tUInt8)1u:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d137 = INST_top.INST_hwmain_proc.DEF_mem_im_respQ_first__5_BITS_31_TO_25_8_EQ_0b0___d99 ? INST_top.INST_hwmain_proc.DEF_src1__h5432 : (tUInt8)0u;
	   break;
	 case (tUInt8)5u:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d137 = INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_31_TO_25_8_EQ_0b_ETC___d134;
	   break;
	 default:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d137 = (tUInt8)0u;
	 }
	 switch (INST_top.INST_hwmain_proc.DEF_funct3__h5429) {
	 case (tUInt8)0u:
	 case (tUInt8)1u:
	 case (tUInt8)2u:
	 case (tUInt8)3u:
	 case (tUInt8)4u:
	 case (tUInt8)5u:
	 case (tUInt8)6u:
	 case (tUInt8)7u:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d218 = INST_top.INST_hwmain_proc.DEF_src2__h5433;
	   break;
	 default:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d218 = (tUInt8)0u;
	 }
	 switch (INST_top.INST_hwmain_proc.DEF_funct3__h5429) {
	 case (tUInt8)0u:
	 case (tUInt8)1u:
	 case (tUInt8)2u:
	 case (tUInt8)3u:
	 case (tUInt8)4u:
	 case (tUInt8)5u:
	 case (tUInt8)6u:
	 case (tUInt8)7u:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d117 = INST_top.INST_hwmain_proc.DEF_src1__h5432;
	   break;
	 default:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d117 = (tUInt8)0u;
	 }
	 switch (INST_top.INST_hwmain_proc.DEF_funct3__h5429) {
	 case (tUInt8)0u:
	 case (tUInt8)5u:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d219 = INST_top.INST_hwmain_proc.DEF_src2__h5433;
	   break;
	 default:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d219 = (tUInt8)0u;
	 }
	 switch (INST_top.INST_hwmain_proc.DEF_funct3__h5429) {
	 case (tUInt8)0u:
	 case (tUInt8)5u:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d120 = INST_top.INST_hwmain_proc.DEF_src1__h5432;
	   break;
	 default:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d120 = (tUInt8)0u;
	 }
	 INST_top.INST_hwmain_proc.DEF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0b0___d101 = (INST_top.INST_hwmain_proc.DEF_funct3__h5429) == (tUInt8)0u;
	 switch (INST_top.INST_hwmain_proc.DEF_funct7__h5430) {
	 case (tUInt8)0u:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_31_TO_25_8_EQ_0b_ETC___d223 = INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d218;
	   break;
	 case (tUInt8)32u:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_31_TO_25_8_EQ_0b_ETC___d223 = INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d219;
	   break;
	 case (tUInt8)1u:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_31_TO_25_8_EQ_0b_ETC___d223 = INST_top.INST_hwmain_proc.DEF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0b0___d101 ? INST_top.INST_hwmain_proc.DEF_src2__h5433 : (tUInt8)0u;
	   break;
	 default:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_31_TO_25_8_EQ_0b_ETC___d223 = (tUInt8)0u;
	 }
	 switch (INST_top.INST_hwmain_proc.DEF_opcode__h5428) {
	 case (tUInt8)51u:
	   INST_top.INST_hwmain_proc.DEF_dInst_src2__h6048 = INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_31_TO_25_8_EQ_0b_ETC___d223;
	   break;
	 case (tUInt8)99u:
	   INST_top.INST_hwmain_proc.DEF_dInst_src2__h6048 = INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d224;
	   break;
	 case (tUInt8)35u:
	   INST_top.INST_hwmain_proc.DEF_dInst_src2__h6048 = INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d228;
	   break;
	 default:
	   INST_top.INST_hwmain_proc.DEF_dInst_src2__h6048 = (tUInt8)0u;
	 }
	 switch (INST_top.INST_hwmain_proc.DEF_funct7__h5430) {
	 case (tUInt8)0u:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_31_TO_25_8_EQ_0b_ETC___d125 = INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d117;
	   break;
	 case (tUInt8)32u:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_31_TO_25_8_EQ_0b_ETC___d125 = INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d120;
	   break;
	 case (tUInt8)1u:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_31_TO_25_8_EQ_0b_ETC___d125 = INST_top.INST_hwmain_proc.DEF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0b0___d101 ? INST_top.INST_hwmain_proc.DEF_src1__h5432 : (tUInt8)0u;
	   break;
	 default:
	   INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_31_TO_25_8_EQ_0b_ETC___d125 = (tUInt8)0u;
	 }
	 switch (INST_top.INST_hwmain_proc.DEF_opcode__h5428) {
	 case (tUInt8)51u:
	   INST_top.INST_hwmain_proc.DEF_dInst_src1__h6047 = INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_31_TO_25_8_EQ_0b_ETC___d125;
	   break;
	 case (tUInt8)19u:
	   INST_top.INST_hwmain_proc.DEF_dInst_src1__h6047 = INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d137;
	   break;
	 case (tUInt8)99u:
	   INST_top.INST_hwmain_proc.DEF_dInst_src1__h6047 = INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d143;
	   break;
	 case (tUInt8)103u:
	   INST_top.INST_hwmain_proc.DEF_dInst_src1__h6047 = INST_top.INST_hwmain_proc.DEF_src1__h5432;
	   break;
	 case (tUInt8)3u:
	   INST_top.INST_hwmain_proc.DEF_dInst_src1__h6047 = INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d153;
	   break;
	 case (tUInt8)35u:
	   INST_top.INST_hwmain_proc.DEF_dInst_src1__h6047 = INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_14_TO_12_00_EQ_0_ETC___d157;
	   break;
	 default:
	   INST_top.INST_hwmain_proc.DEF_dInst_src1__h6047 = (tUInt8)0u;
	 }
	 INST_top.INST_hwmain_proc.DEF_p1__h9500 = (tUInt8)7u & (((tUInt8)7u & (INST_top.INST_hwmain_proc.DEF_idx__h9499)) + (tUInt8)1u);
	 INST_top.INST_hwmain_proc.DEF_x__h9503 = (INST_top.INST_hwmain_proc.DEF_p1__h9500) < (tUInt8)4u ? INST_top.INST_hwmain_proc.DEF_p1__h9500 : (tUInt8)0u;
	 INST_top.INST_hwmain_proc.DEF_x_BITS_1_TO_0___h9510 = (tUInt8)((tUInt8)3u & (INST_top.INST_hwmain_proc.DEF_x__h9503));
	 INST_top.INST_hwmain_proc.DEF_x__read_dst__h5403 = INST_top.INST_hwmain_proc.DEF_forwardE_whas____d90 ? INST_top.INST_hwmain_proc.DEF_x_wget_dst__h5399 : (tUInt8)0u;
	 INST_top.INST_hwmain_proc.DEF_IF_forwardE_whas__0_THEN_forwardE_wget__1_BITS_ETC___d213 = (INST_top.INST_hwmain_proc.DEF_x__read_dst__h5403) == (INST_top.INST_hwmain_proc.DEF_dInst_src1__h6047);
	 INST_top.INST_hwmain_proc.DEF_IF_forwardE_whas__0_THEN_forwardE_wget__1_BITS_ETC___d255 = (INST_top.INST_hwmain_proc.DEF_x__read_dst__h5403) == (INST_top.INST_hwmain_proc.DEF_dInst_src2__h6048);
	 INST_top.INST_hwmain_proc.DEF_IF_forwardE_whas__0_THEN_forwardE_wget__1_BITS_ETC___d94 = (INST_top.INST_hwmain_proc.DEF_x__read_dst__h5403) == (tUInt8)0u;
	 INST_top.INST_hwmain_proc.DEF_sb_datav_3_67_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d236 = (INST_top.INST_hwmain_proc.DEF__read__h829) == (INST_top.INST_hwmain_proc.DEF_dInst_src2__h6048);
	 INST_top.INST_hwmain_proc.DEF_sb_datav_2_70_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d237 = (INST_top.INST_hwmain_proc.DEF__read__h789) == (INST_top.INST_hwmain_proc.DEF_dInst_src2__h6048);
	 INST_top.INST_hwmain_proc.DEF_sb_datav_1_78_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d238 = (INST_top.INST_hwmain_proc.DEF__read__h749) == (INST_top.INST_hwmain_proc.DEF_dInst_src2__h6048);
	 INST_top.INST_hwmain_proc.DEF_sb_datav_3_67_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d168 = (INST_top.INST_hwmain_proc.DEF__read__h829) == (INST_top.INST_hwmain_proc.DEF_dInst_src1__h6047);
	 INST_top.INST_hwmain_proc.DEF_sb_datav_2_70_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d171 = (INST_top.INST_hwmain_proc.DEF__read__h789) == (INST_top.INST_hwmain_proc.DEF_dInst_src1__h6047);
	 INST_top.INST_hwmain_proc.DEF_sb_enqoff_5_ULT_sb_deqoff___d169 = (INST_top.INST_hwmain_proc.DEF_idx__h9499) < (INST_top.INST_hwmain_proc.DEF_sb_deqoff__h6881);
	 INST_top.INST_hwmain_proc.DEF_sb_datav_1_78_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d179 = (INST_top.INST_hwmain_proc.DEF__read__h749) == (INST_top.INST_hwmain_proc.DEF_dInst_src1__h6047);
	 INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_6_TO_0_6_EQ_0b11_ETC___d234 = (INST_top.INST_hwmain_proc.DEF_dInst_src2__h6048) == (tUInt8)0u;
	 INST_top.INST_hwmain_proc.DEF_sb_datav_0_85_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d239 = (INST_top.INST_hwmain_proc.DEF__read__h709) == (INST_top.INST_hwmain_proc.DEF_dInst_src2__h6048);
	 INST_top.INST_hwmain_proc.DEF_sb_datav_0_85_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d186 = (INST_top.INST_hwmain_proc.DEF__read__h709) == (INST_top.INST_hwmain_proc.DEF_dInst_src1__h6047);
	 INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_6_TO_0_6_EQ_0b11_ETC___d165 = (INST_top.INST_hwmain_proc.DEF_dInst_src1__h6047) == (tUInt8)0u;
	 INST_top.INST_hwmain_proc.DEF_sb_deqoff_EQ_3___d175 = (INST_top.INST_hwmain_proc.DEF_sb_deqoff__h6881) == (tUInt8)3u;
	 INST_top.INST_hwmain_proc.DEF_sb_deqoff_EQ_0___d189 = (INST_top.INST_hwmain_proc.DEF_sb_deqoff__h6881) == (tUInt8)0u;
	 INST_top.INST_hwmain_proc.DEF_sb_enqoff_5_EQ_0___d21 = (INST_top.INST_hwmain_proc.DEF_idx__h9499) == (tUInt8)0u;
	 INST_top.INST_hwmain_proc.DEF_sb_enqoff_5_EQ_3___d30 = (INST_top.INST_hwmain_proc.DEF_idx__h9499) == (tUInt8)3u;
	 INST_top.INST_hwmain_proc.DEF_NOT_sb_enqoff_5_EQ_0_1___d187 = !(INST_top.INST_hwmain_proc.DEF_sb_enqoff_5_EQ_0___d21);
	 INST_top.INST_hwmain_proc.DEF_sb_deqoff_ULE_1___d183 = (INST_top.INST_hwmain_proc.DEF_sb_deqoff__h6881) <= (tUInt8)1u;
	 INST_top.INST_hwmain_proc.DEF_sb_enqoff_5_ULE_1___d180 = (INST_top.INST_hwmain_proc.DEF_idx__h9499) <= (tUInt8)1u;
	 INST_top.INST_hwmain_proc.DEF_NOT_sb_enqoff_5_ULE_1_80___d181 = !(INST_top.INST_hwmain_proc.DEF_sb_enqoff_5_ULE_1___d180);
	 INST_top.INST_hwmain_proc.DEF_sb_enqoff_5_ULT_sb_deqoff_69_AND_NOT_sb_enqoff_ETC___d200 = INST_top.INST_hwmain_proc.DEF_sb_enqoff_5_ULT_sb_deqoff___d169 && (INST_top.INST_hwmain_proc.DEF_NOT_sb_enqoff_5_ULE_1_80___d181 || INST_top.INST_hwmain_proc.DEF_sb_deqoff_ULE_1___d183);
	 INST_top.INST_hwmain_proc.DEF_NOT_sb_deqoff_EQ_3_75___d176 = !(INST_top.INST_hwmain_proc.DEF_sb_deqoff_EQ_3___d175);
	 INST_top.INST_hwmain_proc.DEF_sb_enqoff_5_ULT_sb_deqoff_69_AND_sb_enqoff_5_E_ETC___d198 = INST_top.INST_hwmain_proc.DEF_sb_enqoff_5_ULT_sb_deqoff___d169 && (INST_top.INST_hwmain_proc.DEF_sb_enqoff_5_EQ_3___d30 || INST_top.INST_hwmain_proc.DEF_NOT_sb_deqoff_EQ_3_75___d176);
	 INST_top.INST_hwmain_proc.DEF_NOT_sb_enqoff_5_ULE_sb_deqoff_72___d173 = !(INST_top.INST_hwmain_proc.DEF_sb_enqoff_5_ULE_sb_deqoff___d172);
	 INST_top.INST_hwmain_proc.DEF_NOT_sb_enqoff_5_ULE_sb_deqoff_72_73_AND_NOT_sb_ETC___d184 = (INST_top.INST_hwmain_proc.DEF_NOT_sb_enqoff_5_ULE_sb_deqoff_72___d173 && INST_top.INST_hwmain_proc.DEF_NOT_sb_enqoff_5_ULE_1_80___d181) && INST_top.INST_hwmain_proc.DEF_sb_deqoff_ULE_1___d183;
	 INST_top.INST_hwmain_proc.DEF_NOT_sb_enqoff_5_ULE_sb_deqoff_72_73_AND_sb_enq_ETC___d177 = (INST_top.INST_hwmain_proc.DEF_NOT_sb_enqoff_5_ULE_sb_deqoff_72___d173 && INST_top.INST_hwmain_proc.DEF_sb_enqoff_5_EQ_3___d30) && INST_top.INST_hwmain_proc.DEF_NOT_sb_deqoff_EQ_3_75___d176;
	 INST_top.INST_hwmain_proc.DEF_NOT_sb_enqoff_5_ULE_sb_deqoff_72_73_AND_NOT_sb_ETC___d190 = (INST_top.INST_hwmain_proc.DEF_NOT_sb_enqoff_5_ULE_sb_deqoff_72___d173 && INST_top.INST_hwmain_proc.DEF_NOT_sb_enqoff_5_EQ_0_1___d187) && INST_top.INST_hwmain_proc.DEF_sb_deqoff_EQ_0___d189;
	 INST_top.INST_hwmain_proc.DEF_sb_datav_0_85_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d240 = INST_top.INST_hwmain_proc.DEF_sb_datav_0_85_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d239 && INST_top.INST_hwmain_proc.DEF_NOT_sb_enqoff_5_ULE_sb_deqoff_72_73_AND_NOT_sb_ETC___d190;
	 INST_top.INST_hwmain_proc.DEF_IF_sb_datav_1_78_EQ_IF_mem_im_respQ_first__5_B_ETC___d242 = INST_top.INST_hwmain_proc.DEF_sb_datav_1_78_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d238 ? INST_top.INST_hwmain_proc.DEF_NOT_sb_enqoff_5_ULE_sb_deqoff_72_73_AND_NOT_sb_ETC___d184 || INST_top.INST_hwmain_proc.DEF_sb_datav_0_85_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d240 : INST_top.INST_hwmain_proc.DEF_sb_datav_0_85_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d240;
	 INST_top.INST_hwmain_proc.DEF_sb_datav_0_85_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d191 = INST_top.INST_hwmain_proc.DEF_sb_datav_0_85_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d186 && INST_top.INST_hwmain_proc.DEF_NOT_sb_enqoff_5_ULE_sb_deqoff_72_73_AND_NOT_sb_ETC___d190;
	 INST_top.INST_hwmain_proc.DEF_IF_sb_datav_1_78_EQ_IF_mem_im_respQ_first__5_B_ETC___d193 = INST_top.INST_hwmain_proc.DEF_sb_datav_1_78_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d179 ? INST_top.INST_hwmain_proc.DEF_NOT_sb_enqoff_5_ULE_sb_deqoff_72_73_AND_NOT_sb_ETC___d184 || INST_top.INST_hwmain_proc.DEF_sb_datav_0_85_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d191 : INST_top.INST_hwmain_proc.DEF_sb_datav_0_85_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d191;
	 INST_top.INST_hwmain_proc.DEF_sb_enqoff_5_ULT_sb_deqoff_69_AND_NOT_sb_enqoff_ETC___d203 = (INST_top.INST_hwmain_proc.DEF_sb_enqoff_5_ULT_sb_deqoff___d169 && (INST_top.INST_hwmain_proc.DEF_NOT_sb_enqoff_5_EQ_0_1___d187 || INST_top.INST_hwmain_proc.DEF_sb_deqoff_EQ_0___d189)) || INST_top.INST_hwmain_proc.DEF_NOT_sb_enqoff_5_ULE_sb_deqoff_72_73_AND_NOT_sb_ETC___d190;
	 INST_top.INST_hwmain_proc.DEF_sb_datav_0_85_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d246 = INST_top.INST_hwmain_proc.DEF_sb_datav_0_85_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d239 && INST_top.INST_hwmain_proc.DEF_sb_enqoff_5_ULT_sb_deqoff_69_AND_NOT_sb_enqoff_ETC___d203;
	 INST_top.INST_hwmain_proc.DEF_IF_sb_datav_1_78_EQ_IF_mem_im_respQ_first__5_B_ETC___d249 = INST_top.INST_hwmain_proc.DEF_sb_datav_1_78_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d238 ? INST_top.INST_hwmain_proc.DEF_sb_enqoff_5_ULT_sb_deqoff_69_AND_NOT_sb_enqoff_ETC___d200 || (INST_top.INST_hwmain_proc.DEF_NOT_sb_enqoff_5_ULE_sb_deqoff_72_73_AND_NOT_sb_ETC___d184 || INST_top.INST_hwmain_proc.DEF_sb_datav_0_85_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d246) : INST_top.INST_hwmain_proc.DEF_sb_datav_0_85_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d246;
	 INST_top.INST_hwmain_proc.DEF_NOT_IF_mem_im_respQ_first__5_BITS_6_TO_0_6_EQ__ETC___d254 = !(INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_6_TO_0_6_EQ_0b11_ETC___d234) && (INST_top.INST_hwmain_proc.DEF_sb_datav_3_67_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d236 ? INST_top.INST_hwmain_proc.DEF_sb_enqoff_5_ULT_sb_deqoff___d169 || (INST_top.INST_hwmain_proc.DEF_sb_datav_2_70_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d237 ? INST_top.INST_hwmain_proc.DEF_NOT_sb_enqoff_5_ULE_sb_deqoff_72_73_AND_sb_enq_ETC___d177 || INST_top.INST_hwmain_proc.DEF_IF_sb_datav_1_78_EQ_IF_mem_im_respQ_first__5_B_ETC___d242 : INST_top.INST_hwmain_proc.DEF_IF_sb_datav_1_78_EQ_IF_mem_im_respQ_first__5_B_ETC___d242) : (INST_top.INST_hwmain_proc.DEF_sb_datav_2_70_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d237 ? INST_top.INST_hwmain_proc.DEF_sb_enqoff_5_ULT_sb_deqoff_69_AND_sb_enqoff_5_E_ETC___d198 || (INST_top.INST_hwmain_proc.DEF_NOT_sb_enqoff_5_ULE_sb_deqoff_72_73_AND_sb_enq_ETC___d177 || INST_top.INST_hwmain_proc.DEF_IF_sb_datav_1_78_EQ_IF_mem_im_respQ_first__5_B_ETC___d249) : INST_top.INST_hwmain_proc.DEF_IF_sb_datav_1_78_EQ_IF_mem_im_respQ_first__5_B_ETC___d249));
	 INST_top.INST_hwmain_proc.DEF_NOT_IF_forwardE_whas__0_THEN_forwardE_wget__1__ETC___d257 = !(INST_top.INST_hwmain_proc.DEF_IF_forwardE_whas__0_THEN_forwardE_wget__1_BITS_ETC___d255) && INST_top.INST_hwmain_proc.DEF_NOT_IF_mem_im_respQ_first__5_BITS_6_TO_0_6_EQ__ETC___d254;
	 INST_top.INST_hwmain_proc.DEF_sb_datav_0_85_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d204 = INST_top.INST_hwmain_proc.DEF_sb_datav_0_85_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d186 && INST_top.INST_hwmain_proc.DEF_sb_enqoff_5_ULT_sb_deqoff_69_AND_NOT_sb_enqoff_ETC___d203;
	 INST_top.INST_hwmain_proc.DEF_IF_sb_datav_1_78_EQ_IF_mem_im_respQ_first__5_B_ETC___d207 = INST_top.INST_hwmain_proc.DEF_sb_datav_1_78_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d179 ? INST_top.INST_hwmain_proc.DEF_sb_enqoff_5_ULT_sb_deqoff_69_AND_NOT_sb_enqoff_ETC___d200 || (INST_top.INST_hwmain_proc.DEF_NOT_sb_enqoff_5_ULE_sb_deqoff_72_73_AND_NOT_sb_ETC___d184 || INST_top.INST_hwmain_proc.DEF_sb_datav_0_85_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d204) : INST_top.INST_hwmain_proc.DEF_sb_datav_0_85_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d204;
	 INST_top.INST_hwmain_proc.DEF_NOT_IF_mem_im_respQ_first__5_BITS_6_TO_0_6_EQ__ETC___d212 = !(INST_top.INST_hwmain_proc.DEF_IF_mem_im_respQ_first__5_BITS_6_TO_0_6_EQ_0b11_ETC___d165) && (INST_top.INST_hwmain_proc.DEF_sb_datav_3_67_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d168 ? INST_top.INST_hwmain_proc.DEF_sb_enqoff_5_ULT_sb_deqoff___d169 || (INST_top.INST_hwmain_proc.DEF_sb_datav_2_70_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d171 ? INST_top.INST_hwmain_proc.DEF_NOT_sb_enqoff_5_ULE_sb_deqoff_72_73_AND_sb_enq_ETC___d177 || INST_top.INST_hwmain_proc.DEF_IF_sb_datav_1_78_EQ_IF_mem_im_respQ_first__5_B_ETC___d193 : INST_top.INST_hwmain_proc.DEF_IF_sb_datav_1_78_EQ_IF_mem_im_respQ_first__5_B_ETC___d193) : (INST_top.INST_hwmain_proc.DEF_sb_datav_2_70_EQ_IF_mem_im_respQ_first__5_BITS_ETC___d171 ? INST_top.INST_hwmain_proc.DEF_sb_enqoff_5_ULT_sb_deqoff_69_AND_sb_enqoff_5_E_ETC___d198 || (INST_top.INST_hwmain_proc.DEF_NOT_sb_enqoff_5_ULE_sb_deqoff_72_73_AND_sb_enq_ETC___d177 || INST_top.INST_hwmain_proc.DEF_IF_sb_datav_1_78_EQ_IF_mem_im_respQ_first__5_B_ETC___d207) : INST_top.INST_hwmain_proc.DEF_IF_sb_datav_1_78_EQ_IF_mem_im_respQ_first__5_B_ETC___d207));
	 INST_top.INST_hwmain_proc.DEF_NOT_IF_forwardE_whas__0_THEN_forwardE_wget__1__ETC___d215 = !(INST_top.INST_hwmain_proc.DEF_IF_forwardE_whas__0_THEN_forwardE_wget__1_BITS_ETC___d213) && INST_top.INST_hwmain_proc.DEF_NOT_IF_mem_im_respQ_first__5_BITS_6_TO_0_6_EQ__ETC___d212;
	 DEF_INST_top_INST_hwmain_proc_DEF_CAN_FIRE_RL_doDecode = INST_top.INST_hwmain_proc.INST_mem_im_respQ.METH_i_notEmpty() && (INST_top.INST_hwmain_proc.INST_f2d.METH_i_notEmpty() && (((INST_top.INST_hwmain_proc.DEF_IF_forwardE_whas__0_THEN_forwardE_wget__1_BITS_ETC___d94 ? INST_top.INST_hwmain_proc.DEF_NOT_IF_mem_im_respQ_first__5_BITS_6_TO_0_6_EQ__ETC___d212 : INST_top.INST_hwmain_proc.DEF_NOT_IF_forwardE_whas__0_THEN_forwardE_wget__1__ETC___d215) || (INST_top.INST_hwmain_proc.DEF_IF_forwardE_whas__0_THEN_forwardE_wget__1_BITS_ETC___d94 ? INST_top.INST_hwmain_proc.DEF_NOT_IF_mem_im_respQ_first__5_BITS_6_TO_0_6_EQ__ETC___d254 : INST_top.INST_hwmain_proc.DEF_NOT_IF_forwardE_whas__0_THEN_forwardE_wget__1__ETC___d257)) || (!((INST_top.INST_hwmain_proc.DEF_sb_deqoff__h6881) == (INST_top.INST_hwmain_proc.DEF_x_BITS_1_TO_0___h9510)) && INST_top.INST_hwmain_proc.INST_d2e.METH_i_notFull())));
	 DEF_INST_top_INST_hwmain_proc_DEF_WILL_FIRE_RL_doDecode = DEF_INST_top_INST_hwmain_proc_DEF_CAN_FIRE_RL_doDecode;
	 if (DEF_INST_top_INST_hwmain_proc_DEF_WILL_FIRE_RL_doDecode)
	   INST_top.INST_hwmain_proc.RL_doDecode();
	 if (DEF_INST_top_INST_hwmain_proc_DEF_WILL_FIRE_RL_doWriteback)
	   INST_top.INST_hwmain_proc.RL_doWriteback();
	 if (DEF_INST_top_INST_hwmain_proc_DEF_WILL_FIRE_RL_incCycle)
	   INST_top.INST_hwmain_proc.RL_incCycle();
	 if (DEF_INST_top_INST_hwmain_proc_DEF_WILL_FIRE_RL_mem_relayResp)
	   INST_top.INST_hwmain_proc.RL_mem_relayResp();
	 if (DEF_INST_top_INST_hwmain_proc_DEF_WILL_FIRE_RL_sb_normalize)
	   INST_top.INST_hwmain_proc.RL_sb_normalize();
	 INST_top.INST_hwmain_mem_serverAdapterB_s1_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_hwmain_mem_serverAdapterB_writeWithResp.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_hwmain_mem_serverAdapterB_cnt_3.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_hwmain_mem_serverAdapterB_cnt_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_hwmain_mem_serverAdapterB_cnt_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_hwmain_mem_serverAdapterB_outData_deqCalled.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_hwmain_mem_serverAdapterB_outData_outData.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_hwmain_mem_serverAdapterB_outData_enqData.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_hwmain_mem_serverAdapterA_s1_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_hwmain_mem_serverAdapterA_writeWithResp.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_hwmain_mem_serverAdapterA_cnt_3.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_hwmain_mem_serverAdapterA_cnt_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_hwmain_mem_serverAdapterA_cnt_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_hwmain_mem_serverAdapterA_outData_deqCalled.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_hwmain_mem_serverAdapterA_outData_outData.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_hwmain_mem_serverAdapterA_outData_enqData.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_hwmain_mem_memory.clkA((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_hwmain_mem_memory.clkB((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_hwmain_proc.INST_forwardE.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_hwmain_proc.INST_sb_deqreq.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_hwmain_proc.INST_sb_enqdata.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_hwmain_proc.INST_sb_enqreq.clk((tUInt8)1u, (tUInt8)1u);
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_hwmain_proc.INST_cycles.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_instCnt.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_f2d.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_d2e.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_e2m.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_sb_datav_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_sb_datav_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_sb_datav_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_sb_datav_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_sb_enqoff.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_sb_deqoff.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_8.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_9.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_10.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_11.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_12.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_13.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_14.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_15.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_16.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_17.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_18.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_19.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_20.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_21.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_22.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_23.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_24.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_25.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_26.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_27.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_28.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_29.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_30.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_rf_rfile_31.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_mem_im_reqQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_mem_im_respQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_mem_dm_reqQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_mem_dm_respQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_mem_reqQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_mem_respQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_mem_reqTargetIsIMemQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_nextpcQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_pc.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_proc.INST_epoch.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_uart_inQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_uart_outQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_uart_outCnt.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_uart_inReqId.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_mem_serverAdapterA_outDataCore.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_mem_serverAdapterA_cnt.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_mem_serverAdapterA_s1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_mem_serverAdapterB_outDataCore.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_mem_serverAdapterB_cnt.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_mem_serverAdapterB_s1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_relayUart.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_initialized.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkBsvTop_bsim::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkBsvTop_bsim_instance = new MOD_mkBsvTop_bsim(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkBsvTop_bsim_instance->INST_uart_inQ.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_uart_outQ.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_proc.INST_f2d.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_proc.INST_d2e.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_proc.INST_e2m.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_proc.INST_sb_enqreq.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_proc.INST_sb_enqdata.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_proc.INST_sb_deqreq.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_proc.INST_mem_im_reqQ.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_proc.INST_mem_im_respQ.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_proc.INST_mem_dm_reqQ.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_proc.INST_mem_dm_respQ.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_proc.INST_mem_reqQ.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_proc.INST_mem_respQ.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_proc.INST_mem_reqTargetIsIMemQ.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_proc.INST_nextpcQ.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_proc.INST_forwardE.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_proc.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_mem_memory.set_clk_1)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_mem_memory.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_mem_serverAdapterA_outDataCore.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_mem_serverAdapterA_outData_enqData.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_mem_serverAdapterA_outData_outData.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_mem_serverAdapterA_outData_deqCalled.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_mem_serverAdapterA_cnt_1.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_mem_serverAdapterA_cnt_2.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_mem_serverAdapterA_cnt_3.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_mem_serverAdapterA_writeWithResp.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_mem_serverAdapterA_s1_1.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_mem_serverAdapterB_outDataCore.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_mem_serverAdapterB_outData_enqData.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_mem_serverAdapterB_outData_outData.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_mem_serverAdapterB_outData_deqCalled.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_mem_serverAdapterB_cnt_1.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_mem_serverAdapterB_cnt_2.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_mem_serverAdapterB_cnt_3.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_mem_serverAdapterB_writeWithResp.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_mem_serverAdapterB_s1_1.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_relayUart.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->set_clk_0)("CLK");
}
void MODEL_mkBsvTop_bsim::destroy_model()
{
  delete mkBsvTop_bsim_instance;
  mkBsvTop_bsim_instance = NULL;
}
void MODEL_mkBsvTop_bsim::reset_model(bool asserted)
{
  (mkBsvTop_bsim_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkBsvTop_bsim::get_instance()
{
  return mkBsvTop_bsim_instance;
}

/* Fill in version numbers */
void MODEL_mkBsvTop_bsim::get_version(unsigned int *year,
				      unsigned int *month,
				      char const **annotation,
				      char const **build)
{
  *year = 2014u;
  *month = 7u;
  *annotation = "A";
  *build = "34078";
}

/* Get the model creation time */
time_t MODEL_mkBsvTop_bsim::get_creation_time()
{
  
  /* Tue May 19 22:33:31 UTC 2020 */
  return 1589927611llu;
}

/* Control run-time licensing */
tUInt64 MODEL_mkBsvTop_bsim::skip_license_check()
{
  return 0llu;
}

/* State dumping function */
void MODEL_mkBsvTop_bsim::dump_state()
{
  (mkBsvTop_bsim_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkBsvTop_bsim & mkBsvTop_bsim_backing(tSimStateHdl simHdl)
{
  static MOD_mkBsvTop_bsim *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkBsvTop_bsim(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkBsvTop_bsim::dump_VCD_defs()
{
  (mkBsvTop_bsim_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkBsvTop_bsim::dump_VCD(tVCDDumpType dt)
{
  (mkBsvTop_bsim_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkBsvTop_bsim_backing(sim_hdl));
}
