/*
 * Generated by Bluespec Compiler (build 629c10a)
 * 
 * On Sat Jul  3 01:51:09 UTC 2021
 * 
 */
extern "C" {
  void bdpiSwInit();
  unsigned int bdpiUartGet(char );
  void bdpiUartPut(unsigned int );
}
