/*
 * Generated by Bluespec Compiler, version 2014.07.A (build 34078, 2014-07-30)
 * 
 * On Tue May 19 23:26:45 PDT 2020
 * 
 */
extern "C" {
  void bdpiSwInit();
  unsigned int bdpiUartGet(char );
  void bdpiUartPut(unsigned int );
}
