/*
 * Generated by Bluespec Compiler (build 629c10a)
 * 
 * On Sat Jul  3 01:51:09 UTC 2021
 * 
 */
#include "bluesim_primitives.h"
#include "mkBsvTop_bsim.h"
#include "imported_BDPI_functions.h"


/* Constructor */
MOD_mkBsvTop_bsim::MOD_mkBsvTop_bsim(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_hwmain_floatAdder_calcQ(simHdl, "hwmain_floatAdder_calcQ", this, 55u, 1u, (tUInt8)1u, 0u),
    INST_hwmain_floatAdder_inProcQ(simHdl, "hwmain_floatAdder_inProcQ", this, 63u, 1u, (tUInt8)1u, 0u),
    INST_hwmain_floatAdder_inQ(simHdl, "hwmain_floatAdder_inQ", this, 64u, 1u, (tUInt8)1u, 0u),
    INST_hwmain_floatAdder_normalizeQ(simHdl,
				      "hwmain_floatAdder_normalizeQ",
				      this,
				      28u,
				      1u,
				      (tUInt8)1u,
				      0u),
    INST_hwmain_floatAdder_normalizeQ1(simHdl,
				       "hwmain_floatAdder_normalizeQ1",
				       this,
				       28u,
				       1u,
				       (tUInt8)1u,
				       0u),
    INST_hwmain_floatAdder_normalizeQ2(simHdl,
				       "hwmain_floatAdder_normalizeQ2",
				       this,
				       28u,
				       1u,
				       (tUInt8)1u,
				       0u),
    INST_hwmain_floatAdder_normalizeQ3(simHdl,
				       "hwmain_floatAdder_normalizeQ3",
				       this,
				       28u,
				       1u,
				       (tUInt8)1u,
				       0u),
    INST_hwmain_floatAdder_normalizeQ4(simHdl,
				       "hwmain_floatAdder_normalizeQ4",
				       this,
				       28u,
				       1u,
				       (tUInt8)1u,
				       0u),
    INST_hwmain_floatAdder_outQ(simHdl, "hwmain_floatAdder_outQ", this, 32u, 1u, (tUInt8)1u, 0u),
    INST_hwmain_floatMultiplier_multQ(simHdl,
				      "hwmain_floatMultiplier_multQ",
				      this,
				      32u,
				      2u,
				      (tUInt8)1u,
				      0u),
    INST_hwmain_floatMultiplier_outQ(simHdl,
				     "hwmain_floatMultiplier_outQ",
				     this,
				     32u,
				     2u,
				     (tUInt8)1u,
				     0u),
    INST_hwmain_floatMultiplier_signExpZeroQ(simHdl,
					     "hwmain_floatMultiplier_signExpZeroQ",
					     this,
					     11u,
					     4u,
					     (tUInt8)1u,
					     0u),
    INST_hwmain_floatingQ(simHdl, "hwmain_floatingQ", this, 32u, 2u, (tUInt8)1u, 0u),
    INST_hwmain_inputBuffer(simHdl, "hwmain_inputBuffer", this, 32u, 0u, (tUInt8)0u),
    INST_hwmain_inputBufferCnt(simHdl, "hwmain_inputBufferCnt", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_hwmain_outputBuffer(simHdl, "hwmain_outputBuffer", this, 32u, 0u, (tUInt8)0u),
    INST_hwmain_outputBufferCnt(simHdl, "hwmain_outputBufferCnt", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_hwmain_ram_outQ(simHdl, "hwmain_ram_outQ", this, 16u, 2u, (tUInt8)1u, 0u),
    INST_hwmain_ram_ram(simHdl, "hwmain_ram_ram", this, 14u, 16u, 0u, 16383u),
    INST_hwmain_ram_reqWire(simHdl, "hwmain_ram_reqWire", this, 35u, (tUInt8)0u),
    INST_hwmain_relayUartInQ(simHdl, "hwmain_relayUartInQ", this, 8u, 2u, (tUInt8)1u, 0u),
    INST_hwmain_relayUartOutQ(simHdl, "hwmain_relayUartOutQ", this, 8u, 2u, (tUInt8)1u, 0u),
    INST_initialized(simHdl, "initialized", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_uart_inQ(simHdl, "uart_inQ", this, 8u, 2u, (tUInt8)1u, 0u),
    INST_uart_inReqId(simHdl, "uart_inReqId", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_uart_outCnt(simHdl, "uart_outCnt", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_uart_outQ(simHdl, "uart_outQ", this, 8u, 2u, (tUInt8)1u, 0u),
    PORT_RST_N((tUInt8)1u),
    DEF_v__h303(2863311530u)
{
  symbol_count = 46u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkBsvTop_bsim::init_symbols_0()
{
  init_symbol(&symbols[0u], "hwmain_floatAdder_calcQ", SYM_MODULE, &INST_hwmain_floatAdder_calcQ);
  init_symbol(&symbols[1u], "hwmain_floatAdder_inProcQ", SYM_MODULE, &INST_hwmain_floatAdder_inProcQ);
  init_symbol(&symbols[2u], "hwmain_floatAdder_inQ", SYM_MODULE, &INST_hwmain_floatAdder_inQ);
  init_symbol(&symbols[3u],
	      "hwmain_floatAdder_normalizeQ",
	      SYM_MODULE,
	      &INST_hwmain_floatAdder_normalizeQ);
  init_symbol(&symbols[4u],
	      "hwmain_floatAdder_normalizeQ1",
	      SYM_MODULE,
	      &INST_hwmain_floatAdder_normalizeQ1);
  init_symbol(&symbols[5u],
	      "hwmain_floatAdder_normalizeQ2",
	      SYM_MODULE,
	      &INST_hwmain_floatAdder_normalizeQ2);
  init_symbol(&symbols[6u],
	      "hwmain_floatAdder_normalizeQ3",
	      SYM_MODULE,
	      &INST_hwmain_floatAdder_normalizeQ3);
  init_symbol(&symbols[7u],
	      "hwmain_floatAdder_normalizeQ4",
	      SYM_MODULE,
	      &INST_hwmain_floatAdder_normalizeQ4);
  init_symbol(&symbols[8u], "hwmain_floatAdder_outQ", SYM_MODULE, &INST_hwmain_floatAdder_outQ);
  init_symbol(&symbols[9u], "hwmain_floatingQ", SYM_MODULE, &INST_hwmain_floatingQ);
  init_symbol(&symbols[10u],
	      "hwmain_floatMultiplier_multQ",
	      SYM_MODULE,
	      &INST_hwmain_floatMultiplier_multQ);
  init_symbol(&symbols[11u],
	      "hwmain_floatMultiplier_outQ",
	      SYM_MODULE,
	      &INST_hwmain_floatMultiplier_outQ);
  init_symbol(&symbols[12u],
	      "hwmain_floatMultiplier_signExpZeroQ",
	      SYM_MODULE,
	      &INST_hwmain_floatMultiplier_signExpZeroQ);
  init_symbol(&symbols[13u], "hwmain_inputBuffer", SYM_MODULE, &INST_hwmain_inputBuffer);
  init_symbol(&symbols[14u], "hwmain_inputBufferCnt", SYM_MODULE, &INST_hwmain_inputBufferCnt);
  init_symbol(&symbols[15u], "hwmain_outputBuffer", SYM_MODULE, &INST_hwmain_outputBuffer);
  init_symbol(&symbols[16u], "hwmain_outputBufferCnt", SYM_MODULE, &INST_hwmain_outputBufferCnt);
  init_symbol(&symbols[17u], "hwmain_ram_outQ", SYM_MODULE, &INST_hwmain_ram_outQ);
  init_symbol(&symbols[18u], "hwmain_ram_ram", SYM_MODULE, &INST_hwmain_ram_ram);
  init_symbol(&symbols[19u], "hwmain_ram_reqWire", SYM_MODULE, &INST_hwmain_ram_reqWire);
  init_symbol(&symbols[20u], "hwmain_relayUartInQ", SYM_MODULE, &INST_hwmain_relayUartInQ);
  init_symbol(&symbols[21u], "hwmain_relayUartOutQ", SYM_MODULE, &INST_hwmain_relayUartOutQ);
  init_symbol(&symbols[22u], "initialized", SYM_MODULE, &INST_initialized);
  init_symbol(&symbols[23u], "RL_doinit", SYM_RULE);
  init_symbol(&symbols[24u], "RL_hwmain_floatAdder_calcFrac", SYM_RULE);
  init_symbol(&symbols[25u], "RL_hwmain_floatAdder_calcFrac2", SYM_RULE);
  init_symbol(&symbols[26u], "RL_hwmain_floatAdder_normalize", SYM_RULE);
  init_symbol(&symbols[27u], "RL_hwmain_floatAdder_normalize1", SYM_RULE);
  init_symbol(&symbols[28u], "RL_hwmain_floatAdder_normalize2", SYM_RULE);
  init_symbol(&symbols[29u], "RL_hwmain_floatAdder_normalize3", SYM_RULE);
  init_symbol(&symbols[30u], "RL_hwmain_floatAdder_normalize4", SYM_RULE);
  init_symbol(&symbols[31u], "RL_hwmain_floatAdder_procIn", SYM_RULE);
  init_symbol(&symbols[32u], "RL_hwmain_floatMultiplier_procMultResult", SYM_RULE);
  init_symbol(&symbols[33u], "RL_hwmain_readFloat", SYM_RULE);
  init_symbol(&symbols[34u], "RL_hwmain_ttt", SYM_RULE);
  init_symbol(&symbols[35u], "RL_hwmain_writeFloat", SYM_RULE);
  init_symbol(&symbols[36u], "RL_relayUartIn", SYM_RULE);
  init_symbol(&symbols[37u], "RL_relayUartOut", SYM_RULE);
  init_symbol(&symbols[38u], "RL_uart_relayIn", SYM_RULE);
  init_symbol(&symbols[39u], "RL_uart_relayOut", SYM_RULE);
  init_symbol(&symbols[40u], "uart_inQ", SYM_MODULE, &INST_uart_inQ);
  init_symbol(&symbols[41u], "uart_inReqId", SYM_MODULE, &INST_uart_inReqId);
  init_symbol(&symbols[42u], "uart_outCnt", SYM_MODULE, &INST_uart_outCnt);
  init_symbol(&symbols[43u], "uart_outQ", SYM_MODULE, &INST_uart_outQ);
  init_symbol(&symbols[44u], "x__h4112", SYM_DEF, &DEF_x__h4112, 2u);
  init_symbol(&symbols[45u], "x__h4144", SYM_DEF, &DEF_x__h4144, 2u);
}


/* Rule actions */

void MOD_mkBsvTop_bsim::RL_uart_relayOut()
{
  tUInt8 DEF_x__h353;
  tUInt8 DEF_TASK_bdpiUartGet_BITS_15_TO_8_EQ_0___d5;
  tUInt8 DEF_data__h320;
  tUInt8 DEF_flg__h321;
  tUInt8 DEF_x__h376;
  DEF_x__h376 = INST_uart_inReqId.METH_read();
  DEF_x__h353 = (tUInt8)255u & (DEF_x__h376 + (tUInt8)1u);
  if (!(PORT_RST_N == (tUInt8)0u))
    DEF_v__h303 = bdpiUartGet(DEF_x__h376);
  DEF_flg__h321 = (tUInt8)((tUInt8)255u & (DEF_v__h303 >> 8u));
  DEF_data__h320 = (tUInt8)((tUInt8)255u & DEF_v__h303);
  DEF_TASK_bdpiUartGet_BITS_15_TO_8_EQ_0___d5 = DEF_flg__h321 == (tUInt8)0u;
  if (DEF_TASK_bdpiUartGet_BITS_15_TO_8_EQ_0___d5)
    INST_uart_inReqId.METH_write(DEF_x__h353);
  if (DEF_TASK_bdpiUartGet_BITS_15_TO_8_EQ_0___d5)
    INST_uart_outQ.METH_enq(DEF_data__h320);
}

void MOD_mkBsvTop_bsim::RL_uart_relayIn()
{
  tUInt32 DEF__0_CONCAT_uart_outCnt_CONCAT_uart_inQ_first__1___d12;
  tUInt8 DEF_x__h431;
  tUInt8 DEF_d__h421;
  tUInt8 DEF_x__h439;
  DEF_x__h439 = INST_uart_outCnt.METH_read();
  DEF_d__h421 = INST_uart_inQ.METH_first();
  DEF_x__h431 = (tUInt8)255u & (DEF_x__h439 + (tUInt8)1u);
  DEF__0_CONCAT_uart_outCnt_CONCAT_uart_inQ_first__1___d12 = (((tUInt32)(DEF_x__h439)) << 8u) | (tUInt32)(DEF_d__h421);
  INST_uart_inQ.METH_deq();
  INST_uart_outCnt.METH_write(DEF_x__h431);
  if (!(PORT_RST_N == (tUInt8)0u))
    bdpiUartPut(DEF__0_CONCAT_uart_outCnt_CONCAT_uart_inQ_first__1___d12);
}

void MOD_mkBsvTop_bsim::RL_hwmain_floatMultiplier_procMultResult()
{
  tUInt8 DEF__theResult___snd__h1256;
  tUInt32 DEF__theResult___fst__h1255;
  tUInt32 DEF_x__h1211;
  tUInt32 DEF_IF_hwmain_floatMultiplier_signExpZeroQ_first___ETC___d34;
  tUInt8 DEF_sign__h1176;
  tUInt8 DEF_hwmain_floatMultiplier_multQ_first__1_BIT_31___d22;
  tUInt32 DEF_x__h1270;
  tUInt8 DEF_newexp__h1267;
  tUInt32 DEF_x__h1261;
  tUInt8 DEF_newexp__h1258;
  tUInt32 DEF_expsum__h1177;
  tUInt32 DEF_newfrac__h1266;
  tUInt32 DEF_newfrac__h1257;
  tUInt32 DEF_hwmain_floatMultiplier_signExpZeroQ_first____d18;
  tUInt32 DEF_hwmain_floatMultiplier_multQ_first____d21;
  DEF_hwmain_floatMultiplier_multQ_first____d21 = INST_hwmain_floatMultiplier_multQ.METH_first();
  DEF_hwmain_floatMultiplier_signExpZeroQ_first____d18 = INST_hwmain_floatMultiplier_signExpZeroQ.METH_first();
  DEF_newfrac__h1257 = (tUInt32)(65535u & (DEF_hwmain_floatMultiplier_multQ_first____d21 >> 15u));
  DEF_newfrac__h1266 = (tUInt32)(65535u & (DEF_hwmain_floatMultiplier_multQ_first____d21 >> 14u));
  DEF_expsum__h1177 = (tUInt32)(511u & (DEF_hwmain_floatMultiplier_signExpZeroQ_first____d18 >> 1u));
  DEF_x__h1261 = 511u & (DEF_expsum__h1177 - 126u);
  DEF_newexp__h1258 = (tUInt8)((tUInt8)255u & DEF_x__h1261);
  DEF_x__h1270 = 511u & (DEF_expsum__h1177 - 127u);
  DEF_newexp__h1267 = (tUInt8)((tUInt8)255u & DEF_x__h1270);
  DEF_hwmain_floatMultiplier_multQ_first__1_BIT_31___d22 = (tUInt8)(DEF_hwmain_floatMultiplier_multQ_first____d21 >> 31u);
  DEF_sign__h1176 = (tUInt8)(DEF_hwmain_floatMultiplier_signExpZeroQ_first____d18 >> 10u);
  DEF__theResult___fst__h1255 = DEF_hwmain_floatMultiplier_multQ_first__1_BIT_31___d22 ? DEF_newfrac__h1257 : DEF_newfrac__h1266;
  DEF__theResult___snd__h1256 = DEF_hwmain_floatMultiplier_multQ_first__1_BIT_31___d22 ? DEF_newexp__h1258 : DEF_newexp__h1267;
  DEF_x__h1211 = (((((tUInt32)(DEF_sign__h1176)) << 31u) | (((tUInt32)(DEF__theResult___snd__h1256)) << 23u)) | (DEF__theResult___fst__h1255 << 7u)) | (tUInt32)((tUInt8)0u);
  DEF_IF_hwmain_floatMultiplier_signExpZeroQ_first___ETC___d34 = (tUInt8)((tUInt8)1u & DEF_hwmain_floatMultiplier_signExpZeroQ_first____d18) ? 0u : DEF_x__h1211;
  INST_hwmain_floatMultiplier_multQ.METH_deq();
  INST_hwmain_floatMultiplier_signExpZeroQ.METH_deq();
  INST_hwmain_floatMultiplier_outQ.METH_enq(DEF_IF_hwmain_floatMultiplier_signExpZeroQ_first___ETC___d34);
}

void MOD_mkBsvTop_bsim::RL_hwmain_floatAdder_procIn()
{
  tUInt64 DEF_NOT_hwmain_floatAdder_inQ_first__8_BITS_62_TO__ETC___d60;
  tUInt32 DEF_fracb__h2134;
  tUInt32 DEF_fraca__h2133;
  tUInt8 DEF_hwmain_floatAdder_inQ_first__8_BITS_62_TO_55_9_ETC___d41;
  tUInt8 DEF_x__h2302;
  tUInt8 DEF_signb__h2138;
  tUInt8 DEF_signa__h2137;
  tUInt8 DEF_expb__h2136;
  tUInt8 DEF_expa__h2135;
  tUInt32 DEF_x__h2266;
  tUInt32 DEF_x__h2228;
  tUInt64 DEF_hwmain_floatAdder_inQ_first____d38;
  DEF_hwmain_floatAdder_inQ_first____d38 = INST_hwmain_floatAdder_inQ.METH_first();
  DEF_x__h2228 = (tUInt32)(131071u & (DEF_hwmain_floatAdder_inQ_first____d38 >> 38u));
  DEF_x__h2266 = (tUInt32)(131071u & (DEF_hwmain_floatAdder_inQ_first____d38 >> 6u));
  DEF_expa__h2135 = (tUInt8)((tUInt8)255u & (DEF_hwmain_floatAdder_inQ_first____d38 >> 55u));
  DEF_expb__h2136 = (tUInt8)((tUInt8)255u & (DEF_hwmain_floatAdder_inQ_first____d38 >> 23u));
  DEF_signb__h2138 = (tUInt8)((tUInt8)1u & (DEF_hwmain_floatAdder_inQ_first____d38 >> 31u));
  DEF_signa__h2137 = (tUInt8)(DEF_hwmain_floatAdder_inQ_first____d38 >> 63u);
  DEF_hwmain_floatAdder_inQ_first__8_BITS_62_TO_55_9_ETC___d41 = DEF_expa__h2135 <= DEF_expb__h2136;
  DEF_x__h2302 = DEF_hwmain_floatAdder_inQ_first__8_BITS_62_TO_55_9_ETC___d41 ? (tUInt8)255u & (DEF_expb__h2136 - DEF_expa__h2135) : (tUInt8)255u & (DEF_expa__h2135 - DEF_expb__h2136);
  DEF_fraca__h2133 = 262143u & ((((tUInt32)((tUInt8)1u)) << 17u) | DEF_x__h2228);
  DEF_fracb__h2134 = 262143u & ((((tUInt32)((tUInt8)1u)) << 17u) | DEF_x__h2266);
  DEF_NOT_hwmain_floatAdder_inQ_first__8_BITS_62_TO__ETC___d60 = 9223372036854775807llu & ((((((((((tUInt64)(!DEF_hwmain_floatAdder_inQ_first__8_BITS_62_TO_55_9_ETC___d41 || (DEF_expa__h2135 == DEF_expb__h2136 && !(DEF_fraca__h2133 <= DEF_fracb__h2134)))) << 62u) | (((tUInt64)(DEF_x__h2302)) << 54u)) | (((tUInt64)(DEF_fraca__h2133)) << 36u)) | (((tUInt64)(DEF_expa__h2135)) << 28u)) | (((tUInt64)(DEF_signa__h2137)) << 27u)) | (((tUInt64)(DEF_fracb__h2134)) << 9u)) | (((tUInt64)(DEF_expb__h2136)) << 1u)) | (tUInt64)(DEF_signb__h2138));
  INST_hwmain_floatAdder_inQ.METH_deq();
  INST_hwmain_floatAdder_inProcQ.METH_enq(DEF_NOT_hwmain_floatAdder_inQ_first__8_BITS_62_TO__ETC___d60);
}

void MOD_mkBsvTop_bsim::RL_hwmain_floatAdder_calcFrac()
{
  tUInt64 DEF_hwmain_floatAdder_inProcQ_first__4_BIT_62_5_CO_ETC___d77;
  tUInt32 DEF_fraca__h2416;
  tUInt32 DEF_fracb__h2417;
  tUInt8 DEF_hwmain_floatAdder_inProcQ_first__4_BIT_62___d65;
  tUInt8 DEF_hwmain_floatAdder_inProcQ_first__4_BITS_61_TO_54___d67;
  tUInt32 DEF_fracb__h2411;
  tUInt32 DEF_fraca__h2410;
  tUInt64 DEF_hwmain_floatAdder_inProcQ_first____d64;
  DEF_hwmain_floatAdder_inProcQ_first____d64 = INST_hwmain_floatAdder_inProcQ.METH_first();
  DEF_fraca__h2410 = (tUInt32)(262143u & (DEF_hwmain_floatAdder_inProcQ_first____d64 >> 36u));
  DEF_fracb__h2411 = (tUInt32)(262143u & (DEF_hwmain_floatAdder_inProcQ_first____d64 >> 9u));
  DEF_hwmain_floatAdder_inProcQ_first__4_BITS_61_TO_54___d67 = (tUInt8)((tUInt8)255u & (DEF_hwmain_floatAdder_inProcQ_first____d64 >> 54u));
  DEF_hwmain_floatAdder_inProcQ_first__4_BIT_62___d65 = (tUInt8)(DEF_hwmain_floatAdder_inProcQ_first____d64 >> 62u);
  DEF_fracb__h2417 = DEF_hwmain_floatAdder_inProcQ_first__4_BIT_62___d65 ? primShiftR32(18u,
											18u,
											(tUInt32)(DEF_fracb__h2411),
											8u,
											(tUInt8)(DEF_hwmain_floatAdder_inProcQ_first__4_BITS_61_TO_54___d67)) : DEF_fracb__h2411;
  DEF_fraca__h2416 = DEF_hwmain_floatAdder_inProcQ_first__4_BIT_62___d65 ? DEF_fraca__h2410 : primShiftR32(18u,
													   18u,
													   (tUInt32)(DEF_fraca__h2410),
													   8u,
													   (tUInt8)(DEF_hwmain_floatAdder_inProcQ_first__4_BITS_61_TO_54___d67));
  DEF_hwmain_floatAdder_inProcQ_first__4_BIT_62_5_CO_ETC___d77 = 36028797018963967llu & (((((((tUInt64)(DEF_hwmain_floatAdder_inProcQ_first__4_BIT_62___d65)) << 54u) | (((tUInt64)(DEF_fraca__h2416)) << 36u)) | (((tUInt64)((tUInt32)(511u & (DEF_hwmain_floatAdder_inProcQ_first____d64 >> 27u)))) << 27u)) | (((tUInt64)(DEF_fracb__h2417)) << 9u)) | (tUInt64)((tUInt32)(511u & DEF_hwmain_floatAdder_inProcQ_first____d64)));
  INST_hwmain_floatAdder_inProcQ.METH_deq();
  INST_hwmain_floatAdder_calcQ.METH_enq(DEF_hwmain_floatAdder_inProcQ_first__4_BIT_62_5_CO_ETC___d77);
}

void MOD_mkBsvTop_bsim::RL_hwmain_floatAdder_calcFrac2()
{
  tUInt32 DEF_IF_hwmain_floatAdder_calcQ_first__1_BIT_54_2_T_ETC___d101;
  tUInt8 DEF_x__h2598;
  tUInt8 DEF_x__h2645;
  tUInt32 DEF_x__h2670;
  tUInt32 DEF_x__h2687;
  tUInt32 DEF_newfrac__h2660;
  tUInt32 DEF_newfrac__h2651;
  tUInt32 DEF_x__h2649;
  tUInt8 DEF_signb__h2580;
  tUInt8 DEF_signa__h2579;
  tUInt8 DEF_hwmain_floatAdder_calcQ_first__1_BIT_54___d82;
  tUInt8 DEF_expb__h2578;
  tUInt8 DEF_expa__h2577;
  tUInt32 DEF_fracb__h2576;
  tUInt32 DEF_fraca__h2575;
  tUInt64 DEF_hwmain_floatAdder_calcQ_first____d81;
  DEF_hwmain_floatAdder_calcQ_first____d81 = INST_hwmain_floatAdder_calcQ.METH_first();
  DEF_fraca__h2575 = (tUInt32)(262143u & (DEF_hwmain_floatAdder_calcQ_first____d81 >> 36u));
  DEF_fracb__h2576 = (tUInt32)(262143u & (DEF_hwmain_floatAdder_calcQ_first____d81 >> 9u));
  DEF_expa__h2577 = (tUInt8)((tUInt8)255u & (DEF_hwmain_floatAdder_calcQ_first____d81 >> 28u));
  DEF_expb__h2578 = (tUInt8)((tUInt8)255u & (DEF_hwmain_floatAdder_calcQ_first____d81 >> 1u));
  DEF_hwmain_floatAdder_calcQ_first__1_BIT_54___d82 = (tUInt8)(DEF_hwmain_floatAdder_calcQ_first____d81 >> 54u);
  DEF_signa__h2579 = (tUInt8)((tUInt8)1u & (DEF_hwmain_floatAdder_calcQ_first____d81 >> 27u));
  DEF_signb__h2580 = (tUInt8)((tUInt8)1u & DEF_hwmain_floatAdder_calcQ_first____d81);
  DEF_newfrac__h2651 = 524287u & ((524287u & ((((tUInt32)((tUInt8)0u)) << 18u) | DEF_fraca__h2575)) + (524287u & ((((tUInt32)((tUInt8)0u)) << 18u) | DEF_fracb__h2576)));
  DEF_x__h2687 = 262143u & (DEF_fracb__h2576 - DEF_fraca__h2575);
  DEF_x__h2670 = 262143u & (DEF_fraca__h2575 - DEF_fracb__h2576);
  DEF_newfrac__h2660 = 524287u & ((((tUInt32)((tUInt8)0u)) << 18u) | (DEF_fraca__h2575 <= DEF_fracb__h2576 ? DEF_x__h2687 : DEF_x__h2670));
  DEF_x__h2649 = DEF_signa__h2579 == DEF_signb__h2580 ? DEF_newfrac__h2651 : DEF_newfrac__h2660;
  DEF_x__h2645 = DEF_hwmain_floatAdder_calcQ_first__1_BIT_54___d82 ? DEF_expa__h2577 : DEF_expb__h2578;
  DEF_x__h2598 = DEF_hwmain_floatAdder_calcQ_first__1_BIT_54___d82 ? DEF_signa__h2579 : DEF_signb__h2580;
  DEF_IF_hwmain_floatAdder_calcQ_first__1_BIT_54_2_T_ETC___d101 = 268435455u & (((((tUInt32)(DEF_x__h2598)) << 27u) | (((tUInt32)(DEF_x__h2645)) << 19u)) | DEF_x__h2649);
  INST_hwmain_floatAdder_calcQ.METH_deq();
  INST_hwmain_floatAdder_normalizeQ.METH_enq(DEF_IF_hwmain_floatAdder_calcQ_first__1_BIT_54_2_T_ETC___d101);
}

void MOD_mkBsvTop_bsim::RL_hwmain_floatAdder_normalize()
{
  tUInt32 DEF_newfrac___1__h2778;
  tUInt32 DEF_hwmain_floatAdder_normalizeQ_first__05_BIT_27__ETC___d115;
  tUInt8 DEF_newexp___1__h2779;
  tUInt8 DEF_x__h2731;
  tUInt8 DEF_newexp__h2721;
  tUInt32 DEF_hwmain_floatAdder_normalizeQ_first____d105;
  DEF_hwmain_floatAdder_normalizeQ_first____d105 = INST_hwmain_floatAdder_normalizeQ.METH_first();
  DEF_newexp__h2721 = (tUInt8)((tUInt8)255u & (DEF_hwmain_floatAdder_normalizeQ_first____d105 >> 19u));
  DEF_x__h2731 = (tUInt8)(DEF_hwmain_floatAdder_normalizeQ_first____d105 >> 27u);
  DEF_newexp___1__h2779 = (tUInt8)255u & (DEF_newexp__h2721 + (tUInt8)1u);
  DEF_newfrac___1__h2778 = 524287u & ((((tUInt32)((tUInt8)0u)) << 18u) | (tUInt32)(262143u & (DEF_hwmain_floatAdder_normalizeQ_first____d105 >> 1u)));
  DEF_hwmain_floatAdder_normalizeQ_first__05_BIT_27__ETC___d115 = 268435455u & ((((tUInt32)(DEF_x__h2731)) << 27u) | ((tUInt8)((tUInt8)1u & (DEF_hwmain_floatAdder_normalizeQ_first____d105 >> 18u)) ? 134217727u & ((((tUInt32)(DEF_newexp___1__h2779)) << 19u) | DEF_newfrac___1__h2778) : (tUInt32)(134217727u & DEF_hwmain_floatAdder_normalizeQ_first____d105)));
  INST_hwmain_floatAdder_normalizeQ.METH_deq();
  INST_hwmain_floatAdder_normalizeQ1.METH_enq(DEF_hwmain_floatAdder_normalizeQ_first__05_BIT_27__ETC___d115);
}

void MOD_mkBsvTop_bsim::RL_hwmain_floatAdder_normalize1()
{
  tUInt32 DEF_newfrac___1__h2877;
  tUInt32 DEF_hwmain_floatAdder_normalizeQ1_first__19_BIT_27_ETC___d134;
  tUInt8 DEF_newexp___1__h2878;
  tUInt8 DEF_x__h2827;
  tUInt8 DEF_newexp__h2817;
  tUInt32 DEF_newfrac__h2818;
  tUInt32 DEF_hwmain_floatAdder_normalizeQ1_first____d119;
  DEF_hwmain_floatAdder_normalizeQ1_first____d119 = INST_hwmain_floatAdder_normalizeQ1.METH_first();
  DEF_newfrac__h2818 = (tUInt32)(524287u & DEF_hwmain_floatAdder_normalizeQ1_first____d119);
  DEF_newexp__h2817 = (tUInt8)((tUInt8)255u & (DEF_hwmain_floatAdder_normalizeQ1_first____d119 >> 19u));
  DEF_x__h2827 = (tUInt8)(DEF_hwmain_floatAdder_normalizeQ1_first____d119 >> 27u);
  DEF_newexp___1__h2878 = (tUInt8)255u & (DEF_newexp__h2817 - (tUInt8)9u);
  DEF_newfrac___1__h2877 = 524287u & (((tUInt32)(1023u & DEF_hwmain_floatAdder_normalizeQ1_first____d119)) << 9u);
  DEF_hwmain_floatAdder_normalizeQ1_first__19_BIT_27_ETC___d134 = 268435455u & ((((tUInt32)(DEF_x__h2827)) << 27u) | (((tUInt32)(511u & (DEF_hwmain_floatAdder_normalizeQ1_first____d119 >> 9u))) == 0u && !(DEF_newfrac__h2818 == 0u) ? 134217727u & ((((tUInt32)(DEF_newexp___1__h2878)) << 19u) | DEF_newfrac___1__h2877) : (tUInt32)(134217727u & DEF_hwmain_floatAdder_normalizeQ1_first____d119)));
  INST_hwmain_floatAdder_normalizeQ1.METH_deq();
  INST_hwmain_floatAdder_normalizeQ2.METH_enq(DEF_hwmain_floatAdder_normalizeQ1_first__19_BIT_27_ETC___d134);
}

void MOD_mkBsvTop_bsim::RL_hwmain_floatAdder_normalize2()
{
  tUInt32 DEF_newfrac___1__h2976;
  tUInt32 DEF_hwmain_floatAdder_normalizeQ2_first__38_BIT_27_ETC___d153;
  tUInt8 DEF_newexp___1__h2977;
  tUInt8 DEF_x__h2926;
  tUInt8 DEF_newexp__h2916;
  tUInt32 DEF_newfrac__h2917;
  tUInt32 DEF_hwmain_floatAdder_normalizeQ2_first____d138;
  DEF_hwmain_floatAdder_normalizeQ2_first____d138 = INST_hwmain_floatAdder_normalizeQ2.METH_first();
  DEF_newfrac__h2917 = (tUInt32)(524287u & DEF_hwmain_floatAdder_normalizeQ2_first____d138);
  DEF_newexp__h2916 = (tUInt8)((tUInt8)255u & (DEF_hwmain_floatAdder_normalizeQ2_first____d138 >> 19u));
  DEF_x__h2926 = (tUInt8)(DEF_hwmain_floatAdder_normalizeQ2_first____d138 >> 27u);
  DEF_newexp___1__h2977 = (tUInt8)255u & (DEF_newexp__h2916 - (tUInt8)5u);
  DEF_newfrac___1__h2976 = 524287u & ((((tUInt32)(16383u & DEF_hwmain_floatAdder_normalizeQ2_first____d138)) << 5u) | (tUInt32)((tUInt8)0u));
  DEF_hwmain_floatAdder_normalizeQ2_first__38_BIT_27_ETC___d153 = 268435455u & ((((tUInt32)(DEF_x__h2926)) << 27u) | (((tUInt8)((tUInt8)15u & (DEF_hwmain_floatAdder_normalizeQ2_first____d138 >> 14u))) == (tUInt8)0u && !(DEF_newfrac__h2917 == 0u) ? 134217727u & ((((tUInt32)(DEF_newexp___1__h2977)) << 19u) | DEF_newfrac___1__h2976) : (tUInt32)(134217727u & DEF_hwmain_floatAdder_normalizeQ2_first____d138)));
  INST_hwmain_floatAdder_normalizeQ2.METH_deq();
  INST_hwmain_floatAdder_normalizeQ3.METH_enq(DEF_hwmain_floatAdder_normalizeQ2_first__38_BIT_27_ETC___d153);
}

void MOD_mkBsvTop_bsim::RL_hwmain_floatAdder_normalize3()
{
  tUInt32 DEF_newfrac___1__h3075;
  tUInt32 DEF_hwmain_floatAdder_normalizeQ3_first__57_BIT_27_ETC___d172;
  tUInt8 DEF_newexp___1__h3076;
  tUInt8 DEF_x__h3025;
  tUInt8 DEF_newexp__h3015;
  tUInt32 DEF_newfrac__h3016;
  tUInt32 DEF_hwmain_floatAdder_normalizeQ3_first____d157;
  DEF_hwmain_floatAdder_normalizeQ3_first____d157 = INST_hwmain_floatAdder_normalizeQ3.METH_first();
  DEF_newfrac__h3016 = (tUInt32)(524287u & DEF_hwmain_floatAdder_normalizeQ3_first____d157);
  DEF_newexp__h3015 = (tUInt8)((tUInt8)255u & (DEF_hwmain_floatAdder_normalizeQ3_first____d157 >> 19u));
  DEF_x__h3025 = (tUInt8)(DEF_hwmain_floatAdder_normalizeQ3_first____d157 >> 27u);
  DEF_newexp___1__h3076 = (tUInt8)255u & (DEF_newexp__h3015 - (tUInt8)2u);
  DEF_newfrac___1__h3075 = 524287u & ((((tUInt32)(131071u & DEF_hwmain_floatAdder_normalizeQ3_first____d157)) << 2u) | (tUInt32)((tUInt8)0u));
  DEF_hwmain_floatAdder_normalizeQ3_first__57_BIT_27_ETC___d172 = 268435455u & ((((tUInt32)(DEF_x__h3025)) << 27u) | (((tUInt8)((tUInt8)3u & (DEF_hwmain_floatAdder_normalizeQ3_first____d157 >> 16u))) == (tUInt8)0u && !(DEF_newfrac__h3016 == 0u) ? 134217727u & ((((tUInt32)(DEF_newexp___1__h3076)) << 19u) | DEF_newfrac___1__h3075) : (tUInt32)(134217727u & DEF_hwmain_floatAdder_normalizeQ3_first____d157)));
  INST_hwmain_floatAdder_normalizeQ3.METH_deq();
  INST_hwmain_floatAdder_normalizeQ4.METH_enq(DEF_hwmain_floatAdder_normalizeQ3_first__57_BIT_27_ETC___d172);
}

void MOD_mkBsvTop_bsim::RL_hwmain_floatAdder_normalize4()
{
  tUInt32 DEF_x__h3118;
  tUInt8 DEF_newexp___1__h3170;
  tUInt8 DEF__theResult___snd__h3168;
  tUInt32 DEF_newfrac___1__h3169;
  tUInt8 DEF_NOT_hwmain_floatAdder_normalizeQ4_first__76_BI_ETC___d183;
  tUInt8 DEF_newsign__h3111;
  tUInt8 DEF_newexp__h3112;
  tUInt32 DEF_x__h3175;
  tUInt32 DEF_newfrace__h3115;
  tUInt32 DEF_newfrac__h3113;
  tUInt32 DEF_hwmain_floatAdder_normalizeQ4_first____d176;
  DEF_hwmain_floatAdder_normalizeQ4_first____d176 = INST_hwmain_floatAdder_normalizeQ4.METH_first();
  DEF_newfrac__h3113 = (tUInt32)(524287u & DEF_hwmain_floatAdder_normalizeQ4_first____d176);
  DEF_newexp__h3112 = (tUInt8)((tUInt8)255u & (DEF_hwmain_floatAdder_normalizeQ4_first____d176 >> 19u));
  DEF_newsign__h3111 = (tUInt8)(DEF_hwmain_floatAdder_normalizeQ4_first____d176 >> 27u);
  DEF_NOT_hwmain_floatAdder_normalizeQ4_first__76_BI_ETC___d183 = !((tUInt8)((tUInt8)1u & (DEF_hwmain_floatAdder_normalizeQ4_first____d176 >> 17u))) && !(DEF_newfrac__h3113 == 0u);
  DEF_newfrac___1__h3169 = 524287u & ((((tUInt32)(262143u & DEF_hwmain_floatAdder_normalizeQ4_first____d176)) << 1u) | (tUInt32)((tUInt8)0u));
  DEF_x__h3175 = DEF_NOT_hwmain_floatAdder_normalizeQ4_first__76_BI_ETC___d183 ? DEF_newfrac___1__h3169 : DEF_newfrac__h3113;
  DEF_newfrace__h3115 = (tUInt32)(131071u & DEF_x__h3175);
  DEF_newexp___1__h3170 = (tUInt8)255u & (DEF_newexp__h3112 - (tUInt8)1u);
  DEF__theResult___snd__h3168 = DEF_NOT_hwmain_floatAdder_normalizeQ4_first__76_BI_ETC___d183 ? DEF_newexp___1__h3170 : DEF_newexp__h3112;
  DEF_x__h3118 = (((((tUInt32)(DEF_newsign__h3111)) << 31u) | (((tUInt32)(DEF__theResult___snd__h3168)) << 23u)) | (DEF_newfrace__h3115 << 6u)) | (tUInt32)((tUInt8)0u);
  INST_hwmain_floatAdder_normalizeQ4.METH_deq();
  INST_hwmain_floatAdder_outQ.METH_enq(DEF_x__h3118);
}

void MOD_mkBsvTop_bsim::RL_hwmain_ttt()
{
  tUInt8 DEF_x__h3662;
  tUInt32 DEF_v__h3629;
  DEF_v__h3629 = INST_hwmain_ram_outQ.METH_first();
  DEF_x__h3662 = (tUInt8)((tUInt8)255u & DEF_v__h3629);
  INST_hwmain_ram_outQ.METH_deq();
  INST_hwmain_relayUartInQ.METH_enq(DEF_x__h3662);
}

void MOD_mkBsvTop_bsim::RL_hwmain_readFloat()
{
  tUInt32 DEF_hwmain_relayUartInQ_first__07_BIT_7_17_XOR_hwm_ETC___d226;
  tUInt32 DEF_nv__h3699;
  tUInt32 DEF__0_CONCAT_hwmain_relayUartInQ_first__07_BITS_6__ETC___d222;
  tUInt32 DEF_x__h3990;
  tUInt8 DEF_x__h3947;
  tUInt32 DEF__1_CONCAT_hwmain_inputBuffer_08_BITS_30_TO_16_13___d214;
  tUInt8 DEF_a_exp__h3840;
  tUInt8 DEF_x__h3750;
  tUInt8 DEF_IF_hwmain_inputBufferCnt_99_EQ_3_00_THEN_0_ELS_ETC___d212;
  tUInt8 DEF_data_BIT_7___h3844;
  tUInt8 DEF_hwmain_inputBuffer_BITS_31_TO_8__BIT_23___h3848;
  tUInt8 DEF_data_BITS_6_TO_0___h3847;
  tUInt32 DEF_x__h3810;
  tUInt32 DEF_hwmain_inputBuffer_BITS_31_TO_8___h3733;
  tUInt32 DEF_v__h3784;
  tUInt8 DEF_data__h3698;
  tUInt32 DEF_hwmain_inputBuffer___d208;
  DEF_hwmain_inputBuffer___d208 = INST_hwmain_inputBuffer.METH_read();
  DEF_data__h3698 = INST_hwmain_relayUartInQ.METH_first();
  DEF_x__h4112 = INST_hwmain_inputBufferCnt.METH_read();
  DEF_hwmain_inputBuffer_BITS_31_TO_8___h3733 = (tUInt32)(DEF_hwmain_inputBuffer___d208 >> 8u);
  DEF_x__h3810 = (tUInt32)(32767u & (DEF_hwmain_inputBuffer___d208 >> 16u));
  DEF_data_BITS_6_TO_0___h3847 = (tUInt8)((tUInt8)127u & DEF_data__h3698);
  DEF_hwmain_inputBuffer_BITS_31_TO_8__BIT_23___h3848 = (tUInt8)(DEF_hwmain_inputBuffer___d208 >> 31u);
  DEF_data_BIT_7___h3844 = (tUInt8)(DEF_data__h3698 >> 7u);
  DEF_hwmain_inputBufferCnt_99_EQ_3___d200 = DEF_x__h4112 == (tUInt8)3u;
  DEF_x__h3750 = (tUInt8)3u & (DEF_x__h4112 + (tUInt8)1u);
  DEF_IF_hwmain_inputBufferCnt_99_EQ_3_00_THEN_0_ELS_ETC___d212 = DEF_hwmain_inputBufferCnt_99_EQ_3___d200 ? (tUInt8)0u : DEF_x__h3750;
  DEF_a_exp__h3840 = (tUInt8)255u & ((DEF_data_BITS_6_TO_0___h3847 << 1u) | DEF_hwmain_inputBuffer_BITS_31_TO_8__BIT_23___h3848);
  DEF_x__h3947 = DEF_data_BIT_7___h3844 ^ DEF_data_BIT_7___h3844;
  DEF__1_CONCAT_hwmain_inputBuffer_08_BITS_30_TO_16_13___d214 = (1u << 15u) | DEF_x__h3810;
  DEF_v__h3784 = (tUInt32)(((tUInt64)(DEF__1_CONCAT_hwmain_inputBuffer_08_BITS_30_TO_16_13___d214)) * ((tUInt64)(DEF__1_CONCAT_hwmain_inputBuffer_08_BITS_30_TO_16_13___d214)));
  DEF__0_CONCAT_hwmain_relayUartInQ_first__07_BITS_6__ETC___d222 = 511u & ((((tUInt32)((tUInt8)0u)) << 8u) | (tUInt32)(DEF_a_exp__h3840));
  DEF_x__h3990 = 511u & (DEF__0_CONCAT_hwmain_relayUartInQ_first__07_BITS_6__ETC___d222 + DEF__0_CONCAT_hwmain_relayUartInQ_first__07_BITS_6__ETC___d222);
  DEF_nv__h3699 = (((tUInt32)(DEF_data__h3698)) << 24u) | DEF_hwmain_inputBuffer_BITS_31_TO_8___h3733;
  DEF_hwmain_relayUartInQ_first__07_BIT_7_17_XOR_hwm_ETC___d226 = 2047u & (((((tUInt32)(DEF_x__h3947)) << 10u) | (DEF_x__h3990 << 1u)) | (tUInt32)(DEF_a_exp__h3840 == (tUInt8)0u));
  INST_hwmain_relayUartInQ.METH_deq();
  INST_hwmain_inputBuffer.METH_write(DEF_nv__h3699);
  INST_hwmain_inputBufferCnt.METH_write(DEF_IF_hwmain_inputBufferCnt_99_EQ_3_00_THEN_0_ELS_ETC___d212);
  if (DEF_hwmain_inputBufferCnt_99_EQ_3___d200)
    INST_hwmain_floatMultiplier_multQ.METH_enq(DEF_v__h3784);
  if (DEF_hwmain_inputBufferCnt_99_EQ_3___d200)
    INST_hwmain_floatMultiplier_signExpZeroQ.METH_enq(DEF_hwmain_relayUartInQ_first__07_BIT_7_17_XOR_hwm_ETC___d226);
}

void MOD_mkBsvTop_bsim::RL_hwmain_writeFloat()
{
  tUInt32 DEF__0_CONCAT_IF_hwmain_outputBufferCnt_28_EQ_0_29__ETC___d239;
  tUInt8 DEF_x__h4136;
  tUInt8 DEF_IF_hwmain_outputBufferCnt_28_EQ_0_29_THEN_3_EL_ETC___d241;
  tUInt8 DEF_IF_hwmain_outputBufferCnt_28_EQ_0_29_THEN_hwma_ETC___d244;
  tUInt8 DEF_tmp__h4236;
  tUInt8 DEF_tmp__h4187;
  tUInt32 DEF_hwmain_outputBuffer_BITS_31_TO_8___h4219;
  tUInt32 DEF_x__h4296;
  tUInt32 DEF_x__h4232;
  DEF_x__h4232 = INST_hwmain_outputBuffer.METH_read();
  DEF_x__h4296 = INST_hwmain_floatMultiplier_outQ.METH_first();
  DEF_x__h4144 = INST_hwmain_outputBufferCnt.METH_read();
  DEF_hwmain_outputBuffer_BITS_31_TO_8___h4219 = (tUInt32)(DEF_x__h4232 >> 8u);
  DEF_tmp__h4187 = (tUInt8)((tUInt8)255u & DEF_x__h4232);
  DEF_tmp__h4236 = (tUInt8)((tUInt8)255u & DEF_x__h4296);
  DEF_hwmain_outputBufferCnt_28_EQ_0___d229 = DEF_x__h4144 == (tUInt8)0u;
  DEF_IF_hwmain_outputBufferCnt_28_EQ_0_29_THEN_hwma_ETC___d244 = DEF_hwmain_outputBufferCnt_28_EQ_0___d229 ? DEF_tmp__h4236 : DEF_tmp__h4187;
  DEF_x__h4136 = (tUInt8)3u & (DEF_x__h4144 - (tUInt8)1u);
  DEF_IF_hwmain_outputBufferCnt_28_EQ_0_29_THEN_3_EL_ETC___d241 = DEF_hwmain_outputBufferCnt_28_EQ_0___d229 ? (tUInt8)3u : DEF_x__h4136;
  DEF__0_CONCAT_IF_hwmain_outputBufferCnt_28_EQ_0_29__ETC___d239 = (((tUInt32)((tUInt8)0u)) << 24u) | (DEF_hwmain_outputBufferCnt_28_EQ_0___d229 ? (tUInt32)(DEF_x__h4296 >> 8u) : DEF_hwmain_outputBuffer_BITS_31_TO_8___h4219);
  INST_hwmain_outputBuffer.METH_write(DEF__0_CONCAT_IF_hwmain_outputBufferCnt_28_EQ_0_29__ETC___d239);
  INST_hwmain_outputBufferCnt.METH_write(DEF_IF_hwmain_outputBufferCnt_28_EQ_0_29_THEN_3_EL_ETC___d241);
  if (DEF_hwmain_outputBufferCnt_28_EQ_0___d229)
    INST_hwmain_floatMultiplier_outQ.METH_deq();
  INST_hwmain_relayUartOutQ.METH_enq(DEF_IF_hwmain_outputBufferCnt_28_EQ_0_29_THEN_hwma_ETC___d244);
}

void MOD_mkBsvTop_bsim::RL_doinit()
{
  INST_initialized.METH_write((tUInt8)1u);
  if (!(PORT_RST_N == (tUInt8)0u))
    bdpiSwInit();
}

void MOD_mkBsvTop_bsim::RL_relayUartIn()
{
  tUInt8 DEF_v__h4392;
  DEF_v__h4392 = INST_uart_outQ.METH_first();
  INST_uart_outQ.METH_deq();
  INST_hwmain_relayUartInQ.METH_enq(DEF_v__h4392);
}

void MOD_mkBsvTop_bsim::RL_relayUartOut()
{
  tUInt8 DEF_v__h4434;
  DEF_v__h4434 = INST_hwmain_relayUartOutQ.METH_first();
  INST_hwmain_relayUartOutQ.METH_deq();
  INST_uart_inQ.METH_enq(DEF_v__h4434);
}


/* Methods */


/* Reset routines */

void MOD_mkBsvTop_bsim::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_uart_outQ.reset_RST(ARG_rst_in);
  INST_uart_outCnt.reset_RST(ARG_rst_in);
  INST_uart_inReqId.reset_RST(ARG_rst_in);
  INST_uart_inQ.reset_RST(ARG_rst_in);
  INST_initialized.reset_RST(ARG_rst_in);
  INST_hwmain_relayUartOutQ.reset_RST(ARG_rst_in);
  INST_hwmain_relayUartInQ.reset_RST(ARG_rst_in);
  INST_hwmain_ram_outQ.reset_RST(ARG_rst_in);
  INST_hwmain_outputBufferCnt.reset_RST(ARG_rst_in);
  INST_hwmain_outputBuffer.reset_RST(ARG_rst_in);
  INST_hwmain_inputBufferCnt.reset_RST(ARG_rst_in);
  INST_hwmain_inputBuffer.reset_RST(ARG_rst_in);
  INST_hwmain_floatingQ.reset_RST(ARG_rst_in);
  INST_hwmain_floatMultiplier_signExpZeroQ.reset_RST(ARG_rst_in);
  INST_hwmain_floatMultiplier_outQ.reset_RST(ARG_rst_in);
  INST_hwmain_floatMultiplier_multQ.reset_RST(ARG_rst_in);
  INST_hwmain_floatAdder_outQ.reset_RST(ARG_rst_in);
  INST_hwmain_floatAdder_normalizeQ4.reset_RST(ARG_rst_in);
  INST_hwmain_floatAdder_normalizeQ3.reset_RST(ARG_rst_in);
  INST_hwmain_floatAdder_normalizeQ2.reset_RST(ARG_rst_in);
  INST_hwmain_floatAdder_normalizeQ1.reset_RST(ARG_rst_in);
  INST_hwmain_floatAdder_normalizeQ.reset_RST(ARG_rst_in);
  INST_hwmain_floatAdder_inQ.reset_RST(ARG_rst_in);
  INST_hwmain_floatAdder_inProcQ.reset_RST(ARG_rst_in);
  INST_hwmain_floatAdder_calcQ.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkBsvTop_bsim::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkBsvTop_bsim::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_hwmain_floatAdder_calcQ.dump_state(indent + 2u);
  INST_hwmain_floatAdder_inProcQ.dump_state(indent + 2u);
  INST_hwmain_floatAdder_inQ.dump_state(indent + 2u);
  INST_hwmain_floatAdder_normalizeQ.dump_state(indent + 2u);
  INST_hwmain_floatAdder_normalizeQ1.dump_state(indent + 2u);
  INST_hwmain_floatAdder_normalizeQ2.dump_state(indent + 2u);
  INST_hwmain_floatAdder_normalizeQ3.dump_state(indent + 2u);
  INST_hwmain_floatAdder_normalizeQ4.dump_state(indent + 2u);
  INST_hwmain_floatAdder_outQ.dump_state(indent + 2u);
  INST_hwmain_floatMultiplier_multQ.dump_state(indent + 2u);
  INST_hwmain_floatMultiplier_outQ.dump_state(indent + 2u);
  INST_hwmain_floatMultiplier_signExpZeroQ.dump_state(indent + 2u);
  INST_hwmain_floatingQ.dump_state(indent + 2u);
  INST_hwmain_inputBuffer.dump_state(indent + 2u);
  INST_hwmain_inputBufferCnt.dump_state(indent + 2u);
  INST_hwmain_outputBuffer.dump_state(indent + 2u);
  INST_hwmain_outputBufferCnt.dump_state(indent + 2u);
  INST_hwmain_ram_outQ.dump_state(indent + 2u);
  INST_hwmain_ram_ram.dump_state(indent + 2u);
  INST_hwmain_ram_reqWire.dump_state(indent + 2u);
  INST_hwmain_relayUartInQ.dump_state(indent + 2u);
  INST_hwmain_relayUartOutQ.dump_state(indent + 2u);
  INST_initialized.dump_state(indent + 2u);
  INST_uart_inQ.dump_state(indent + 2u);
  INST_uart_inReqId.dump_state(indent + 2u);
  INST_uart_outCnt.dump_state(indent + 2u);
  INST_uart_outQ.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkBsvTop_bsim::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 33u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "hwmain_inputBufferCnt_99_EQ_3___d200", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "hwmain_outputBufferCnt_28_EQ_0___d229", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h303", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h4112", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h4144", 2u);
  num = INST_hwmain_floatAdder_calcQ.dump_VCD_defs(num);
  num = INST_hwmain_floatAdder_inProcQ.dump_VCD_defs(num);
  num = INST_hwmain_floatAdder_inQ.dump_VCD_defs(num);
  num = INST_hwmain_floatAdder_normalizeQ.dump_VCD_defs(num);
  num = INST_hwmain_floatAdder_normalizeQ1.dump_VCD_defs(num);
  num = INST_hwmain_floatAdder_normalizeQ2.dump_VCD_defs(num);
  num = INST_hwmain_floatAdder_normalizeQ3.dump_VCD_defs(num);
  num = INST_hwmain_floatAdder_normalizeQ4.dump_VCD_defs(num);
  num = INST_hwmain_floatAdder_outQ.dump_VCD_defs(num);
  num = INST_hwmain_floatMultiplier_multQ.dump_VCD_defs(num);
  num = INST_hwmain_floatMultiplier_outQ.dump_VCD_defs(num);
  num = INST_hwmain_floatMultiplier_signExpZeroQ.dump_VCD_defs(num);
  num = INST_hwmain_floatingQ.dump_VCD_defs(num);
  num = INST_hwmain_inputBuffer.dump_VCD_defs(num);
  num = INST_hwmain_inputBufferCnt.dump_VCD_defs(num);
  num = INST_hwmain_outputBuffer.dump_VCD_defs(num);
  num = INST_hwmain_outputBufferCnt.dump_VCD_defs(num);
  num = INST_hwmain_ram_outQ.dump_VCD_defs(num);
  num = INST_hwmain_ram_ram.dump_VCD_defs(num);
  num = INST_hwmain_ram_reqWire.dump_VCD_defs(num);
  num = INST_hwmain_relayUartInQ.dump_VCD_defs(num);
  num = INST_hwmain_relayUartOutQ.dump_VCD_defs(num);
  num = INST_initialized.dump_VCD_defs(num);
  num = INST_uart_inQ.dump_VCD_defs(num);
  num = INST_uart_inReqId.dump_VCD_defs(num);
  num = INST_uart_outCnt.dump_VCD_defs(num);
  num = INST_uart_outQ.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkBsvTop_bsim::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkBsvTop_bsim &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkBsvTop_bsim::vcd_defs(tVCDDumpType dt, MOD_mkBsvTop_bsim &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 2u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_hwmain_inputBufferCnt_99_EQ_3___d200) != DEF_hwmain_inputBufferCnt_99_EQ_3___d200)
      {
	vcd_write_val(sim_hdl, num, DEF_hwmain_inputBufferCnt_99_EQ_3___d200, 1u);
	backing.DEF_hwmain_inputBufferCnt_99_EQ_3___d200 = DEF_hwmain_inputBufferCnt_99_EQ_3___d200;
      }
      ++num;
      if ((backing.DEF_hwmain_outputBufferCnt_28_EQ_0___d229) != DEF_hwmain_outputBufferCnt_28_EQ_0___d229)
      {
	vcd_write_val(sim_hdl, num, DEF_hwmain_outputBufferCnt_28_EQ_0___d229, 1u);
	backing.DEF_hwmain_outputBufferCnt_28_EQ_0___d229 = DEF_hwmain_outputBufferCnt_28_EQ_0___d229;
      }
      ++num;
      if ((backing.DEF_v__h303) != DEF_v__h303)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h303, 32u);
	backing.DEF_v__h303 = DEF_v__h303;
      }
      ++num;
      if ((backing.DEF_x__h4112) != DEF_x__h4112)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h4112, 2u);
	backing.DEF_x__h4112 = DEF_x__h4112;
      }
      ++num;
      if ((backing.DEF_x__h4144) != DEF_x__h4144)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h4144, 2u);
	backing.DEF_x__h4144 = DEF_x__h4144;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_hwmain_inputBufferCnt_99_EQ_3___d200, 1u);
      backing.DEF_hwmain_inputBufferCnt_99_EQ_3___d200 = DEF_hwmain_inputBufferCnt_99_EQ_3___d200;
      vcd_write_val(sim_hdl, num++, DEF_hwmain_outputBufferCnt_28_EQ_0___d229, 1u);
      backing.DEF_hwmain_outputBufferCnt_28_EQ_0___d229 = DEF_hwmain_outputBufferCnt_28_EQ_0___d229;
      vcd_write_val(sim_hdl, num++, DEF_v__h303, 32u);
      backing.DEF_v__h303 = DEF_v__h303;
      vcd_write_val(sim_hdl, num++, DEF_x__h4112, 2u);
      backing.DEF_x__h4112 = DEF_x__h4112;
      vcd_write_val(sim_hdl, num++, DEF_x__h4144, 2u);
      backing.DEF_x__h4144 = DEF_x__h4144;
    }
}

void MOD_mkBsvTop_bsim::vcd_prims(tVCDDumpType dt, MOD_mkBsvTop_bsim &backing)
{
  INST_hwmain_floatAdder_calcQ.dump_VCD(dt, backing.INST_hwmain_floatAdder_calcQ);
  INST_hwmain_floatAdder_inProcQ.dump_VCD(dt, backing.INST_hwmain_floatAdder_inProcQ);
  INST_hwmain_floatAdder_inQ.dump_VCD(dt, backing.INST_hwmain_floatAdder_inQ);
  INST_hwmain_floatAdder_normalizeQ.dump_VCD(dt, backing.INST_hwmain_floatAdder_normalizeQ);
  INST_hwmain_floatAdder_normalizeQ1.dump_VCD(dt, backing.INST_hwmain_floatAdder_normalizeQ1);
  INST_hwmain_floatAdder_normalizeQ2.dump_VCD(dt, backing.INST_hwmain_floatAdder_normalizeQ2);
  INST_hwmain_floatAdder_normalizeQ3.dump_VCD(dt, backing.INST_hwmain_floatAdder_normalizeQ3);
  INST_hwmain_floatAdder_normalizeQ4.dump_VCD(dt, backing.INST_hwmain_floatAdder_normalizeQ4);
  INST_hwmain_floatAdder_outQ.dump_VCD(dt, backing.INST_hwmain_floatAdder_outQ);
  INST_hwmain_floatMultiplier_multQ.dump_VCD(dt, backing.INST_hwmain_floatMultiplier_multQ);
  INST_hwmain_floatMultiplier_outQ.dump_VCD(dt, backing.INST_hwmain_floatMultiplier_outQ);
  INST_hwmain_floatMultiplier_signExpZeroQ.dump_VCD(dt,
						    backing.INST_hwmain_floatMultiplier_signExpZeroQ);
  INST_hwmain_floatingQ.dump_VCD(dt, backing.INST_hwmain_floatingQ);
  INST_hwmain_inputBuffer.dump_VCD(dt, backing.INST_hwmain_inputBuffer);
  INST_hwmain_inputBufferCnt.dump_VCD(dt, backing.INST_hwmain_inputBufferCnt);
  INST_hwmain_outputBuffer.dump_VCD(dt, backing.INST_hwmain_outputBuffer);
  INST_hwmain_outputBufferCnt.dump_VCD(dt, backing.INST_hwmain_outputBufferCnt);
  INST_hwmain_ram_outQ.dump_VCD(dt, backing.INST_hwmain_ram_outQ);
  INST_hwmain_ram_ram.dump_VCD(dt, backing.INST_hwmain_ram_ram);
  INST_hwmain_ram_reqWire.dump_VCD(dt, backing.INST_hwmain_ram_reqWire);
  INST_hwmain_relayUartInQ.dump_VCD(dt, backing.INST_hwmain_relayUartInQ);
  INST_hwmain_relayUartOutQ.dump_VCD(dt, backing.INST_hwmain_relayUartOutQ);
  INST_initialized.dump_VCD(dt, backing.INST_initialized);
  INST_uart_inQ.dump_VCD(dt, backing.INST_uart_inQ);
  INST_uart_inReqId.dump_VCD(dt, backing.INST_uart_inReqId);
  INST_uart_outCnt.dump_VCD(dt, backing.INST_uart_outCnt);
  INST_uart_outQ.dump_VCD(dt, backing.INST_uart_outQ);
}
