/*
 * Generated by Bluespec Compiler (build 629c10a)
 * 
 * On Sat Jul  3 01:51:09 UTC 2021
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkBsvTop_bsim.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkBsvTop_bsim::MODEL_mkBsvTop_bsim()
{
  mkBsvTop_bsim_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkBsvTop_bsim()
{
  MODEL_mkBsvTop_bsim *model = new MODEL_mkBsvTop_bsim();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkBsvTop_bsim &INST_top = *((MOD_mkBsvTop_bsim *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_initialized__h4356;
	 tUInt8 DEF_INST_top_DEF_hwmain_relayUartInQ_i_notFull____d194;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_uart_relayOut;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_uart_relayOut;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_uart_relayIn;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_uart_relayIn;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatMultiplier_procMultResult;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatMultiplier_procMultResult;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatAdder_procIn;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatAdder_procIn;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatAdder_calcFrac;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatAdder_calcFrac;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatAdder_calcFrac2;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatAdder_calcFrac2;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatAdder_normalize;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatAdder_normalize;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatAdder_normalize1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatAdder_normalize1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatAdder_normalize2;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatAdder_normalize2;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatAdder_normalize3;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatAdder_normalize3;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatAdder_normalize4;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatAdder_normalize4;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_ttt;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_ttt;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_readFloat;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_readFloat;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_writeFloat;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_writeFloat;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_doinit;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_doinit;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_relayUartIn;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_relayUartIn;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_relayUartOut;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_relayUartOut;
	 DEF_INST_top_DEF_initialized__h4356 = INST_top.INST_initialized.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_doinit = !DEF_INST_top_DEF_initialized__h4356;
	 DEF_INST_top_DEF_WILL_FIRE_RL_doinit = DEF_INST_top_DEF_CAN_FIRE_RL_doinit;
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatAdder_calcFrac = INST_top.INST_hwmain_floatAdder_inProcQ.METH_i_notEmpty() && INST_top.INST_hwmain_floatAdder_calcQ.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatAdder_calcFrac = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatAdder_calcFrac;
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatAdder_calcFrac2 = INST_top.INST_hwmain_floatAdder_calcQ.METH_i_notEmpty() && INST_top.INST_hwmain_floatAdder_normalizeQ.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatAdder_calcFrac2 = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatAdder_calcFrac2;
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatAdder_normalize = INST_top.INST_hwmain_floatAdder_normalizeQ.METH_i_notEmpty() && INST_top.INST_hwmain_floatAdder_normalizeQ1.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatAdder_normalize = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatAdder_normalize;
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatAdder_normalize1 = INST_top.INST_hwmain_floatAdder_normalizeQ1.METH_i_notEmpty() && INST_top.INST_hwmain_floatAdder_normalizeQ2.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatAdder_normalize1 = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatAdder_normalize1;
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatAdder_normalize2 = INST_top.INST_hwmain_floatAdder_normalizeQ2.METH_i_notEmpty() && INST_top.INST_hwmain_floatAdder_normalizeQ3.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatAdder_normalize2 = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatAdder_normalize2;
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatAdder_normalize3 = INST_top.INST_hwmain_floatAdder_normalizeQ3.METH_i_notEmpty() && INST_top.INST_hwmain_floatAdder_normalizeQ4.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatAdder_normalize3 = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatAdder_normalize3;
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatAdder_normalize4 = INST_top.INST_hwmain_floatAdder_normalizeQ4.METH_i_notEmpty() && INST_top.INST_hwmain_floatAdder_outQ.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatAdder_normalize4 = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatAdder_normalize4;
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatAdder_procIn = INST_top.INST_hwmain_floatAdder_inQ.METH_i_notEmpty() && INST_top.INST_hwmain_floatAdder_inProcQ.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatAdder_procIn = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatAdder_procIn;
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatMultiplier_procMultResult = INST_top.INST_hwmain_floatMultiplier_multQ.METH_i_notEmpty() && (INST_top.INST_hwmain_floatMultiplier_signExpZeroQ.METH_i_notEmpty() && INST_top.INST_hwmain_floatMultiplier_outQ.METH_i_notFull());
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatMultiplier_procMultResult = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_floatMultiplier_procMultResult;
	 INST_top.DEF_x__h4112 = INST_top.INST_hwmain_inputBufferCnt.METH_read();
	 INST_top.DEF_hwmain_inputBufferCnt_99_EQ_3___d200 = (INST_top.DEF_x__h4112) == (tUInt8)3u;
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_readFloat = INST_top.INST_hwmain_relayUartInQ.METH_i_notEmpty() && (!(INST_top.DEF_hwmain_inputBufferCnt_99_EQ_3___d200) || (INST_top.INST_hwmain_floatMultiplier_multQ.METH_i_notFull() && INST_top.INST_hwmain_floatMultiplier_signExpZeroQ.METH_i_notFull()));
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_readFloat = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_readFloat;
	 INST_top.DEF_x__h4144 = INST_top.INST_hwmain_outputBufferCnt.METH_read();
	 INST_top.DEF_hwmain_outputBufferCnt_28_EQ_0___d229 = (INST_top.DEF_x__h4144) == (tUInt8)0u;
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_writeFloat = INST_top.INST_hwmain_relayUartOutQ.METH_i_notFull() && (!(INST_top.DEF_hwmain_outputBufferCnt_28_EQ_0___d229) || INST_top.INST_hwmain_floatMultiplier_outQ.METH_i_notEmpty());
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_writeFloat = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_writeFloat;
	 DEF_INST_top_DEF_hwmain_relayUartInQ_i_notFull____d194 = INST_top.INST_hwmain_relayUartInQ.METH_i_notFull();
	 DEF_INST_top_DEF_CAN_FIRE_RL_relayUartIn = DEF_INST_top_DEF_hwmain_relayUartInQ_i_notFull____d194 && INST_top.INST_uart_outQ.METH_i_notEmpty();
	 DEF_INST_top_DEF_WILL_FIRE_RL_relayUartIn = DEF_INST_top_DEF_CAN_FIRE_RL_relayUartIn;
	 DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_ttt = INST_top.INST_hwmain_ram_outQ.METH_i_notEmpty() && DEF_INST_top_DEF_hwmain_relayUartInQ_i_notFull____d194;
	 DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_ttt = DEF_INST_top_DEF_CAN_FIRE_RL_hwmain_ttt && !DEF_INST_top_DEF_WILL_FIRE_RL_relayUartIn;
	 DEF_INST_top_DEF_CAN_FIRE_RL_relayUartOut = INST_top.INST_hwmain_relayUartOutQ.METH_i_notEmpty() && INST_top.INST_uart_inQ.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_relayUartOut = DEF_INST_top_DEF_CAN_FIRE_RL_relayUartOut;
	 DEF_INST_top_DEF_CAN_FIRE_RL_uart_relayIn = INST_top.INST_uart_inQ.METH_i_notEmpty();
	 DEF_INST_top_DEF_WILL_FIRE_RL_uart_relayIn = DEF_INST_top_DEF_CAN_FIRE_RL_uart_relayIn;
	 DEF_INST_top_DEF_CAN_FIRE_RL_uart_relayOut = INST_top.INST_uart_outQ.METH_i_notFull();
	 DEF_INST_top_DEF_WILL_FIRE_RL_uart_relayOut = DEF_INST_top_DEF_CAN_FIRE_RL_uart_relayOut;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_doinit)
	   INST_top.RL_doinit();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatAdder_calcFrac)
	   INST_top.RL_hwmain_floatAdder_calcFrac();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatAdder_calcFrac2)
	   INST_top.RL_hwmain_floatAdder_calcFrac2();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatAdder_normalize)
	   INST_top.RL_hwmain_floatAdder_normalize();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatAdder_normalize1)
	   INST_top.RL_hwmain_floatAdder_normalize1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatAdder_normalize2)
	   INST_top.RL_hwmain_floatAdder_normalize2();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatAdder_normalize4)
	   INST_top.RL_hwmain_floatAdder_normalize4();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatAdder_normalize3)
	   INST_top.RL_hwmain_floatAdder_normalize3();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatAdder_procIn)
	   INST_top.RL_hwmain_floatAdder_procIn();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_floatMultiplier_procMultResult)
	   INST_top.RL_hwmain_floatMultiplier_procMultResult();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_readFloat)
	   INST_top.RL_hwmain_readFloat();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_ttt)
	   INST_top.RL_hwmain_ttt();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_hwmain_writeFloat)
	   INST_top.RL_hwmain_writeFloat();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_relayUartIn)
	   INST_top.RL_relayUartIn();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_relayUartOut)
	   INST_top.RL_relayUartOut();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_uart_relayOut)
	   INST_top.RL_uart_relayOut();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_uart_relayIn)
	   INST_top.RL_uart_relayIn();
	 INST_top.INST_hwmain_ram_reqWire.clk((tUInt8)1u, (tUInt8)1u);
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_uart_inQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_uart_outQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_uart_outCnt.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_uart_inReqId.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_ram_outQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_floatMultiplier_signExpZeroQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_floatMultiplier_multQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_floatMultiplier_outQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_floatAdder_inQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_floatAdder_inProcQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_floatAdder_calcQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_floatAdder_normalizeQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_floatAdder_normalizeQ1.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_floatAdder_normalizeQ2.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_floatAdder_normalizeQ3.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_floatAdder_normalizeQ4.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_floatAdder_outQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_relayUartInQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_relayUartOutQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_floatingQ.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_hwmain_inputBuffer.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_inputBufferCnt.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_outputBuffer.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_hwmain_outputBufferCnt.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_initialized.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkBsvTop_bsim::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkBsvTop_bsim_instance = new MOD_mkBsvTop_bsim(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkBsvTop_bsim_instance->INST_uart_inQ.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_uart_outQ.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_ram_outQ.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_ram_reqWire.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_floatMultiplier_signExpZeroQ.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_floatMultiplier_multQ.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_floatMultiplier_outQ.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_floatAdder_inQ.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_floatAdder_inProcQ.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_floatAdder_calcQ.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_floatAdder_normalizeQ.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_floatAdder_normalizeQ1.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_floatAdder_normalizeQ2.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_floatAdder_normalizeQ3.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_floatAdder_normalizeQ4.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_floatAdder_outQ.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_relayUartInQ.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_relayUartOutQ.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->INST_hwmain_floatingQ.set_clk_0)("CLK");
  (mkBsvTop_bsim_instance->set_clk_0)("CLK");
}
void MODEL_mkBsvTop_bsim::destroy_model()
{
  delete mkBsvTop_bsim_instance;
  mkBsvTop_bsim_instance = NULL;
}
void MODEL_mkBsvTop_bsim::reset_model(bool asserted)
{
  (mkBsvTop_bsim_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkBsvTop_bsim::get_instance()
{
  return mkBsvTop_bsim_instance;
}

/* Fill in version numbers */
void MODEL_mkBsvTop_bsim::get_version(unsigned int *year,
				      unsigned int *month,
				      char const **annotation,
				      char const **build)
{
  *year = 0u;
  *month = 0u;
  *annotation = NULL;
  *build = "629c10a";
}

/* Get the model creation time */
time_t MODEL_mkBsvTop_bsim::get_creation_time()
{
  
  /* Sat Jul  3 01:51:09 UTC 2021 */
  return 1625277069llu;
}

/* State dumping function */
void MODEL_mkBsvTop_bsim::dump_state()
{
  (mkBsvTop_bsim_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkBsvTop_bsim & mkBsvTop_bsim_backing(tSimStateHdl simHdl)
{
  static MOD_mkBsvTop_bsim *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkBsvTop_bsim(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkBsvTop_bsim::dump_VCD_defs()
{
  (mkBsvTop_bsim_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkBsvTop_bsim::dump_VCD(tVCDDumpType dt)
{
  (mkBsvTop_bsim_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkBsvTop_bsim_backing(sim_hdl));
}
